# -*- coding: utf-8 -*-
"""Overlay inglese per le sette nuove voci del Dominio 1 e per i sensori."""
import io

EN_PATH = "src/data.en.ts"

CHANGE_EN = '''  OwnershipStakeholders: {
    name: "Ownership & Stakeholders",
    definition: "The two roles objective 1.3 keeps apart in every change: the owner, who has the authority to request it and answers for the outcome, and the stakeholders, everyone the change touches, who must be identified and involved before it happens.",
    details: "They are two different roles, and exam questions put them side by side precisely to see whether you confuse them:\\n* **Ownership - who decides and who answers:** every change request has a **named** owner, not a generic department. That is the person who knows the system, who has the formal authority to seek approval, and who is asked when something goes wrong. With no owner, a failed change has nobody to roll it back and nobody to answer for it: the give-away phrase is \\"IT was handling it\\".\\n* **Stakeholders - who is affected:** the functions that will use the system after the change, those that depend on it, security, compliance, customer support and, when the service is public-facing, the customers themselves. Identifying them is a step of the process, not a courtesy.\\n* **Why they are identified beforehand:** they answer different questions. The owner answers \\"who authorizes and who is accountable\\"; the stakeholders answer \\"who must be told, consulted and trained\\". A change that succeeds technically but is announced to nobody causes the same outage as one that fails.\\n* **The typical mistakes:** confusing the owner of the **system** with the owner of the **change**, and limiting the stakeholder list to technical staff, forgetting the people who use that system every day.\\n\\n* **Focused Mini-Example:** The ERP is migrated to a new version over a weekend and the migration succeeds. On Monday, however, the call centre is down for three hours: the new interface changed the path for issuing a credit note and no operator had been told. The department was the system's main user and did not appear among the change request's stakeholders.",
    examTip: "Keep the two words apart. **Ownership** = a named person who **decides and answers** for the change · **Stakeholders** = everyone the change **touches**, to be identified, informed and where needed trained. **Exam trap:** when the scenario describes a change that succeeded technically but blocked an unaware department, the flaw is neither the backout plan nor the maintenance window: it is the failure to identify the stakeholders.",
  },
  TestResultsChange: {
    name: "Test Results",
    definition: "The documented outcomes of tests run in an environment other than production, which the approval board examines before authorizing a change.",
    details: "They are the only element of the change management package that speaks of **facts** rather than intentions:\\n* **What they are for:** the impact analysis says what is *expected* to happen; the test results say what *actually happened* when the change was tried. They are the only evidence that it works and that it breaks nothing else.\\n* **Where they are produced:** in an environment that resembles production - staging or UAT - with representative data and integrations. A test on an environment too unlike production returns a reassuring result with no value.\\n* **What the evidence must contain:** what was tested, with what data, by whom, when, and the outcome of each case - including the **failed** runs and what was fixed. A report listing only successes is not a test report.\\n* **When there is no test environment:** the correct route is not to declare them \\"unnecessary\\", but to state the residual risk, have it accepted by someone with the authority to take it on, and strengthen the backout plan.\\n\\n* **Focused Mini-Example:** A request reaches the board complete with owner, impact analysis, maintenance window and a detailed backout plan. Against \\"outcome of testing\\" the requester has written \\"not needed, minimal change\\". The board rejects it, and rightly so: without that outcome none of the other documents shows that the change works.",
    examTip: "Test results are the only item in the package that says anything about the change's **real behaviour**; everything else describes plans and intentions. **Exam trap:** \\"minimal change\\" is never a valid reason to omit them, and a request complete with everything except test outcomes is the right answer when the question asks what should have blocked approval.",
  },
  StandardOperatingProcedure: {
    name: "Standard Operating Procedure (SOP)",
    definition: "The document describing, step by step, how a recurring activity is carried out, so that the outcome does not depend on who performs it.",
    details: "The SOP turns one person's skill into a process owned by the organization:\\n* **The problem it solves:** an activity that lives only in the experience of two colleagues produces different outcomes depending on the shift, cannot be verified by anyone, and disappears when those people go on holiday or change jobs.\\n* **What it contains:** the purpose, who is authorized to perform it, the prerequisites, the exact sequence of steps with commands or screens, the final verification checks, what to do if a step fails, and a version number with the date of the last revision.\\n* **Its place in the document hierarchy:** the **policy** says *what* must be achieved and *why*; the **standard** says *with what*; the **procedure (SOP)** says *how*, in the right order. All three are mandatory; the **guideline** is advice.\\n* **Why it is a security control and not paperwork:** it makes the activity **repeatable** (same outcome from anyone), **auditable** (a reviewer compares what was done against what was prescribed) and **transferable** (a new joiner is productive in days, not months).\\n\\n* **Focused Mini-Example:** In one company the procedure for applying monthly patches exists only in the heads of two administrators. Each runs it their own way and, over the summer holidays, a less experienced colleague skips the post-reboot check, leaving two services down for a day. Written as an SOP, that check is a numbered step that cannot be missed without it showing.",
    examTip: "The SOP answers the question **\\"how is it done, step by step\\"** and is **mandatory**, unlike a guideline, which is a recommendation. **Exam trap:** when the scenario describes an activity whose outcome depends on who is on shift, the answer is the standard operating procedure - not a policy, which would only say the activity must be done, and not training, which leaves no auditable trace.",
  },
  ChangeTechnicalImplications: {
    name: "Technical Implications of a Change",
    definition: "The side effects objective 1.3 asks you to anticipate before applying a change: allow and deny lists, permitted activities, downtime, restarts, legacy applications and dependencies.",
    details: "This is the part of objective 1.3 that questions test with concrete scenarios rather than definitions:\\n* **Allow list and deny list:** a change may require **adding** the new server, application or address to the lists of what is permitted, or **removing** from block lists what is now legitimate. Forgetting it produces the classic \\"it worked in staging\\".\\n* **Restricted activities:** during the window you perform **only what was approved**. This is the rule that forbids the opportunistic fix - \\"while we are here, let me also turn off this service nobody uses\\" - because what was never analysed has neither an impact assessment nor a rollback plan.\\n* **Downtime:** it must be **estimated** beforehand, **communicated** to stakeholders and checked against the service commitments in force. Undeclared downtime breaches the SLA even when the change succeeds.\\n* **Service restart and application restart:** many settings only take effect after the service or application restarts, not when the file is saved. The restart therefore belongs **inside** the window, otherwise the change applies itself later, at the worst possible moment.\\n* **Legacy applications:** unsupported systems may not tolerate the change and may have no upgrade path at all. When they surface in the analysis, the correct route is to document the dependency and isolate them with compensating controls, not to postpone the whole change.\\n* **Dependencies:** what depends on the system being changed, and what that system depends on. This is the item impact analysis gets wrong most often, because undocumented dependencies only surface when they break.\\n\\n* **Focused Mini-Example:** During a night window an administrator changes an authentication parameter, checks that the file is correct and considers the work closed. The next morning the system still behaves the old way; later a scheduled automatic reboot applies the new configuration in the middle of the working day and three dependent applications fall over together. The restart was a foreseeable implication, and belonged inside the window.",
    examTip: "Match each implication to its symptom, because that is how questions present them. Change that **has no effect** → the service **restart** is missing · outage **in other systems** → **dependencies** not mapped · something broken that **was not in the request** → **restricted activities** violated · traffic blocked after release → **allow list** not updated · customer complaints about an outage → **downtime** not communicated.",
  },
  ChangeDocumentation: {
    name: "Change Documentation",
    definition: "Updating diagrams, policies and procedures after a change has been applied: the last step of the process, and the one skipped most often.",
    details: "It is the phase that brings no immediate benefit and without which everything else decays:\\n* **Updating diagrams:** network topology, appliance schematics, data flows and inventory must reflect the state **after** the change. An out-of-date diagram is not neutral: it misleads whoever reads it, and whoever reads it is usually responding to an incident or running an assessment.\\n* **Updating policies and procedures:** if the change alters how work is done - a new tool, an extra authorization step, a retired protocol - the procedure describing the old way must be rewritten, otherwise a document prescribing something that no longer exists stays in force.\\n* **Why it is a control:** up-to-date documentation is what makes recovery, incident analysis, onboarding and auditing possible. And it is the basis of the **next change's impact analysis**: stale documentation today means a wrong impact analysis tomorrow.\\n* **When it is done:** as part of closing the change, not \\"when there is time\\". A change is not closed until the documentation matches reality.\\n\\n* **Focused Mini-Example:** An external consultant is engaged to map the data centre's vulnerabilities and asks for the architecture diagram. They are handed a drawing more than a year old: two segments added since are missing, and a decommissioned server is still on it. The consultant works from a wrong map, and the most recent flaws fall outside the scope of the assessment.",
    examTip: "Documentation closes the change cycle, and its value always shows up **later**: during an incident, an audit, or the next change's impact analysis. **Exam trap:** when the scenario describes someone reaching a wrong conclusion because they trusted an out-of-date diagram or procedure, the answer is not a technical control but the documentation update the change management process requires.",
  },

'''

PHYS_EN = '''  AccessControlVestibule: {
    name: "Access Control Vestibule",
    definition: "A small room with two interlocked doors, only one of which can be open at a time, admitting one person at a time and making it mechanically impossible to walk in behind someone else.",
    details: "It is the only physical control that solves tailgating rather than discouraging or recording it:\\n* **How it works:** the person opens the first door with their badge and steps into the vestibule; the first door must close before the second can open. Many installations add a weight sensor or a people counter, which halts the cycle if more than one individual is inside.\\n* **The problem it solves:** **tailgating**, where a stranger follows an employee who does not notice, and **piggybacking**, where the employee deliberately holds the door open out of courtesy. Training reduces both but never eliminates them, because they ask one person to be rude to another.\\n* **Why it is the right answer in scenarios:** cameras document what happened afterwards, signs discourage, training lowers the frequency. Only the vestibule makes two people passing together **physically impossible**.\\n* **Practical limits worth knowing:** it slows the flow, so it suits the entrance to critical areas - server room, laboratories, vaults - and not a lobby that must clear hundreds of people at shift start. It also needs an escape route compliant with fire regulations, because in an emergency people must be able to get out.\\n\\n* **Focused Mini-Example:** A data centre entrance is protected by a badge-reader turnstile, but the register does not add up: physical presences outnumber badge swipes. Cameras show employees courteously holding the door for whoever follows them. Once the gate is replaced with an interlocked double-door vestibule the problem stops: the second door will not open until the first is shut.",
    examTip: "**Mind the name:** the SY0-701 objectives call it an **access control vestibule**; *mantrap* is the historical term, still common in the field but not the one you will find among the exam options. **Exam trap:** when the scenario describes tailgating or piggybacking and asks for the control that makes it **impossible**, the answer is the vestibule - not cameras, which detect; not signs, which deter; not training, which only lowers the frequency.",
  },
  PhysicalLighting: {
    name: "Lighting",
    definition: "Security lighting of outdoor areas and access points: a physical control that discourages intrusion attempts and, at the same time, makes the other surveillance controls usable.",
    details: "It is the most underrated physical control, and the one the others depend on:\\n* **The dual function the exam tests:** lighting is **deterrent**, because anyone acting covertly avoids spaces where they can be seen and recognised, and it is **enabling**, because without light cameras return unusable images and guards see nothing.\\n* **Where it applies:** perimeter and fences, car parks and yards, entrances and emergency exits, loading bays, walkways, and any area where a camera must capture faces or number plates.\\n* **Design criteria:** uniformity, because the shadow between two lamp posts is exactly where someone hides; no glare towards the cameras; **motion-sensor** activation where permanently lit is not sustainable; and emergency power on critical points, because a power cut must not switch off lighting and surveillance together.\\n* **The link with cameras:** a camera is only as good as the light it has. Before replacing units with higher-resolution models it is worth checking the lighting: for the same money it is almost always the change that produces the biggest improvement.\\n\\n* **Focused Mini-Example:** A remote industrial site suffers night-time thefts from its yard. Cameras are already in place, but at night they produce unusable footage. Lighting the yard and completing the fence cuts the attempts immediately - anyone approaching knows they are visible - and the recordings finally become usable as evidence.",
    examTip: "Lighting appears among the physical controls of objective 1.2 and is the classic control that is **deterrent and enabling at once**. **Exam trap:** when the scenario complains about unusable night-time footage, the answer is not buying better cameras but **lighting the area**; and when it asks how to discourage attempts *before* they happen, light and fencing come before video surveillance.",
  },

'''


def insert_before(text, anchor, block, label):
    i = text.find(anchor)
    if i < 0:
        raise SystemExit("%s: ancora non trovata" % label)
    return text[:i] + block + text[i:]


s = io.open(EN_PATH, encoding="utf-8").read()
s = insert_before(s, "  /* ---------------- Domain 1 · Group 5: Cryptography ---------------- */", CHANGE_EN, "gruppo 5")
s = insert_before(s, "  /* ---------------- Domain 1 · Group 7: Deception Technologies ---------------- */", PHYS_EN, "gruppo 7")

OLD = "details: \"Sensors positioned to ensure the environmental stability and anti-intrusion protection of critical areas:\\n* **Intrusion Detection:** Volumetric infrared (PIR) sensors or magnetic contacts positioned on the hinges of doors and windows.\\n* **Environmental Detection:** Humidity sensors, smoke sensors, rapid-rise heat detectors and flood sensors under raised floors."
NEW = "details: \"Sensors positioned to ensure the environmental stability and anti-intrusion protection of critical areas.\\n* **The four types objective 1.2 names, and each one's weakness:**\\n  - **Infrared (PIR, passive):** detects **body heat in motion**. Cheap and ubiquitous, but it loses sensitivity when the ambient temperature approaches body temperature - typically on summer nights in a warehouse - and it cannot see through glass.\\n  - **Pressure:** detects **weight** on a surface: sensitive mats, platforms, raised floors. Simple and reliable, but it covers only the surface it is installed on and is bypassed by walking elsewhere.\\n  - **Microwave:** emits radio waves and measures the change in the reflected signal, so it detects **movement** regardless of heat, even in total darkness. It covers large volumes, but it passes through thin walls and can false-positive on movement beyond them.\\n  - **Ultrasonic:** same principle with high-frequency sound waves. Sensitive to small movements, but also to draughts from air conditioning and to noise, which make it prone to false alarms.\\n* **Why they are often combined:** **dual-technology** sensors (typically infrared plus microwave) raise the alarm only when **both** detect, which cuts each one's false positives without sacrificing coverage.\\n* **Environmental Detection:** beyond intrusion, humidity sensors, smoke sensors, rapid-rise heat detectors and flood sensors under raised floors."
if s.count(OLD) != 1:
    raise SystemExit("EN sensori: %d occorrenze" % s.count(OLD))
s = s.replace(OLD, NEW)

OLD_TIP = "examTip: \"Environmental sensors in the server room are essential for preserving the Availability of the hardware by mitigating damage from flooding or overheating.\""
NEW_TIP = "examTip: \"Environmental sensors in the server room preserve the hardware's **Availability** by mitigating flooding and overheating. **Exam trap:** on intrusion sensors the question is almost always settled by the **weakness** of the wrong type, not the merit of the right one. Room as warm as a human body → **infrared** cannot see, you need **microwave** · uneven or cluttered floor → a **pressure** sensor does not cover it · draughts and noise → **ultrasonic** gives false alarms · too many false positives in general → **dual-technology** sensor.\""
if s.count(OLD_TIP) != 1:
    raise SystemExit("EN tip sensori: %d occorrenze" % s.count(OLD_TIP))
s = s.replace(OLD_TIP, NEW_TIP)

io.open(EN_PATH, "w", encoding="utf-8").write(s)
print("overlay inglese aggiunto")
