# -*- coding: utf-8 -*-
"""Colma le sotto-voci degli obiettivi 1.2 e 1.3 prive di voce di glossario.

Obiettivo 1.3 elenca 14 sotto-voci: solo 5 avevano una voce propria
(approval process, impact analysis, backout plan, maintenance window,
version control). Le altre erano trattate nelle spiegazioni delle domande
ma introvabili per chi consulta il glossario.

Obiettivo 1.2 elenca 8 controlli fisici: mancavano access control vestibule
e lighting.
"""
import io

IT_PATH = "src/data.ts"
EN_PATH = "src/data.en.ts"

# ------------------------------------------------------------------ #
# Nuove voci italiane, gruppo "4. Change Management (Obj 1.3)"
# ------------------------------------------------------------------ #
CHANGE_IT = '''      {
        name: "Ownership & Stakeholders",
        checklistKey: "OwnershipStakeholders",
        definition: "Le due figure che l'obiettivo 1.3 tiene distinte in ogni modifica: il titolare (ownership), che ha l'autorità di chiederla e risponde dell'esito, e le parti interessate (stakeholder), cioè tutti coloro che la modifica tocca e che vanno identificati e coinvolti prima che avvenga.",
        details: "Sono due ruoli diversi, e le domande d'esame li accostano proprio per vedere se li confondi:\\n* **Ownership — chi decide e chi risponde:** ogni richiesta di modifica ha un titolare **nominato**, non un reparto generico. È la persona che conosce il sistema, che ha l'autorità formale per chiedere l'approvazione e a cui si risale se qualcosa va storto. Senza un titolare, una modifica fallita non ha nessuno che la riporti indietro e nessuno a cui chiedere conto: la frase spia è «se ne occupava l'IT».\\n* **Stakeholder — chi ne subisce gli effetti:** le funzioni che useranno il sistema dopo la modifica, quelle che dipendono da esso, la sicurezza, la conformità, l'assistenza clienti e, quando il servizio è esposto, i clienti stessi. Identificarli è un passo del processo, non una cortesia.\\n* **Perché si identificano prima:** rispondono a domande diverse. Il titolare risponde a «chi autorizza e chi risponde»; gli stakeholder a «chi va avvisato, consultato e formato». Una modifica tecnicamente riuscita ma comunicata a nessuno produce lo stesso disservizio di una fallita.\\n* **Gli errori tipici:** confondere il titolare del **sistema** con il titolare della **modifica**, e limitare l'elenco degli stakeholder ai soli tecnici, dimenticando chi quel sistema lo usa tutti i giorni.\\n\\n* **Piccolo Esempio Concentrato:** Il gestionale viene migrato a una nuova versione in un fine settimana e la migrazione riesce. Il lunedì però il call center resta fermo tre ore: la nuova interfaccia ha cambiato il percorso per emettere una nota di credito e nessun operatore era stato avvisato. Il reparto era il principale utilizzatore del sistema e non compariva fra le parti interessate della richiesta.",
        examTip: "Tieni distinte le due parole. **Ownership** = una persona nominata che **decide e risponde** della modifica · **Stakeholder** = tutti quelli che la modifica **tocca**, da identificare, informare e all'occorrenza formare. **Trappola d'esame:** quando lo scenario descrive una modifica riuscita sul piano tecnico ma che ha bloccato un reparto ignaro, il difetto non è il piano di backout né la finestra di manutenzione: è la mancata identificazione delle parti interessate."
      },
      {
        name: "Test Results",
        checklistKey: "TestResultsChange",
        definition: "Gli esiti documentati delle prove eseguite in un ambiente diverso dalla produzione, che il comitato di approvazione esamina prima di autorizzare una modifica.",
        details: "Sono l'unico elemento del pacchetto di change management che parla di **fatti** anziché di intenzioni:\\n* **A che cosa servono:** l'analisi d'impatto dice che cosa *ci si aspetta* che accada; i risultati dei test dicono che cosa *è accaduto davvero* quando la modifica è stata provata. Sono la sola prova che funziona e che non rompe altro.\\n* **Dove si producono:** in un ambiente che somiglia alla produzione — staging o collaudo — con dati e integrazioni rappresentativi. Una prova su un ambiente troppo diverso restituisce un esito rassicurante e privo di valore.\\n* **Che cosa deve contenere l'evidenza:** che cosa è stato provato, con quali dati, da chi, quando, e l'esito di ciascun caso — comprese le prove **fallite** e ciò che è stato corretto. Un rapporto che elenca solo i successi non è un rapporto di test.\\n* **Quando l'ambiente di collaudo non c'è:** la strada corretta non è dichiararli «non necessari», ma dichiarare il rischio residuo, farlo accettare da chi ha l'autorità di assumerselo e rafforzare il piano di backout.\\n\\n* **Piccolo Esempio Concentrato:** Una richiesta arriva al comitato completa di titolare, analisi d'impatto, finestra di manutenzione e piano di backout dettagliato. Alla voce «esito delle verifiche in collaudo» il richiedente ha scritto «non necessario, modifica minima». Il comitato la respinge, e fa bene: senza quell'esito nessuno degli altri documenti dimostra che la modifica funzioni.",
        examTip: "I risultati dei test sono l'unico elemento del pacchetto che dice qualcosa sul **comportamento reale** della modifica; tutti gli altri descrivono piani e intenzioni. **Trappola d'esame:** «modifica minima» non è mai una motivazione valida per ometterli, e una richiesta completa di tutto tranne gli esiti delle prove è la risposta corretta quando la domanda chiede che cosa avrebbe dovuto impedire l'approvazione."
      },
      {
        name: "Standard Operating Procedure (SOP)",
        checklistKey: "StandardOperatingProcedure",
        definition: "Il documento che descrive passo per passo come si esegue un'attività ricorrente, così che l'esito non dipenda da chi la esegue.",
        details: "La SOP trasforma la competenza di una persona in un processo dell'organizzazione:\\n* **Il problema che risolve:** un'attività che vive solo nell'esperienza di due colleghi produce esiti diversi a seconda del turno, non è verificabile da nessuno e sparisce quando quelle persone vanno in ferie o cambiano lavoro.\\n* **Che cosa contiene:** lo scopo, chi è autorizzato a eseguirla, i prerequisiti, la sequenza esatta dei passi con i comandi o le schermate, i controlli di verifica finali, che cosa fare se un passo fallisce, e un numero di versione con la data dell'ultima revisione.\\n* **Il posto nella gerarchia documentale:** la **policy** dice *che cosa* si deve ottenere e *perché*; lo **standard** dice *con che cosa*; la **procedura (SOP)** dice *come*, nell'ordine giusto. Tutte e tre sono obbligatorie; la **linea guida** è invece un consiglio.\\n* **Perché è un controllo di sicurezza e non burocrazia:** rende l'attività **ripetibile** (stesso esito da chiunque), **verificabile** (un auditor confronta ciò che è stato fatto con ciò che era prescritto) e **trasferibile** (una persona nuova è operativa in giorni, non in mesi).\\n\\n* **Piccolo Esempio Concentrato:** In un'azienda la procedura per applicare le patch mensili esiste solo nella testa di due amministratori. Ognuno la esegue a modo suo e, durante le ferie estive, un collega meno esperto salta la verifica successiva al riavvio lasciando due servizi fermi per un giorno. Scritta come SOP, quella verifica è un passo numerato che non si può omettere senza che risulti.",
        examTip: "La SOP risponde alla domanda **«come si fa, passo per passo»** ed è **obbligatoria**, a differenza della linea guida che è una raccomandazione. **Trappola d'esame:** quando lo scenario descrive un'attività il cui esito dipende da chi è di turno, la risposta è la procedura operativa standard — non una policy, che direbbe soltanto che l'attività va svolta, e non un corso di formazione, che non lascia alcuna traccia verificabile."
      },
      {
        name: "Implicazioni tecniche di una modifica",
        checklistKey: "ChangeTechnicalImplications",
        definition: "Gli effetti collaterali che l'obiettivo 1.3 chiede di prevedere prima di applicare una modifica: liste di autorizzazione e di blocco, attività consentite, fermo del servizio, riavvii, applicazioni legacy e dipendenze.",
        details: "Sono la parte dell'obiettivo 1.3 che le domande verificano con scenari concreti, non con definizioni:\\n* **Allow list e deny list:** una modifica può richiedere di **aggiungere** il nuovo server, la nuova applicazione o il nuovo indirizzo agli elenchi di ciò che è consentito, o di **togliere** dagli elenchi di blocco ciò che ora è legittimo. Dimenticarlo produce il classico «in collaudo funzionava».\\n* **Restricted activities (attività limitate):** durante la finestra si esegue **solo ciò che è stato approvato**. È la regola che vieta l'intervento opportunistico — «visto che siamo qui, disattivo anche questo servizio che non usa nessuno» — perché ciò che non è stato analizzato non ha né valutazione d'impatto né piano di ripristino.\\n* **Downtime (fermo del servizio):** va **stimato** prima, **comunicato** alle parti interessate e confrontato con gli impegni di servizio in essere. Un fermo non dichiarato viola l'SLA anche quando la modifica riesce.\\n* **Service restart e application restart:** molte configurazioni diventano effettive solo dopo il riavvio del servizio o dell'applicazione, non al salvataggio del file. Il riavvio va quindi pianificato **dentro** la finestra, altrimenti la modifica si applica da sola più tardi, nel momento peggiore.\\n* **Legacy applications:** i sistemi fuori supporto possono non tollerare la modifica e non avere alcun percorso di aggiornamento. Quando emergono nell'analisi, la via corretta è documentare la dipendenza e isolarli con controlli compensativi, non rinviare l'intera modifica.\\n* **Dependencies (dipendenze):** ciò che dipende dal sistema che si modifica e ciò da cui quel sistema dipende. È la voce che l'analisi d'impatto sbaglia più spesso, perché le dipendenze non documentate si scoprono solo quando si rompono.\\n\\n* **Piccolo Esempio Concentrato:** Durante una finestra notturna un amministratore modifica un parametro di autenticazione, verifica che il file sia corretto e considera chiusa l'attività. La mattina dopo il comportamento del sistema è ancora quello vecchio; più tardi un riavvio automatico pianificato applica la nuova configurazione in pieno orario di lavoro e tre applicazioni dipendenti cadono insieme. Il riavvio era un'implicazione prevedibile, e andava eseguito dentro la finestra.",
        examTip: "Associa ogni implicazione al suo sintomo, perché è così che le domande te la presentano. Modifica che **non ha effetto** → manca il **riavvio** del servizio · disservizio **in altri sistemi** → **dipendenze** non mappate · qualcosa rotto che **non era nella richiesta** → violate le **attività limitate** · traffico bloccato dopo il rilascio → **allow list** non aggiornata · reclami dei clienti per un fermo → **downtime** non comunicato."
      },
      {
        name: "Documentazione della modifica",
        checklistKey: "ChangeDocumentation",
        definition: "L'aggiornamento dei diagrammi, delle policy e delle procedure dopo che una modifica è stata applicata: l'ultimo passo del processo, e quello che viene saltato più spesso.",
        details: "È la fase che non produce alcun beneficio immediato e senza la quale tutto il resto si degrada:\\n* **Aggiornamento dei diagrammi:** topologia di rete, schemi degli apparati, flussi dei dati e inventario devono riflettere lo stato **dopo** la modifica. Un diagramma non aggiornato non è neutro: induce in errore chi lo consulta, e chi lo consulta di solito sta rispondendo a un incidente o conducendo una valutazione.\\n* **Aggiornamento di policy e procedure:** se la modifica cambia il modo di lavorare — un nuovo strumento, un passaggio di autorizzazione in più, un protocollo dismesso — la procedura che descriveva il vecchio modo va riscritta, altrimenti resta in vigore un documento che prescrive qualcosa che non esiste più.\\n* **Perché è un controllo:** la documentazione aggiornata è ciò che rende possibili il ripristino, l'analisi di un incidente, l'inserimento di personale nuovo e l'audit. Ed è la base dell'**analisi d'impatto della modifica successiva**: documentazione vecchia oggi significa analisi d'impatto sbagliata domani.\\n* **Quando si esegue:** come parte della chiusura della modifica, non «quando ci sarà tempo». Una modifica non è chiusa finché la documentazione non corrisponde alla realtà.\\n\\n* **Piccolo Esempio Concentrato:** Un consulente esterno riceve l'incarico di mappare le vulnerabilità del data center e chiede il diagramma dell'architettura. Gli viene consegnato uno schema di più di un anno prima: due segmenti introdotti nel frattempo non compaiono e un server dismesso c'è ancora. Il consulente lavora su una mappa sbagliata, e le falle più recenti restano fuori dal perimetro dell'analisi.",
        examTip: "La documentazione chiude il ciclo della modifica, e il suo valore si manifesta sempre **dopo**: durante un incidente, un audit o l'analisi d'impatto del cambiamento successivo. **Trappola d'esame:** quando lo scenario descrive qualcuno che sbaglia una valutazione perché si è fidato di uno schema o di una procedura non aggiornati, la risposta non è un controllo tecnico ma l'aggiornamento della documentazione previsto dal processo di change management."
      }
'''

# ------------------------------------------------------------------ #
# Nuove voci italiane, gruppo "6. Physical Security (Obj 1.2)"
# ------------------------------------------------------------------ #
PHYS_IT = '''      {
        name: "Access Control Vestibule",
        checklistKey: "AccessControlVestibule",
        definition: "Un piccolo locale con due porte interbloccate, di cui una sola può essere aperta per volta, che ammette una persona alla volta e rende meccanicamente impossibile entrare accodandosi a qualcun altro.",
        details: "È l'unico controllo fisico che risolve il tailgating invece di scoraggiarlo o registrarlo:\\n* **Come funziona:** la persona apre la prima porta con il proprio badge ed entra nel vestibolo; la prima porta deve richiudersi prima che la seconda possa aprirsi. Molti impianti aggiungono un sensore di peso o un conteggio delle persone, che blocca il ciclo se all'interno c'è più di un individuo.\\n* **Il problema che risolve:** il **tailgating**, in cui l'estraneo si accoda a un dipendente che non se ne accorge, e il **piggybacking**, in cui il dipendente gli tiene volontariamente la porta per cortesia. Sono comportamenti che la formazione riduce ma non elimina, perché chiedono a una persona di essere scortese con un'altra.\\n* **Perché è la risposta corretta negli scenari:** le telecamere documentano l'accaduto a posteriori, i cartelli dissuadono, la formazione riduce la frequenza. Solo il vestibolo rende il passaggio di due persone **fisicamente impossibile**.\\n* **Limiti pratici da conoscere:** rallenta il flusso, quindi è adatto agli ingressi di aree critiche — sala server, laboratori, caveau — e non a un atrio che deve smaltire centinaia di persone a inizio turno. Richiede inoltre una via di esodo conforme alle norme antincendio, perché in emergenza le persone devono poter uscire.\\n\\n* **Piccolo Esempio Concentrato:** L'ingresso di un data center è protetto da un tornello con lettore di badge, ma il registro non torna: le presenze fisiche superano le strisciate. Le telecamere mostrano dipendenti che, per cortesia, tengono aperta la porta a chi li segue. Sostituito il varco con un vestibolo a doppia porta interbloccata, il fenomeno cessa: la seconda porta non si apre finché la prima non è chiusa.",
        examTip: "**Attenzione al nome:** gli obiettivi SY0-701 lo chiamano **access control vestibule**; *mantrap* è il termine storico, ancora diffuso sul campo ma non quello che troverai fra le opzioni d'esame. **Trappola d'esame:** quando lo scenario descrive tailgating o piggybacking e chiede il controllo che lo rende **impossibile**, la risposta è il vestibolo — non le telecamere, che rilevano; non i cartelli, che dissuadono; non la formazione, che riduce soltanto la frequenza."
      },
      {
        name: "Lighting",
        checklistKey: "PhysicalLighting",
        definition: "L'illuminazione di sicurezza delle aree esterne e dei punti di accesso: un controllo fisico che scoraggia i tentativi di intrusione e, insieme, rende utilizzabili gli altri controlli di sorveglianza.",
        details: "È il controllo fisico più sottovalutato, e quello da cui dipendono gli altri:\\n* **La doppia funzione, che l'esame verifica:** l'illuminazione è **deterrente**, perché chi agisce di nascosto evita gli spazi in cui può essere visto e riconosciuto, ed è **abilitante**, perché senza luce le telecamere restituiscono immagini inutilizzabili e le guardie non vedono nulla.\\n* **Dove si applica:** perimetro e recinzioni, parcheggi e piazzali, ingressi e uscite di sicurezza, banchine di carico, percorsi pedonali e ogni area in cui una telecamera debba riprendere volti o targhe.\\n* **Criteri progettuali:** uniformità, perché le zone d'ombra fra due lampioni sono esattamente il punto in cui ci si nasconde; assenza di abbagliamento verso le telecamere; attivazione da **sensore di movimento** dove una luce accesa in permanenza non è sostenibile; alimentazione di emergenza sui punti critici, perché un'interruzione di corrente non deve spegnere insieme luci e sorveglianza.\\n* **Il legame con le telecamere:** una telecamera è buona quanto la luce che ha. Prima di sostituire gli apparati con modelli a risoluzione maggiore conviene verificare l'illuminazione: a parità di spesa è quasi sempre l'intervento che produce il miglioramento più grande.\\n\\n* **Piccolo Esempio Concentrato:** Un sito industriale periferico subisce furti notturni dal piazzale. Le telecamere ci sono già, ma di notte producono immagini inservibili. Illuminando il piazzale e completando la recinzione i tentativi calano subito — chi si avvicina sa di essere visibile — e le registrazioni diventano finalmente utilizzabili come prova.",
        examTip: "L'illuminazione compare fra i controlli fisici dell'obiettivo 1.2 ed è l'esempio tipico di controllo **deterrente e abilitante insieme**. **Trappola d'esame:** quando lo scenario lamenta riprese notturne inservibili, la risposta non è comprare telecamere migliori ma **illuminare l'area**; e quando chiede di scoraggiare i tentativi *prima* che avvengano, luce e recinzione vengono prima della videosorveglianza."
      }
'''


def insert_after(text, anchor, block, label):
    """Inserisce `block` come nuova voce subito dopo la voce che termina in `anchor`."""
    i = text.find(anchor)
    if i < 0:
        raise SystemExit("%s: ancora non trovata" % label)
    # `anchor` termina con "      }\n    ]" : si inserisce una virgola e la nuova voce
    end = i + len(anchor)
    head, tail = text[:end], text[end:]
    if not head.endswith("      }\n    ]"):
        raise SystemExit("%s: forma inattesa" % label)
    head = head[: -len("\n    ]")] + ",\n" + block.rstrip("\n") + "\n    ]"
    return head + tail


s = io.open(IT_PATH, encoding="utf-8").read()

ANCHOR_CHANGE = "Il controllo di versione è fondamentale per l'integrità del software e previene modifiche non tracciate o sovrascritture accidentali.\"\n      }\n    ]"
ANCHOR_PHYS = "In un data center, il mantenimento di un'umidità e di una temperatura controllate tramite sistemi HVAC è vitale per prevenire scariche elettrostatiche (ESD, causate da umidità troppo bassa) e cortocircuiti (causati da condensa per umidità troppo alta).\"\n      }\n    ]"

s = insert_after(s, ANCHOR_CHANGE, CHANGE_IT, "gruppo Change Management")
s = insert_after(s, ANCHOR_PHYS, PHYS_IT, "gruppo Physical Security")

# Sensori: l'obiettivo 1.2 ne nomina quattro tipi, la voce ne trattava due.
OLD_SENS = "details: \"Sensori posizionati per garantire la stabilità ambientale ed antintrusione delle aree critiche:\\n* **Rilevamento Intrusione:** Sensori volumetrici a infrarossi (PIR) o contatti magnetici posizionati sui cardini di porte e finestre.\\n* **Rilevamento Ambientale:** Sensori di umidità, fumo, rilevatori di calore ad innalzamento rapido e sensori di allagamento sotto i pavimenti fluttuanti."
NEW_SENS = "details: \"Sensori posizionati per garantire la stabilità ambientale ed antintrusione delle aree critiche.\\n* **I quattro tipi nominati dall'obiettivo 1.2, e il difetto di ciascuno:**\\n  - **Infrarosso (PIR, passivo):** rileva il **calore corporeo in movimento**. Economico e diffusissimo, ma perde sensibilità quando la temperatura ambiente si avvicina a quella del corpo — tipicamente nelle notti d'estate in un capannone — e non vede attraverso il vetro.\\n  - **Pressione:** rileva il **peso** su una superficie: tappeti sensibili, pedane, pavimenti tecnici. Semplice e affidabile, ma copre solo la superficie su cui è installato e si aggira camminando altrove.\\n  - **Microonde:** emette onde radio e misura la variazione del segnale riflesso, quindi rileva il **movimento** indipendentemente dal calore, anche al buio totale. Copre volumi ampi, ma attraversa pareti sottili e può dare falsi positivi per il movimento oltre il muro.\\n  - **Ultrasuoni:** stesso principio, con onde sonore ad alta frequenza. Sensibile ai piccoli movimenti, ma anche alle correnti d'aria dei condizionatori e ai rumori, che lo rendono soggetto a falsi allarmi.\\n* **Perché spesso si combinano:** i sensori **a doppia tecnologia** (tipicamente infrarosso più microonde) fanno scattare l'allarme solo quando **entrambi** rilevano, il che abbatte i falsi positivi di ciascuno senza sacrificarne la copertura.\\n* **Rilevamento Ambientale:** oltre all'antintrusione, sensori di umidità, fumo, rilevatori di calore ad innalzamento rapido e sensori di allagamento sotto i pavimenti fluttuanti."
if s.count(OLD_SENS) != 1:
    raise SystemExit("sensori: %d occorrenze" % s.count(OLD_SENS))
s = s.replace(OLD_SENS, NEW_SENS)

OLD_SENS_TIP = "examTip: \"I sensori ambientali in sala server sono fondamentali per preservare la Disponibilità dell'hardware mitigando danni da allagamenti o surriscaldamenti.\""
NEW_SENS_TIP = "examTip: \"I sensori ambientali in sala server preservano la **Disponibilità** dell'hardware mitigando allagamenti e surriscaldamenti. **Trappola d'esame:** sui sensori antintrusione la domanda si risolve quasi sempre sul **difetto** del tipo sbagliato, non sul pregio di quello giusto. Ambiente caldo quanto un corpo umano → l'**infrarosso** non vede, serve **microonde** · pavimento irregolare o ingombro → il sensore a **pressione** non copre · correnti d'aria e rumore → gli **ultrasuoni** danno falsi allarmi · troppi falsi positivi in generale → sensore a **doppia tecnologia**.\""
if s.count(OLD_SENS_TIP) != 1:
    raise SystemExit("tip sensori: %d occorrenze" % s.count(OLD_SENS_TIP))
s = s.replace(OLD_SENS_TIP, NEW_SENS_TIP)

io.open(IT_PATH, "w", encoding="utf-8").write(s)
print("Dominio 1: 7 voci aggiunte, voce Sensors ampliata")
