/**
 * Generates docs/gap-analysis.md (ROADMAP: "Analisi dei gap"): the concepts
 * that still have no practical example, and the real-world figures in the
 * study content (fines, percentages, amounts) that do not name their source.
 * Question scenarios and the examples themselves are left out: their numbers
 * are invented for the exercise, not facts to verify.
 *
 * The output is deterministic (no dates), so tests/gapAnalysis.test.ts can
 * fail CI when the committed file is out of date.
 *
 * Usage: npm run gap-analysis
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { getAllTopics } from "../src/localizedData";
import { DOMAIN_GUIDES_IT } from "../src/domainGuides";
import type { Lang } from "../src/i18n";
import { CONCEPT_CITATIONS } from "../src/citations";
import { SOURCES } from "../src/contentReview";

export const GAP_ANALYSIS_PATH = path.join("docs", "gap-analysis.md");

const DOMAINS = [1, 2, 3, 4, 5];

/** A worked example: a practice callout, an "Examples" list, or an inline "e.g.". */
const EXAMPLE: Record<Lang, RegExp> = {
  it: /\*\*[^*]*\b(Esemp|Nota pratica|Scenario)[^*]*:\*\*|\bes\.\s|ad esempio|per esempio/i,
  en: /\*\*[^*]*\b(Example|Mini-Example|Practical note|Scenario)[^*]*:\*\*|\be\.g\.|for example|for instance/i,
};

/** Concepts of a language with no worked example, as "domain:checklistKey". */
export function conceptsWithoutExample(lang: Lang): { ref: string; name: string; domain: number }[] {
  return DOMAINS.flatMap((d) =>
    getAllTopics(lang)[d]
      .flatMap((g) => g.subtopics)
      .filter((s) => !EXAMPLE[lang].test(`${s.details}\n${s.examTip}`))
      .map((s) => ({ ref: `${d}:${s.checklistKey}`, name: s.name, domain: d }))
  );
}

/**
 * A figure set by a law, a regulator or a contract template: a fine as a share
 * of turnover, an amount in millions, a legal deadline. These change over
 * time and must say where they come from; percentages that are arithmetic
 * (the "nines" of an SLA) or conceptual (100% of packets) are not listed.
 */
const FIGURE = /\b\d[\d.,]*\s?%\s+del\s+fatturato|\b\d[\d.,]*\s?(?:milioni|miliardi)\s+di\s+(?:euro|dollari)\b|\bentro\s+\d+\s+(?:ore|giorni)\b/i;
/** A sentence that names where its figure comes from. */
const CITED = /\b(?:art\.|artt\.|articolo|SP 800-|ISO\/IEC|RFC \d+|PCI DSS \d)/i;
/** Lines that are examples: their figures are invented for the exercise. */
const EXAMPLE_LINE = /^\s*\*\s\*\*[^*]*\b(Esemp|Nota pratica|Scenario)[^*]*:\*\*/i;

/** Sentences of the Italian study content with a real-world figure and no source. */
export function unsourcedFigures(): { where: string; sentence: string }[] {
  const texts: { where: string; text: string }[] = [];
  for (const d of DOMAINS) {
    for (const s of getAllTopics("it")[d].flatMap((g) => g.subtopics)) {
      texts.push({ where: `concetto ${d}:${s.checklistKey}`, text: [s.definition, s.details, s.examTip].join("\n") });
    }
    const guide = DOMAIN_GUIDES_IT[d];
    // The guide's own teaching text; its scenarios are exercises with invented numbers.
    const teaching = [...guide.decisionPatterns, ...guide.connections, ...(guide.commonTraps ?? []).flatMap((t) => [t.misconception, t.correction])];
    texts.push({ where: `guida del Dominio ${d}`, text: teaching.join("\n") });
  }
  return texts.flatMap(({ where, text }) =>
    text
      .split("\n")
      .filter((line) => !EXAMPLE_LINE.test(line))
      .flatMap((line) => line.split(/(?<=[.;])\s+(?=[A-ZÀ-Ü*])/))
      .filter((sentence) => FIGURE.test(sentence) && !CITED.test(sentence))
      .map((sentence) => ({ where, sentence: sentence.replace(/\*\*/g, "").replace(/^\s*\*\s*/, "").trim() }))
  );
}

export function renderGapAnalysis(): string {
  const missing = conceptsWithoutExample("it");
  const total = DOMAINS.reduce((n, d) => n + getAllTopics("it")[d].flatMap((g) => g.subtopics).length, 0);
  const figures = unsourcedFigures();
  const lines: string[] = [
    "# Analisi dei gap",
    "",
    "<!-- Generato da scripts/gap-analysis.ts: non modificare a mano, esegui `npm run gap-analysis`. -->",
    "",
    "Che cosa manca ai contenuti di studio: i concetti senza un esempio pratico e le cifre reali",
    "(sanzioni, percentuali, importi) che non dicono da dove vengono. La copertura degli obiettivi con",
    "le domande è nella [matrice di copertura](coverage-matrix.md).",
    "",
    "> **English summary.** The study concepts that still have no practical example, and the",
    "> real-world figures in the study content that do not cite their source. Generated by",
    "> `scripts/gap-analysis.ts`; `tests/gapAnalysis.test.ts` keeps it current and fails if a new",
    "> concept is added without an example.",
    "",
    "## Concetti senza esempio pratico",
    "",
    `${missing.length} concetti su ${total} non hanno un esempio: né un «Piccolo Esempio Concentrato», né un elenco di`,
    "esempi, né un «per esempio» nel testo. Per aggiungerne uno segui il modello in",
    "[`content-templates.md`](content-templates.md), in italiano e in inglese, poi togli il concetto da",
    "`tests/fixtures/concepts-without-example.json`: l'elenco può solo accorciarsi.",
    "",
    "| Dominio | Concetti | Senza esempio |",
    "|---|---|---|",
    ...DOMAINS.map((d) => {
      const n = getAllTopics("it")[d].flatMap((g) => g.subtopics).length;
      return `| ${d} | ${n} | ${missing.filter((m) => m.domain === d).length} |`;
    }),
    "",
  ];
  for (const d of DOMAINS) {
    const inDomain = missing.filter((m) => m.domain === d);
    if (inDomain.length === 0) continue;
    lines.push(`### Dominio ${d}`, "", ...inDomain.map((m) => `- ${m.name} (\`${m.ref}\`)`), "");
  }
  lines.push(
    "## Cifre senza fonte",
    "",
    "Frasi dei contenuti di studio con una cifra stabilita da una norma o da un regolatore (sanzioni in",
    "percentuale del fatturato, importi, scadenze) che non citano l'articolo o il documento da cui viene.",
    "Queste cifre cambiano nel tempo e vanno verificabili. Gli scenari delle domande e gli esempi sono esclusi, perché i loro numeri",
    "sono inventati per l'esercizio. Per chiudere una voce aggiungi la fonte nella frase (per esempio",
    "«GDPR, art. 83, par. 5») oppure riformula senza la cifra.",
    ""
  );
  if (figures.length === 0) lines.push("Nessuna.", "");
  else lines.push(...figures.map((f) => `- ${f.where}: «${f.sentence}»`), "");
  const cited = Object.entries(CONCEPT_CITATIONS).sort(([a], [b]) => a.localeCompare(b, "en", { numeric: true }));
  lines.push(
    "## Fonti delle affermazioni normative",
    "",
    `${cited.length} concetti nominano una legge, uno standard o un sistema di punteggio; ognuno cita il documento,`,
    "e l'articolo quando il testo afferma una regola precisa. Le citazioni sono in `src/citations.ts` e",
    "compaiono sotto ogni concetto nell'area di studio; il controllo settimanale dei link verifica gli",
    "indirizzi qui sotto.",
    "",
    ...cited.map(
      ([ref, citations]) =>
        `- \`${ref}\`: ` +
        citations!.map((c) => `[${SOURCES[c.source].title}](${SOURCES[c.source].url})${c.locator ? `, ${c.locator.it}` : ""}`).join("; ")
    ),
    ""
  );
  return lines.join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(GAP_ANALYSIS_PATH, renderGapAnalysis());
  console.log(`Written ${GAP_ANALYSIS_PATH}`);
}
