/**
 * Versioned inventory of the official CompTIA Security+ SY0-701 exam objectives
 * (document version 7.0, © 2023 CompTIA), issue #103 — Phase A.
 *
 * This is the COMPLETE enumeration of the bulleted sub-topics under objectives
 * 1.1–5.6, not the hand-curated 249-term shortlist used by
 * `scripts/objective-coverage.ts`. It serves as the full denominator for a
 * breadth check: which official sub-topics the app actually teaches.
 *
 * Only the leaf concepts are listed (the most specific testable items); pure
 * structural headers ("Categories", "Control types", "Tools", "Level", …) are
 * dropped because they name a grouping, not a concept. Labels paraphrase the
 * official short terms (the objectives document says its bulleted examples are
 * "not exhaustive lists"); the acronym and its expansion are both carried in
 * `match` so a term is found however the content writes it.
 *
 * `scripts/inventory-coverage.ts` measures coverage against the app's teaching
 * text and quizzes and writes docs/inventory-coverage.md; the uncovered list is
 * a shrink-only baseline (tests/inventoryCoverage.test.ts), to be closed one
 * domain at a time in later reviews (Phase B), with IT/EN parity.
 */

export const SY0701_SYLLABUS_VERSION = "SY0-701 (document v7.0, 2023)";
export const SY0701_SYLLABUS_SOURCE =
  "CompTIA Security+ SY0-701 Certification Exam Objectives, document version 7.0 (© 2023 CompTIA).";

export interface InventoryItem {
  /** Objective code, e.g. "1.1". */
  code: string;
  /** The parent group shown in the objectives document, for context. */
  group: string;
  /** The leaf concept (paraphrased official term). */
  item: string;
  /** Extra phrases that also denote the concept (acronym ↔ expansion, synonyms). */
  match?: string[];
}

const I = (code: string, group: string, item: string, match?: string[]): InventoryItem =>
  match ? { code, group, item, match } : { code, group, item };

export const SY0701_INVENTORY: InventoryItem[] = [
  // ---- 1.1 Security controls ----
  I("1.1", "Control categories", "Technical"),
  I("1.1", "Control categories", "Managerial"),
  I("1.1", "Control categories", "Operational"),
  I("1.1", "Control categories", "Physical"),
  I("1.1", "Control types", "Preventive"),
  I("1.1", "Control types", "Deterrent"),
  I("1.1", "Control types", "Detective"),
  I("1.1", "Control types", "Corrective"),
  I("1.1", "Control types", "Compensating"),
  I("1.1", "Control types", "Directive"),

  // ---- 1.2 Fundamental security concepts ----
  I("1.2", "Fundamentals", "Confidentiality, Integrity, Availability", ["CIA", "confidentiality", "riservatezza"]),
  I("1.2", "Fundamentals", "Non-repudiation", ["non-repudiation", "non ripudio", "non-ripudio"]),
  I("1.2", "AAA", "Authenticating people", ["authenticating people", "autenticazione delle persone", "AAA"]),
  I("1.2", "AAA", "Authenticating systems", ["authenticating systems", "autenticazione dei sistemi"]),
  I("1.2", "AAA", "Authorization models", ["authorization model", "modelli di autorizzazione"]),
  I("1.2", "Fundamentals", "Gap analysis", ["gap analysis", "analisi dei gap"]),
  I("1.2", "Zero Trust / Control Plane", "Adaptive identity", ["adaptive identity", "identità adattiva"]),
  I("1.2", "Zero Trust / Control Plane", "Threat scope reduction", ["threat scope reduction", "riduzione dell'ambito"]),
  I("1.2", "Zero Trust / Control Plane", "Policy-driven access control", ["policy-driven access control", "accesso guidato da policy"]),
  I("1.2", "Zero Trust / Control Plane", "Policy Administrator", ["policy administrator", "PA"]),
  I("1.2", "Zero Trust / Control Plane", "Policy Engine", ["policy engine", "PE"]),
  I("1.2", "Zero Trust / Data Plane", "Implicit trust zones", ["implicit trust", "zone di fiducia implicita"]),
  I("1.2", "Zero Trust / Data Plane", "Subject/System", ["subject/system", "soggetto/sistema"]),
  I("1.2", "Zero Trust / Data Plane", "Policy Enforcement Point", ["policy enforcement point", "PEP"]),
  I("1.2", "Physical security", "Bollards", ["bollard", "dissuasori"]),
  I("1.2", "Physical security", "Access control vestibule", ["vestibule", "vestibolo"]),
  I("1.2", "Physical security", "Fencing", ["fencing", "recinzion"]),
  I("1.2", "Physical security", "Video surveillance", ["video surveillance", "videosorveglianza", "CCTV"]),
  I("1.2", "Physical security", "Security guard", ["security guard", "guardia"]),
  I("1.2", "Physical security", "Access badge", ["access badge", "badge"]),
  I("1.2", "Physical security", "Lighting", ["lighting", "illuminazione"]),
  I("1.2", "Physical security / Sensors", "Infrared sensor", ["infrared", "infrarossi", "infrarosso"]),
  I("1.2", "Physical security / Sensors", "Pressure sensor", ["pressure sensor", "sensore di pressione"]),
  I("1.2", "Physical security / Sensors", "Microwave sensor", ["microwave", "microonde"]),
  I("1.2", "Physical security / Sensors", "Ultrasonic sensor", ["ultrasonic", "ultrasuoni", "ultrasonico"]),
  I("1.2", "Deception technology", "Honeypot", ["honeypot"]),
  I("1.2", "Deception technology", "Honeynet", ["honeynet"]),
  I("1.2", "Deception technology", "Honeyfile", ["honeyfile"]),
  I("1.2", "Deception technology", "Honeytoken", ["honeytoken"]),

  // ---- 1.3 Change management ----
  I("1.3", "Business processes", "Approval process", ["approval process", "processo di approvazione"]),
  I("1.3", "Business processes", "Ownership", ["ownership", "titolarità", "proprietà"]),
  I("1.3", "Business processes", "Stakeholders", ["stakeholder", "parti interessate"]),
  I("1.3", "Business processes", "Impact analysis", ["impact analysis", "analisi d'impatto", "analisi di impatto"]),
  I("1.3", "Business processes", "Test results", ["test results", "risultati dei test"]),
  I("1.3", "Business processes", "Backout plan", ["backout", "piano di rollback", "piano di ritorno"]),
  I("1.3", "Business processes", "Maintenance window", ["maintenance window", "finestra di manutenzione"]),
  I("1.3", "Business processes", "Standard operating procedure", ["standard operating procedure", "procedura operativa standard", "SOP"]),
  I("1.3", "Technical implications", "Allow lists/deny lists", ["allow list", "deny list", "lista di permessi", "lista di blocco"]),
  I("1.3", "Technical implications", "Restricted activities", ["restricted activities", "attività limitate"]),
  I("1.3", "Technical implications", "Downtime", ["downtime", "tempo di inattività"]),
  I("1.3", "Technical implications", "Service restart", ["service restart", "riavvio del servizio"]),
  I("1.3", "Technical implications", "Application restart", ["application restart", "riavvio dell'applicazione"]),
  I("1.3", "Technical implications", "Legacy applications", ["legacy application", "applicazioni legacy"]),
  I("1.3", "Technical implications", "Dependencies", ["dependencies", "dipendenze"]),
  I("1.3", "Documentation", "Updating diagrams", ["updating diagrams", "aggiornare i diagrammi", "aggiornamento dei diagrammi"]),
  I("1.3", "Documentation", "Updating policies/procedures", ["updating policies", "aggiornamento di policy e procedure"]),
  I("1.3", "Change management", "Version control", ["version control", "controllo di versione", "versionamento"]),

  // ---- 1.4 Cryptographic solutions ----
  I("1.4", "PKI", "Public key", ["public key", "chiave pubblica"]),
  I("1.4", "PKI", "Private key", ["private key", "chiave privata"]),
  I("1.4", "PKI", "Key escrow", ["key escrow", "deposito delle chiavi"]),
  I("1.4", "Encryption level", "Full-disk encryption", ["full-disk", "full disk", "intero disco", "FDE"]),
  I("1.4", "Encryption level", "Partition encryption", ["partition", "partizione"]),
  I("1.4", "Encryption level", "File encryption", ["file encryption", "cifratura dei file", "cifratura del file"]),
  I("1.4", "Encryption level", "Volume encryption", ["volume encryption", "cifratura del volume"]),
  I("1.4", "Encryption level", "Database encryption", ["database encryption", "cifratura del database"]),
  I("1.4", "Encryption level", "Record-level encryption", ["record-level", "a livello di record", "per record"]),
  I("1.4", "Encryption", "Transport/communication encryption", ["transport", "trasporto", "in transito"]),
  I("1.4", "Encryption", "Asymmetric encryption", ["asymmetric", "asimmetric"]),
  I("1.4", "Encryption", "Symmetric encryption", ["symmetric", "simmetric"]),
  I("1.4", "Encryption", "Key exchange", ["key exchange", "scambio di chiavi", "scambio delle chiavi"]),
  I("1.4", "Encryption", "Algorithms", ["algorithm", "algoritm"]),
  I("1.4", "Encryption", "Key length", ["key length", "256 bit", "lunghezza della chiave"]),
  I("1.4", "Tools", "Trusted Platform Module", ["TPM", "trusted platform module"]),
  I("1.4", "Tools", "Hardware security module", ["HSM", "hardware security module"]),
  I("1.4", "Tools", "Key management system", ["key management system", "KMS", "sistema di gestione delle chiavi"]),
  I("1.4", "Tools", "Secure enclave", ["secure enclave", "enclave sicura"]),
  I("1.4", "Obfuscation", "Steganography", ["steganograph", "steganografia"]),
  I("1.4", "Obfuscation", "Tokenization", ["tokenization", "tokenizzazione"]),
  I("1.4", "Obfuscation", "Data masking", ["data masking", "mascheramento"]),
  I("1.4", "Cryptography", "Hashing", ["hashing", "hash"]),
  I("1.4", "Cryptography", "Salting", ["salting", "salt"]),
  I("1.4", "Cryptography", "Digital signatures", ["digital signature", "firma digitale", "firme digitali"]),
  I("1.4", "Cryptography", "Key stretching", ["key stretching", "key-stretching"]),
  I("1.4", "Cryptography", "Blockchain", ["blockchain"]),
  I("1.4", "Cryptography", "Open public ledger", ["public ledger", "registro pubblico", "libro mastro"]),
  I("1.4", "Certificates", "Certificate authorities", ["certificate authorit", "CA", "autorità di certificazione"]),
  I("1.4", "Certificates", "Certificate revocation lists", ["certificate revocation list", "CRL", "lista di revoca"]),
  I("1.4", "Certificates", "Online Certificate Status Protocol", ["OCSP", "online certificate status protocol"]),
  I("1.4", "Certificates", "Self-signed", ["self-signed", "autofirmato"]),
  I("1.4", "Certificates", "Third-party certificate", ["third-party", "terza parte"]),
  I("1.4", "Certificates", "Root of trust", ["root of trust", "radice di fiducia"]),
  I("1.4", "Certificates", "Certificate signing request generation", ["certificate signing request", "CSR"]),
  I("1.4", "Certificates", "Wildcard", ["wildcard"]),

  // ---- 2.1 Threat actors and motivations ----
  I("2.1", "Threat actors", "Nation-state", ["nation-state", "stato-nazione", "statale"]),
  I("2.1", "Threat actors", "Unskilled attacker", ["unskilled", "script kiddie", "inesperto"]),
  I("2.1", "Threat actors", "Hacktivist", ["hacktivist"]),
  I("2.1", "Threat actors", "Insider threat", ["insider threat", "minaccia interna"]),
  I("2.1", "Threat actors", "Organized crime", ["organized crime", "crimine organizzato"]),
  I("2.1", "Threat actors", "Shadow IT", ["shadow it"]),
  I("2.1", "Attributes", "Internal/external", ["internal/external", "interno/esterno", "interni ed esterni"]),
  I("2.1", "Attributes", "Resources/funding", ["resources/funding", "risorse", "finanziament"]),
  I("2.1", "Attributes", "Level of sophistication/capability", ["sophistication", "sofisticazione", "capability"]),
  I("2.1", "Motivations", "Data exfiltration", ["data exfiltration", "esfiltrazione"]),
  I("2.1", "Motivations", "Espionage", ["espionage", "spionaggio"]),
  I("2.1", "Motivations", "Service disruption", ["service disruption", "interruzione del servizio"]),
  I("2.1", "Motivations", "Blackmail", ["blackmail", "ricatto"]),
  I("2.1", "Motivations", "Financial gain", ["financial gain", "guadagno economico", "profitto"]),
  I("2.1", "Motivations", "Philosophical/political beliefs", ["philosophical", "political beliefs", "convinzioni politiche", "ideologic"]),
  I("2.1", "Motivations", "Ethical", ["ethical", "etic"]),
  I("2.1", "Motivations", "Revenge", ["revenge", "vendetta"]),
  I("2.1", "Motivations", "Disruption/chaos", ["disruption/chaos", "caos"]),
  I("2.1", "Motivations", "War", ["war", "guerra"]),

  // ---- 2.2 Threat vectors and attack surfaces ----
  I("2.2", "Message-based", "Email", ["email", "e-mail", "posta elettronica"]),
  I("2.2", "Message-based", "Short Message Service", ["SMS", "short message service"]),
  I("2.2", "Message-based", "Instant messaging", ["instant messaging", "IM", "messaggistica istantanea"]),
  I("2.2", "Vectors", "Image-based", ["image-based", "basato su immagine"]),
  I("2.2", "Vectors", "File-based", ["file-based", "basato su file"]),
  I("2.2", "Vectors", "Voice call", ["voice call", "chiamata vocale"]),
  I("2.2", "Vectors", "Removable device", ["removable device", "removable media", "rimovibil"]),
  I("2.2", "Vectors", "Client-based vs. agentless", ["client-based", "agentless", "agentless"]),
  I("2.2", "Vectors", "Unsupported systems and applications", ["unsupported system", "non supportat"]),
  I("2.2", "Unsecure networks", "Wireless", ["wireless"]),
  I("2.2", "Unsecure networks", "Wired", ["wired", "cablat"]),
  I("2.2", "Unsecure networks", "Bluetooth", ["bluetooth"]),
  I("2.2", "Vectors", "Open service ports", ["open service port", "porte di servizio", "porte aperte"]),
  I("2.2", "Vectors", "Default credentials", ["default credential", "credenziali predefinite"]),
  I("2.2", "Supply chain", "Managed service providers", ["managed service provider", "MSP"]),
  I("2.2", "Supply chain", "Vendors", ["vendor", "fornitori"]),
  I("2.2", "Supply chain", "Suppliers", ["supplier", "fornitori"]),
  I("2.2", "Social engineering", "Phishing", ["phishing"]),
  I("2.2", "Social engineering", "Vishing", ["vishing"]),
  I("2.2", "Social engineering", "Smishing", ["smishing"]),
  I("2.2", "Social engineering", "Misinformation/disinformation", ["misinformation", "disinformation", "disinformazione"]),
  I("2.2", "Social engineering", "Impersonation", ["impersonation", "impersonificazione"]),
  I("2.2", "Social engineering", "Business email compromise", ["business email compromise", "BEC"]),
  I("2.2", "Social engineering", "Pretexting", ["pretexting"]),
  I("2.2", "Social engineering", "Watering hole", ["watering hole"]),
  I("2.2", "Social engineering", "Brand impersonation", ["brand impersonation", "impersonazione del marchio"]),
  I("2.2", "Social engineering", "Typosquatting", ["typosquatting"]),

  // ---- 2.3 Types of vulnerabilities ----
  I("2.3", "Application", "Memory injection", ["memory injection", "iniezione in memoria"]),
  I("2.3", "Application", "Buffer overflow", ["buffer overflow"]),
  I("2.3", "Application / Race conditions", "Time-of-check", ["time-of-check", "TOC"]),
  I("2.3", "Application / Race conditions", "Time-of-use", ["time-of-use", "TOU"]),
  I("2.3", "Application", "Malicious update", ["malicious update", "aggiornamento malevolo"]),
  I("2.3", "Vulnerabilities", "Operating system (OS)-based", ["operating system", "sistema operativo", "OS-based"]),
  I("2.3", "Web-based", "Structured Query Language injection", ["SQL injection", "SQLi"]),
  I("2.3", "Web-based", "Cross-site scripting", ["cross-site scripting", "XSS"]),
  I("2.3", "Hardware", "Firmware", ["firmware"]),
  I("2.3", "Hardware", "End-of-life", ["end-of-life", "EOL", "fine vita"]),
  I("2.3", "Hardware", "Legacy", ["legacy"]),
  I("2.3", "Virtualization", "Virtual machine escape", ["VM escape", "virtual machine escape"]),
  I("2.3", "Virtualization", "Resource reuse", ["resource reuse", "riuso delle risorse"]),
  I("2.3", "Vulnerabilities", "Cloud-specific", ["cloud-specific", "specifiche del cloud", "del cloud"]),
  I("2.3", "Supply chain", "Service provider", ["service provider", "fornitore di servizi"]),
  I("2.3", "Supply chain", "Hardware provider", ["hardware provider", "fornitore di hardware"]),
  I("2.3", "Supply chain", "Software provider", ["software provider", "fornitore di software"]),
  I("2.3", "Vulnerabilities", "Cryptographic", ["cryptographic", "crittografica", "crittografiche"]),
  I("2.3", "Vulnerabilities", "Misconfiguration", ["misconfiguration", "configurazione errata", "errata configurazione"]),
  I("2.3", "Mobile device", "Side loading", ["side loading", "sideloading"]),
  I("2.3", "Mobile device", "Jailbreaking", ["jailbreaking", "jailbreak"]),
  I("2.3", "Vulnerabilities", "Zero-day", ["zero-day"]),

  // ---- 2.4 Indicators of malicious activity ----
  I("2.4", "Malware", "Ransomware", ["ransomware"]),
  I("2.4", "Malware", "Trojan", ["trojan"]),
  I("2.4", "Malware", "Worm", ["worm"]),
  I("2.4", "Malware", "Spyware", ["spyware"]),
  I("2.4", "Malware", "Bloatware", ["bloatware"]),
  I("2.4", "Malware", "Virus", ["virus"]),
  I("2.4", "Malware", "Keylogger", ["keylogger"]),
  I("2.4", "Malware", "Logic bomb", ["logic bomb", "bomba logica"]),
  I("2.4", "Malware", "Rootkit", ["rootkit"]),
  I("2.4", "Physical attacks", "Brute force (physical)", ["brute force", "forza bruta"]),
  I("2.4", "Physical attacks", "RFID cloning", ["RFID cloning", "clonazione RFID", "RFID"]),
  I("2.4", "Physical attacks", "Environmental", ["environmental", "ambientale"]),
  I("2.4", "Network attacks / DDoS", "Amplified DDoS", ["amplified", "amplificato"]),
  I("2.4", "Network attacks / DDoS", "Reflected DDoS", ["reflected", "riflesso"]),
  I("2.4", "Network attacks", "Domain Name System attacks", ["DNS attack", "attacchi DNS", "DNS"]),
  I("2.4", "Network attacks", "Wireless attacks", ["wireless attack", "attacchi wireless"]),
  I("2.4", "Network attacks", "On-path", ["on-path", "man-in-the-middle"]),
  I("2.4", "Network attacks", "Credential replay", ["credential replay", "replay delle credenziali"]),
  I("2.4", "Network attacks", "Malicious code", ["malicious code", "codice malevolo"]),
  I("2.4", "Application attacks", "Injection", ["injection", "iniezione"]),
  I("2.4", "Application attacks", "Buffer overflow (attack)", ["buffer overflow"]),
  I("2.4", "Application attacks", "Replay", ["replay"]),
  I("2.4", "Application attacks", "Privilege escalation", ["privilege escalation", "escalation dei privilegi"]),
  I("2.4", "Application attacks", "Forgery", ["forgery", "contraffazione"]),
  I("2.4", "Application attacks", "Directory traversal", ["directory traversal"]),
  I("2.4", "Cryptographic attacks", "Downgrade", ["downgrade"]),
  I("2.4", "Cryptographic attacks", "Collision", ["collision", "collisione"]),
  I("2.4", "Cryptographic attacks", "Birthday", ["birthday", "compleanno"]),
  I("2.4", "Password attacks", "Spraying", ["spraying", "password spraying"]),
  I("2.4", "Password attacks", "Brute force (password)", ["brute force", "forza bruta"]),
  I("2.4", "Indicators", "Account lockout", ["account lockout", "blocco dell'account"]),
  I("2.4", "Indicators", "Concurrent session usage", ["concurrent session", "sessioni concorrenti"]),
  I("2.4", "Indicators", "Blocked content", ["blocked content", "contenuto bloccato"]),
  I("2.4", "Indicators", "Impossible travel", ["impossible travel", "viaggio impossibile"]),
  I("2.4", "Indicators", "Resource consumption", ["resource consumption", "consumo di risorse"]),
  I("2.4", "Indicators", "Resource inaccessibility", ["resource inaccessibility", "risorsa inaccessibile", "inaccessibilità"]),
  I("2.4", "Indicators", "Out-of-cycle logging", ["out-of-cycle logging", "log fuori ciclo"]),
  I("2.4", "Indicators", "Published/documented", ["published/documented", "pubblicato/documentato"]),
  I("2.4", "Indicators", "Missing logs", ["missing log", "log mancanti"]),

  // ---- 2.5 Mitigation techniques ----
  I("2.5", "Mitigation", "Segmentation", ["segmentation", "segmentazione"]),
  I("2.5", "Access control", "Access control list", ["access control list", "ACL"]),
  I("2.5", "Access control", "Permissions", ["permissions", "permessi"]),
  I("2.5", "Mitigation", "Application allow list", ["application allow list", "lista di applicazioni consentite"]),
  I("2.5", "Mitigation", "Isolation", ["isolation", "isolamento"]),
  I("2.5", "Mitigation", "Patching", ["patching", "patch"]),
  I("2.5", "Mitigation", "Encryption", ["encryption", "cifratura"]),
  I("2.5", "Mitigation", "Monitoring", ["monitoring", "monitoraggio"]),
  I("2.5", "Mitigation", "Least privilege", ["least privilege", "privilegio minimo", "minimo privilegio"]),
  I("2.5", "Mitigation", "Configuration enforcement", ["configuration enforcement", "applicazione della configurazione"]),
  I("2.5", "Mitigation", "Decommissioning", ["decommissioning", "dismissione"]),
  I("2.5", "Hardening", "Installation of endpoint protection", ["endpoint protection", "protezione degli endpoint"]),
  I("2.5", "Hardening", "Host-based firewall", ["host-based firewall", "firewall sull'host", "firewall basato su host"]),
  I("2.5", "Hardening", "Host-based intrusion prevention system", ["HIPS", "host-based intrusion prevention"]),
  I("2.5", "Hardening", "Disabling ports/protocols", ["disabling ports", "disabilitare le porte", "disattivare porte"]),
  I("2.5", "Hardening", "Default password changes", ["default password", "password predefinite"]),
  I("2.5", "Hardening", "Removal of unnecessary software", ["unnecessary software", "software non necessario"]),

  // ---- 3.1 Architecture models ----
  I("3.1", "Cloud", "Responsibility matrix", ["responsibility matrix", "matrice di responsabilità"]),
  I("3.1", "Cloud", "Hybrid considerations", ["hybrid", "ibrido", "ibrida"]),
  I("3.1", "Cloud", "Third-party vendors", ["third-party vendor", "fornitori terzi"]),
  I("3.1", "Architecture", "Infrastructure as code", ["infrastructure as code", "IaC"]),
  I("3.1", "Architecture", "Serverless", ["serverless"]),
  I("3.1", "Architecture", "Microservices", ["microservices", "microservizi"]),
  I("3.1", "Network infrastructure", "Air-gapped", ["air-gapped", "air gap"]),
  I("3.1", "Network infrastructure", "Logical segmentation", ["logical segmentation", "segmentazione logica"]),
  I("3.1", "Network infrastructure", "Software-defined networking", ["software-defined networking", "SDN"]),
  I("3.1", "Architecture", "On-premises", ["on-premises", "on-premise", "on premise"]),
  I("3.1", "Architecture", "Centralized vs. decentralized", ["centralized", "decentralized", "centralizzat", "decentralizzat"]),
  I("3.1", "Architecture", "Containerization", ["containerization", "containerizzazione", "container"]),
  I("3.1", "Architecture", "Virtualization", ["virtualization", "virtualizzazione"]),
  I("3.1", "Architecture", "Internet of Things", ["internet of things", "IoT"]),
  I("3.1", "Architecture", "Industrial control systems / SCADA", ["ICS", "SCADA", "industrial control"]),
  I("3.1", "Architecture", "Real-time operating system", ["real-time operating system", "RTOS"]),
  I("3.1", "Architecture", "Embedded systems", ["embedded system", "sistemi embedded"]),
  I("3.1", "Architecture", "High availability", ["high availability", "alta disponibilità"]),
  I("3.1", "Considerations", "Availability", ["availability", "disponibilità"]),
  I("3.1", "Considerations", "Resilience", ["resilience", "resilienza"]),
  I("3.1", "Considerations", "Cost", ["cost", "costo"]),
  I("3.1", "Considerations", "Responsiveness", ["responsiveness", "reattività"]),
  I("3.1", "Considerations", "Scalability", ["scalability", "scalabilità"]),
  I("3.1", "Considerations", "Ease of deployment", ["ease of deployment", "facilità di distribuzione"]),
  I("3.1", "Considerations", "Risk transference", ["risk transference", "risk transfer", "trasferimento del rischio"]),
  I("3.1", "Considerations", "Ease of recovery", ["ease of recovery", "facilità di ripristino"]),
  I("3.1", "Considerations", "Patch availability", ["patch availability", "disponibilità delle patch"]),
  I("3.1", "Considerations", "Inability to patch", ["inability to patch", "impossibilità di applicare patch"]),
  I("3.1", "Considerations", "Power", ["power", "alimentazione"]),
  I("3.1", "Considerations", "Compute", ["compute", "capacità di calcolo"]),

  // ---- 3.2 Secure enterprise infrastructure ----
  I("3.2", "Infrastructure considerations", "Device placement", ["device placement", "posizionamento dei dispositivi"]),
  I("3.2", "Infrastructure considerations", "Security zones", ["security zones", "zone di sicurezza"]),
  I("3.2", "Infrastructure considerations", "Attack surface", ["attack surface", "superficie d'attacco"]),
  I("3.2", "Infrastructure considerations", "Connectivity", ["connectivity", "connettività"]),
  I("3.2", "Failure modes", "Fail-open", ["fail-open", "fail open"]),
  I("3.2", "Failure modes", "Fail-closed", ["fail-closed", "fail closed"]),
  I("3.2", "Device attribute", "Active vs. passive", ["active vs. passive", "attivo", "passivo"]),
  I("3.2", "Device attribute", "Inline vs. tap/monitor", ["inline", "tap/monitor", "mirroring", "monitoraggio passivo"]),
  I("3.2", "Network appliances", "Jump server", ["jump server"]),
  I("3.2", "Network appliances", "Proxy server", ["proxy server", "proxy"]),
  I("3.2", "Network appliances", "Intrusion prevention/detection system", ["IPS", "IDS", "intrusion prevention", "intrusion detection"]),
  I("3.2", "Network appliances", "Load balancer", ["load balancer", "bilanciatore"]),
  I("3.2", "Network appliances", "Sensors", ["sensors", "sensori"]),
  I("3.2", "Port security", "802.1X", ["802.1X"]),
  I("3.2", "Port security", "Extensible Authentication Protocol", ["extensible authentication protocol", "EAP"]),
  I("3.2", "Firewall types", "Web application firewall", ["web application firewall", "WAF"]),
  I("3.2", "Firewall types", "Unified threat management", ["unified threat management", "UTM"]),
  I("3.2", "Firewall types", "Next-generation firewall", ["next-generation firewall", "NGFW"]),
  I("3.2", "Firewall types", "Layer 4/Layer 7", ["layer 4", "layer 7", "livello 4", "livello 7"]),
  I("3.2", "Secure communication/access", "Virtual private network", ["virtual private network", "VPN"]),
  I("3.2", "Secure communication/access", "Remote access", ["remote access", "accesso remoto"]),
  I("3.2", "Tunneling", "Transport Layer Security", ["transport layer security", "TLS"]),
  I("3.2", "Tunneling", "Internet protocol security", ["IPSec", "internet protocol security"]),
  I("3.2", "Secure communication/access", "Software-defined wide area network", ["software-defined wide area network", "SD-WAN"]),
  I("3.2", "Secure communication/access", "Secure access service edge", ["secure access service edge", "SASE"]),
  I("3.2", "Infrastructure", "Selection of effective controls", ["selection of effective controls", "selezione dei controlli"]),

  // ---- 3.3 Protect data ----
  I("3.3", "Data types", "Regulated", ["regulated", "regolamentat"]),
  I("3.3", "Data types", "Trade secret", ["trade secret", "segreto commerciale"]),
  I("3.3", "Data types", "Intellectual property", ["intellectual property", "proprietà intellettuale"]),
  I("3.3", "Data types", "Legal information", ["legal information", "informazioni legali"]),
  I("3.3", "Data types", "Financial information", ["financial information", "informazioni finanziarie"]),
  I("3.3", "Data types", "Human- and non-human-readable", ["human-readable", "non-human-readable", "leggibile dall'uomo"]),
  I("3.3", "Data classifications", "Sensitive", ["sensitive", "sensibil"]),
  I("3.3", "Data classifications", "Confidential", ["confidential", "confidenzial"]),
  I("3.3", "Data classifications", "Public", ["public", "pubblic"]),
  I("3.3", "Data classifications", "Restricted", ["restricted", "ristrett"]),
  I("3.3", "Data classifications", "Private", ["private", "privat"]),
  I("3.3", "Data classifications", "Critical", ["critical", "critic"]),
  I("3.3", "Data states", "Data at rest", ["at rest", "a riposo"]),
  I("3.3", "Data states", "Data in transit", ["in transit", "in transito"]),
  I("3.3", "Data states", "Data in use", ["in use", "in uso"]),
  I("3.3", "General data considerations", "Data sovereignty", ["data sovereignty", "sovranità dei dati"]),
  I("3.3", "General data considerations", "Geolocation", ["geolocation", "geolocalizzazione"]),
  I("3.3", "Methods to secure data", "Geographic restrictions", ["geographic restriction", "restrizioni geografiche"]),
  I("3.3", "Methods to secure data", "Encryption (data)", ["encryption", "cifratura"]),
  I("3.3", "Methods to secure data", "Hashing (data)", ["hashing", "hash"]),
  I("3.3", "Methods to secure data", "Masking", ["masking", "mascheramento"]),
  I("3.3", "Methods to secure data", "Tokenization (data)", ["tokenization", "tokenizzazione"]),
  I("3.3", "Methods to secure data", "Obfuscation (data)", ["obfuscation", "offuscamento"]),
  I("3.3", "Methods to secure data", "Segmentation (data)", ["segmentation", "segmentazione"]),
  I("3.3", "Methods to secure data", "Permission restrictions", ["permission restriction", "restrizioni dei permessi"]),

  // ---- 3.4 Resilience and recovery ----
  I("3.4", "High availability", "Load balancing vs. clustering", ["load balancing", "clustering", "bilanciamento del carico"]),
  I("3.4", "Site considerations", "Hot site", ["hot site", "sito caldo"]),
  I("3.4", "Site considerations", "Cold site", ["cold site", "sito freddo"]),
  I("3.4", "Site considerations", "Warm site", ["warm site", "sito tiepido"]),
  I("3.4", "Site considerations", "Geographic dispersion", ["geographic dispersion", "dispersione geografica"]),
  I("3.4", "Resilience", "Platform diversity", ["platform diversity", "diversità delle piattaforme"]),
  I("3.4", "Resilience", "Multi-cloud systems", ["multi-cloud", "multicloud"]),
  I("3.4", "Resilience", "Continuity of operations", ["continuity of operations", "continuità operativa", "COOP"]),
  I("3.4", "Capacity planning", "People", ["people", "personale"]),
  I("3.4", "Capacity planning", "Technology", ["technology", "tecnologia"]),
  I("3.4", "Capacity planning", "Infrastructure", ["infrastructure", "infrastruttura"]),
  I("3.4", "Testing", "Tabletop exercises", ["tabletop", "simulazione a tavolino"]),
  I("3.4", "Testing", "Fail over", ["fail over", "failover"]),
  I("3.4", "Testing", "Simulation", ["simulation", "simulazione"]),
  I("3.4", "Testing", "Parallel processing", ["parallel processing", "elaborazione parallela"]),
  I("3.4", "Backups", "Onsite/offsite", ["onsite", "offsite", "fuori sede"]),
  I("3.4", "Backups", "Frequency", ["frequency", "frequenza"]),
  I("3.4", "Backups", "Encryption (backup)", ["encryption", "cifratura"]),
  I("3.4", "Backups", "Snapshots", ["snapshot"]),
  I("3.4", "Backups", "Recovery", ["recovery", "ripristino"]),
  I("3.4", "Backups", "Replication", ["replication", "replica"]),
  I("3.4", "Backups", "Journaling", ["journaling"]),
  I("3.4", "Power", "Generators", ["generator", "generatori"]),
  I("3.4", "Power", "Uninterruptible power supply", ["uninterruptible power supply", "UPS", "gruppo di continuità"]),

  // ---- 4.1 Secure computing resources ----
  I("4.1", "Secure baselines", "Establish", ["establish", "stabilire"]),
  I("4.1", "Secure baselines", "Deploy", ["deploy", "distribuire"]),
  I("4.1", "Secure baselines", "Maintain", ["maintain", "mantenere"]),
  I("4.1", "Hardening targets", "Mobile devices", ["mobile device", "dispositivi mobili"]),
  I("4.1", "Hardening targets", "Workstations", ["workstation", "postazioni di lavoro"]),
  I("4.1", "Hardening targets", "Switches", ["switch"]),
  I("4.1", "Hardening targets", "Routers", ["router"]),
  I("4.1", "Hardening targets", "Cloud infrastructure", ["cloud infrastructure", "infrastruttura cloud"]),
  I("4.1", "Hardening targets", "Servers", ["server"]),
  I("4.1", "Hardening targets", "ICS/SCADA", ["ICS", "SCADA"]),
  I("4.1", "Hardening targets", "Embedded systems", ["embedded system", "sistemi embedded"]),
  I("4.1", "Hardening targets", "RTOS", ["RTOS", "real-time operating system"]),
  I("4.1", "Hardening targets", "IoT devices", ["IoT", "internet of things"]),
  I("4.1", "Wireless devices", "Site surveys", ["site survey", "rilevamento del sito", "sopralluogo"]),
  I("4.1", "Wireless devices", "Heat maps", ["heat map", "mappa di calore"]),
  I("4.1", "Mobile solutions", "Mobile device management", ["mobile device management", "MDM"]),
  I("4.1", "Mobile solutions", "Bring your own device", ["bring your own device", "BYOD"]),
  I("4.1", "Mobile solutions", "Corporate-owned, personally enabled", ["COPE", "corporate-owned"]),
  I("4.1", "Mobile solutions", "Choose your own device", ["choose your own device", "CYOD"]),
  I("4.1", "Mobile solutions", "Cellular", ["cellular", "cellulare"]),
  I("4.1", "Mobile solutions", "Wi-Fi", ["wi-fi", "wifi"]),
  I("4.1", "Mobile solutions", "Bluetooth", ["bluetooth"]),
  I("4.1", "Wireless security", "Wi-Fi Protected Access 3", ["WPA3", "wi-fi protected access"]),
  I("4.1", "Wireless security", "AAA/RADIUS", ["RADIUS", "remote authentication dial-in"]),
  I("4.1", "Wireless security", "Cryptographic protocols", ["cryptographic protocol", "protocolli crittografici"]),
  I("4.1", "Wireless security", "Authentication protocols", ["authentication protocol", "protocolli di autenticazione"]),
  I("4.1", "Application security", "Input validation", ["input validation", "validazione dell'input"]),
  I("4.1", "Application security", "Secure cookies", ["secure cookie", "cookie sicuri"]),
  I("4.1", "Application security", "Static code analysis", ["static code analysis", "analisi statica"]),
  I("4.1", "Application security", "Code signing", ["code signing", "firma del codice"]),
  I("4.1", "Computing resources", "Sandboxing", ["sandboxing", "sandbox"]),
  I("4.1", "Computing resources", "Monitoring", ["monitoring", "monitoraggio"]),

  // ---- 4.2 Asset management ----
  I("4.2", "Asset management", "Acquisition/procurement process", ["procurement", "acquisition phase", "acquisizione", "approvvigionamento"]),
  I("4.2", "Assignment/accounting", "Ownership", ["ownership", "assignment of devices", "assegnazione", "titolarità"]),
  I("4.2", "Assignment/accounting", "Classification", ["classification", "classificazione"]),
  I("4.2", "Monitoring/asset tracking", "Inventory", ["inventory", "inventario"]),
  I("4.2", "Monitoring/asset tracking", "Enumeration", ["enumeration", "enumerazione"]),
  I("4.2", "Disposal/decommissioning", "Sanitization", ["sanitization", "sanificazione", "sanitizzazione"]),
  I("4.2", "Disposal/decommissioning", "Destruction", ["destruction", "distruzione"]),
  I("4.2", "Disposal/decommissioning", "Certification", ["certification", "certificazione"]),
  I("4.2", "Disposal/decommissioning", "Data retention", ["data retention", "conservazione dei dati", "retention"]),

  // ---- 4.3 Vulnerability management ----
  I("4.3", "Identification", "Vulnerability scan", ["vulnerability scan", "scansione delle vulnerabilità"]),
  I("4.3", "Identification / App security", "Static analysis", ["static analysis", "analisi statica", "SAST"]),
  I("4.3", "Identification / App security", "Dynamic analysis", ["dynamic analysis", "analisi dinamica", "DAST"]),
  I("4.3", "Identification / App security", "Package monitoring", ["package monitoring", "monitoraggio dei pacchetti"]),
  I("4.3", "Threat feed", "Open-source intelligence", ["open-source intelligence", "OSINT"]),
  I("4.3", "Threat feed", "Proprietary/third-party", ["proprietary", "third-party", "proprietaria"]),
  I("4.3", "Threat feed", "Information-sharing organization", ["information-sharing", "condivisione delle informazioni"]),
  I("4.3", "Threat feed", "Dark web", ["dark web"]),
  I("4.3", "Identification", "Penetration testing", ["penetration testing", "penetration test", "test di penetrazione"]),
  I("4.3", "Responsible disclosure", "Bug bounty program", ["bug bounty"]),
  I("4.3", "Identification", "System/process audit", ["system/process audit", "audit di sistema"]),
  I("4.3", "Analysis / Confirmation", "False positive", ["false positive", "falso positivo"]),
  I("4.3", "Analysis / Confirmation", "False negative", ["false negative", "falso negativo"]),
  I("4.3", "Analysis", "Prioritize", ["prioritize", "prioritizzare", "priorità"]),
  I("4.3", "Analysis", "Common Vulnerability Scoring System", ["CVSS", "common vulnerability scoring"]),
  I("4.3", "Analysis", "Common Vulnerability Enumeration", ["CVE", "common vulnerability enumeration", "common vulnerabilities and exposures"]),
  I("4.3", "Analysis", "Vulnerability classification", ["vulnerability classification", "classificazione delle vulnerabilità"]),
  I("4.3", "Analysis", "Exposure factor", ["exposure factor", "fattore di esposizione"]),
  I("4.3", "Analysis", "Environmental variables", ["environmental variable", "variabili ambientali"]),
  I("4.3", "Analysis", "Industry/organizational impact", ["organizational impact", "impatto organizzativo", "impatto settoriale"]),
  I("4.3", "Analysis", "Risk tolerance", ["risk tolerance", "tolleranza al rischio"]),
  I("4.3", "Response and remediation", "Patching", ["patching", "patch"]),
  I("4.3", "Response and remediation", "Insurance", ["insurance", "assicurazione"]),
  I("4.3", "Response and remediation", "Segmentation", ["segmentation", "segmentazione"]),
  I("4.3", "Response and remediation", "Compensating controls", ["compensating control", "controlli compensativi"]),
  I("4.3", "Response and remediation", "Exceptions and exemptions", ["exceptions", "exemptions", "eccezioni", "esenzioni"]),
  I("4.3", "Validation of remediation", "Rescanning", ["rescan", "nuova scansione", "riscansione"]),
  I("4.3", "Validation of remediation", "Audit", ["audit"]),
  I("4.3", "Validation of remediation", "Verification", ["verification", "verifica"]),
  I("4.3", "Vulnerability management", "Reporting", ["reporting", "reportistica", "rendicontazione"]),

  // ---- 4.4 Alerting and monitoring ----
  I("4.4", "Monitoring resources", "Systems", ["systems", "sistemi"]),
  I("4.4", "Monitoring resources", "Applications", ["applications", "applicazioni"]),
  I("4.4", "Monitoring resources", "Infrastructure", ["infrastructure", "infrastruttura"]),
  I("4.4", "Activities", "Log aggregation", ["log aggregation", "aggregazione dei log"]),
  I("4.4", "Activities", "Alerting", ["alerting", "allertamento", "avvisi"]),
  I("4.4", "Activities", "Scanning", ["scanning", "scansione"]),
  I("4.4", "Activities", "Reporting", ["reporting", "reportistica"]),
  I("4.4", "Activities", "Archiving", ["archiving", "archiviazione"]),
  I("4.4", "Alert response", "Quarantine", ["quarantine", "quarantena"]),
  I("4.4", "Alert response", "Alert tuning", ["alert tuning", "ottimizzazione degli avvisi", "taratura degli avvisi"]),
  I("4.4", "Tools", "Security Content Automation Protocol", ["SCAP", "security content automation"]),
  I("4.4", "Tools", "Benchmarks", ["benchmark"]),
  I("4.4", "Tools", "Agents/agentless", ["agents", "agentless", "agenti"]),
  I("4.4", "Tools", "Security information and event management", ["SIEM", "security information and event"]),
  I("4.4", "Tools", "Antivirus", ["antivirus"]),
  I("4.4", "Tools", "Data loss prevention", ["data loss prevention", "DLP"]),
  I("4.4", "Tools", "Simple Network Management Protocol traps", ["SNMP trap", "simple network management"]),
  I("4.4", "Tools", "NetFlow", ["netflow"]),
  I("4.4", "Tools", "Vulnerability scanners", ["vulnerability scanner", "scanner di vulnerabilità"]),

  // ---- 4.5 Modify enterprise capabilities ----
  I("4.5", "Firewall", "Rules", ["firewall rule", "regole del firewall", "regole firewall"]),
  I("4.5", "Firewall", "Access lists", ["access list", "ACL", "liste di accesso"]),
  I("4.5", "Firewall", "Ports/protocols", ["ports/protocols", "porte/protocolli", "porte e protocolli"]),
  I("4.5", "Firewall", "Screened subnets", ["screened subnet", "sottorete schermata", "DMZ"]),
  I("4.5", "IDS/IPS", "Trends", ["trends", "tendenze"]),
  I("4.5", "IDS/IPS", "Signatures", ["signatures", "firme"]),
  I("4.5", "Web filter", "Agent-based", ["agent-based", "basato su agente"]),
  I("4.5", "Web filter", "Centralized proxy", ["centralized proxy", "proxy centralizzato"]),
  I("4.5", "Web filter", "URL scanning", ["URL scanning", "scansione degli URL"]),
  I("4.5", "Web filter", "Content categorization", ["content categorization", "categorizzazione dei contenuti"]),
  I("4.5", "Web filter", "Block rules", ["block rules", "regole di blocco"]),
  I("4.5", "Web filter", "Reputation", ["reputation", "reputazione"]),
  I("4.5", "Operating system security", "Group Policy", ["group policy", "GPO"]),
  I("4.5", "Operating system security", "SELinux", ["selinux", "security-enhanced linux"]),
  I("4.5", "Secure protocols", "Protocol selection", ["protocol selection", "selezione del protocollo"]),
  I("4.5", "Secure protocols", "Port selection", ["port selection", "selezione della porta"]),
  I("4.5", "Secure protocols", "Transport method", ["transport method", "metodo di trasporto"]),
  I("4.5", "Capabilities", "DNS filtering", ["DNS filtering", "filtraggio DNS"]),
  I("4.5", "Email security", "Domain-based Message Authentication", ["DMARC", "domain-based message authentication"]),
  I("4.5", "Email security", "DomainKeys Identified Mail", ["DKIM", "domainkeys identified mail"]),
  I("4.5", "Email security", "Sender Policy Framework", ["SPF", "sender policy framework"]),
  I("4.5", "Email security", "Gateway", ["email gateway", "gateway di posta", "gateway"]),
  I("4.5", "Capabilities", "File integrity monitoring", ["file integrity monitoring", "monitoraggio dell'integrità dei file", "FIM"]),
  I("4.5", "Capabilities", "Data loss prevention", ["data loss prevention", "DLP"]),
  I("4.5", "Capabilities", "Network access control", ["network access control", "NAC"]),
  I("4.5", "Capabilities", "Endpoint/extended detection and response", ["EDR", "XDR", "endpoint detection and response"]),
  I("4.5", "Capabilities", "User behavior analytics", ["user behavior analytics", "UEBA", "analisi del comportamento"]),

  // ---- 4.6 IAM ----
  I("4.6", "IAM", "Provisioning/de-provisioning user accounts", ["provisioning", "de-provisioning", "provisioning degli account"]),
  I("4.6", "IAM", "Permission assignments and implications", ["permission assignment", "assegnazione dei permessi"]),
  I("4.6", "IAM", "Identity proofing", ["identity proofing", "verifica dell'identità"]),
  I("4.6", "IAM", "Federation", ["federation", "federazione"]),
  I("4.6", "SSO", "Lightweight Directory Access Protocol", ["LDAP", "lightweight directory access"]),
  I("4.6", "SSO", "Open authorization", ["OAuth", "open authorization"]),
  I("4.6", "SSO", "Security Assertions Markup Language", ["SAML", "security assertions markup"]),
  I("4.6", "IAM", "Interoperability", ["interoperability", "interoperabilità"]),
  I("4.6", "IAM", "Attestation", ["attestation", "attestazione"]),
  I("4.6", "Access controls", "Mandatory", ["mandatory access control", "MAC", "controllo d'accesso obbligatorio"]),
  I("4.6", "Access controls", "Discretionary", ["discretionary access control", "DAC", "discrezionale"]),
  I("4.6", "Access controls", "Role-based", ["role-based", "RBAC", "basato sui ruoli"]),
  I("4.6", "Access controls", "Rule-based", ["rule-based", "basato su regole"]),
  I("4.6", "Access controls", "Attribute-based", ["attribute-based", "ABAC", "basato su attributi"]),
  I("4.6", "Access controls", "Time-of-day restrictions", ["time-of-day", "restrizioni orarie", "fasce orarie"]),
  I("4.6", "Access controls", "Least privilege", ["least privilege", "privilegio minimo"]),
  I("4.6", "MFA implementations", "Biometrics", ["biometric", "biometri"]),
  I("4.6", "MFA implementations", "Hard/soft authentication tokens", ["authentication token", "token di autenticazione"]),
  I("4.6", "MFA implementations", "Security keys", ["security key", "chiavi di sicurezza"]),
  I("4.6", "MFA factors", "Something you know", ["something you know", "qualcosa che sai"]),
  I("4.6", "MFA factors", "Something you have", ["something you have", "qualcosa che hai"]),
  I("4.6", "MFA factors", "Something you are", ["something you are", "qualcosa che sei"]),
  I("4.6", "MFA factors", "Somewhere you are", ["somewhere you are", "da qualche parte"]),
  I("4.6", "Password best practices", "Length", ["password length", "lunghezza minima", "lunghezza della password"]),
  I("4.6", "Password best practices", "Complexity", ["complexity", "complessità"]),
  I("4.6", "Password best practices", "Reuse", ["reuse", "riutilizzo"]),
  I("4.6", "Password best practices", "Expiration", ["expiration", "scadenza"]),
  I("4.6", "Password best practices", "Age", ["password age", "età della password"]),
  I("4.6", "Password concepts", "Password managers", ["password manager", "gestore di password"]),
  I("4.6", "Password concepts", "Passwordless", ["passwordless", "without a password", "senza password"]),
  I("4.6", "PAM tools", "Just-in-time permissions", ["just-in-time", "permessi just-in-time"]),
  I("4.6", "PAM tools", "Password vaulting", ["password vaulting", "vault delle password"]),
  I("4.6", "PAM tools", "Ephemeral credentials", ["ephemeral credential", "credenziali effimere"]),

  // ---- 4.7 Automation and orchestration ----
  I("4.7", "Use cases", "User provisioning", ["user provisioning", "provisioning degli utenti"]),
  I("4.7", "Use cases", "Resource provisioning", ["resource provisioning", "provisioning delle risorse"]),
  I("4.7", "Use cases", "Guard rails", ["guard rail", "guardrail"]),
  I("4.7", "Use cases", "Security groups", ["security group", "gruppi di sicurezza"]),
  I("4.7", "Use cases", "Ticket creation", ["ticket creation", "creazione di ticket"]),
  I("4.7", "Use cases", "Escalation", ["escalation", "escalation"]),
  I("4.7", "Use cases", "Enabling/disabling services and access", ["enabling and disabling", "abilitazione e disabilitazione"]),
  I("4.7", "Use cases", "Continuous integration and testing", ["continuous integration", "integrazione continua", "CI/CD"]),
  I("4.7", "Use cases", "Integrations and APIs", ["application programming interface", "API", "integrazioni"]),
  I("4.7", "Benefits", "Efficiency/time saving", ["efficiency", "efficienza", "risparmio di tempo"]),
  I("4.7", "Benefits", "Enforcing baselines", ["enforcing baseline", "applicazione delle baseline"]),
  I("4.7", "Benefits", "Standard infrastructure configurations", ["standard configuration", "configurazioni standard"]),
  I("4.7", "Benefits", "Scaling in a secure manner", ["scaling", "scalare in modo sicuro"]),
  I("4.7", "Benefits", "Employee retention", ["employee retention", "fidelizzazione del personale"]),
  I("4.7", "Benefits", "Reaction time", ["reaction time", "tempo di reazione"]),
  I("4.7", "Benefits", "Workforce multiplier", ["workforce multiplier", "moltiplicatore della forza lavoro"]),
  I("4.7", "Other considerations", "Complexity", ["complexity", "complessità"]),
  I("4.7", "Other considerations", "Cost", ["cost", "costo"]),
  I("4.7", "Other considerations", "Single point of failure", ["single point of failure", "punto di guasto singolo"]),
  I("4.7", "Other considerations", "Technical debt", ["technical debt", "debito tecnico"]),
  I("4.7", "Other considerations", "Ongoing supportability", ["ongoing supportability", "supportabilità"]),

  // ---- 4.8 Incident response ----
  I("4.8", "Process", "Preparation", ["preparation", "preparazione"]),
  I("4.8", "Process", "Detection", ["detection", "rilevamento"]),
  I("4.8", "Process", "Analysis", ["analysis", "analisi"]),
  I("4.8", "Process", "Containment", ["containment", "contenimento"]),
  I("4.8", "Process", "Eradication", ["eradication", "eradicazione"]),
  I("4.8", "Process", "Recovery", ["recovery", "ripristino"]),
  I("4.8", "Process", "Lessons learned", ["lessons learned", "lezioni apprese"]),
  I("4.8", "IR", "Training", ["training", "formazione"]),
  I("4.8", "Testing", "Tabletop exercise", ["tabletop", "simulazione a tavolino"]),
  I("4.8", "Testing", "Simulation", ["simulation", "simulazione"]),
  I("4.8", "IR", "Root cause analysis", ["root cause analysis", "analisi delle cause"]),
  I("4.8", "IR", "Threat hunting", ["threat hunting"]),
  I("4.8", "Digital forensics", "Legal hold", ["legal hold", "conservazione legale"]),
  I("4.8", "Digital forensics", "Chain of custody", ["chain of custody", "catena di custodia"]),
  I("4.8", "Digital forensics", "Acquisition", ["acquisition", "acquisizione"]),
  I("4.8", "Digital forensics", "Reporting", ["reporting", "reportistica"]),
  I("4.8", "Digital forensics", "Preservation", ["preservation", "conservazione"]),
  I("4.8", "Digital forensics", "E-discovery", ["e-discovery", "ediscovery"]),

  // ---- 4.9 Data sources for investigation ----
  I("4.9", "Log data", "Firewall logs", ["firewall log", "log del firewall"]),
  I("4.9", "Log data", "Application logs", ["application log", "log delle applicazioni"]),
  I("4.9", "Log data", "Endpoint logs", ["endpoint log", "log degli endpoint"]),
  I("4.9", "Log data", "OS-specific security logs", ["OS-specific", "log di sicurezza del sistema operativo"]),
  I("4.9", "Log data", "IPS/IDS logs", ["IPS/IDS log", "log IPS", "log IDS"]),
  I("4.9", "Log data", "Network logs", ["network log", "log di rete"]),
  I("4.9", "Log data", "Metadata", ["metadata", "metadati"]),
  I("4.9", "Data sources", "Vulnerability scans", ["vulnerability scan", "scansione delle vulnerabilità"]),
  I("4.9", "Data sources", "Automated reports", ["automated report", "report automatici"]),
  I("4.9", "Data sources", "Dashboards", ["dashboard"]),
  I("4.9", "Data sources", "Packet captures", ["packet capture", "cattura dei pacchetti", "PCAP"]),

  // ---- 5.1 Security governance ----
  I("5.1", "Governance", "Guidelines", ["guidelines", "linee guida"]),
  I("5.1", "Policies", "Acceptable use policy", ["acceptable use policy", "AUP", "uso accettabile"]),
  I("5.1", "Policies", "Information security policies", ["information security policy", "politiche di sicurezza delle informazioni"]),
  I("5.1", "Policies", "Business continuity", ["business continuity", "continuità operativa"]),
  I("5.1", "Policies", "Disaster recovery", ["disaster recovery", "ripristino di emergenza"]),
  I("5.1", "Policies", "Incident response (policy)", ["incident response", "risposta agli incidenti"]),
  I("5.1", "Policies", "Software development lifecycle", ["software development lifecycle", "SDLC", "ciclo di vita dello sviluppo"]),
  I("5.1", "Policies", "Change management (policy)", ["change management", "gestione del cambiamento"]),
  I("5.1", "Standards", "Password standard", ["password standard", "standard delle password"]),
  I("5.1", "Standards", "Access control standard", ["access control standard", "standard di controllo degli accessi"]),
  I("5.1", "Standards", "Physical security standard", ["physical security standard", "standard di sicurezza fisica"]),
  I("5.1", "Standards", "Encryption standard", ["encryption standard", "standard di cifratura"]),
  I("5.1", "Procedures", "Change management (procedure)", ["change management", "gestione del cambiamento"]),
  I("5.1", "Procedures", "Onboarding/offboarding", ["onboarding", "offboarding"]),
  I("5.1", "Procedures", "Playbooks", ["playbook"]),
  I("5.1", "External considerations", "Regulatory", ["regulatory", "normativ"]),
  I("5.1", "External considerations", "Legal", ["legal", "legale"]),
  I("5.1", "External considerations", "Industry", ["industry", "settore", "di settore"]),
  I("5.1", "External considerations", "Local/regional", ["local/regional", "locale/regionale"]),
  I("5.1", "External considerations", "National", ["national", "nazionale"]),
  I("5.1", "External considerations", "Global", ["global", "globale"]),
  I("5.1", "Governance", "Monitoring and revision", ["monitoring and revision", "monitoraggio e revisione"]),
  I("5.1", "Governance structures", "Boards", ["board", "consigli"]),
  I("5.1", "Governance structures", "Committees", ["committee", "comitati"]),
  I("5.1", "Governance structures", "Government entities", ["government entities", "enti governativi"]),
  I("5.1", "Governance structures", "Centralized/decentralized", ["centralized", "decentralized", "centralizzata", "decentralizzata"]),
  I("5.1", "Roles and responsibilities", "Owners", ["owner", "titolari", "proprietari"]),
  I("5.1", "Roles and responsibilities", "Controllers", ["controller", "titolari del trattamento"]),
  I("5.1", "Roles and responsibilities", "Processors", ["processor", "responsabili del trattamento"]),
  I("5.1", "Roles and responsibilities", "Custodians/stewards", ["custodian", "steward", "custodi"]),

  // ---- 5.2 Risk management ----
  I("5.2", "Risk", "Risk identification", ["risk identification", "identificazione del rischio"]),
  I("5.2", "Risk assessment", "Ad hoc", ["ad hoc"]),
  I("5.2", "Risk assessment", "Recurring", ["recurring", "ricorrente"]),
  I("5.2", "Risk assessment", "One-time", ["one-time", "una tantum"]),
  I("5.2", "Risk assessment", "Continuous", ["continuous", "continuo", "continua"]),
  I("5.2", "Risk analysis", "Qualitative", ["qualitative", "qualitativa"]),
  I("5.2", "Risk analysis", "Quantitative", ["quantitative", "quantitativa"]),
  I("5.2", "Risk analysis", "Single loss expectancy", ["single loss expectancy", "SLE"]),
  I("5.2", "Risk analysis", "Annualized loss expectancy", ["annualized loss expectancy", "ALE"]),
  I("5.2", "Risk analysis", "Annualized rate of occurrence", ["annualized rate of occurrence", "ARO"]),
  I("5.2", "Risk analysis", "Probability", ["probability", "probabilità"]),
  I("5.2", "Risk analysis", "Likelihood", ["likelihood", "verosimiglianza", "probabilità"]),
  I("5.2", "Risk analysis", "Exposure factor", ["exposure factor", "fattore di esposizione"]),
  I("5.2", "Risk analysis", "Impact", ["impact", "impatto"]),
  I("5.2", "Risk register", "Key risk indicators", ["key risk indicator", "KRI", "indicatori chiave di rischio"]),
  I("5.2", "Risk register", "Risk owners", ["risk owner", "proprietari del rischio"]),
  I("5.2", "Risk register", "Risk threshold", ["risk threshold", "soglia di rischio"]),
  I("5.2", "Risk", "Risk tolerance", ["risk tolerance", "tolleranza al rischio"]),
  I("5.2", "Risk appetite", "Expansionary", ["expansionary", "espansiva"]),
  I("5.2", "Risk appetite", "Conservative", ["conservative", "conservativa"]),
  I("5.2", "Risk appetite", "Neutral", ["neutral", "neutrale"]),
  I("5.2", "Risk strategies", "Transfer", ["risk transfer", "transference", "trasferimento del rischio"]),
  I("5.2", "Risk strategies", "Exemption", ["exemption", "esenzione"]),
  I("5.2", "Risk strategies", "Exception", ["exception", "eccezione"]),
  I("5.2", "Risk strategies", "Avoid", ["avoid", "evitare", "evitamento"]),
  I("5.2", "Risk strategies", "Mitigate", ["mitigate", "mitigare", "mitigazione"]),
  I("5.2", "Risk", "Risk reporting", ["risk reporting", "rendicontazione del rischio"]),
  I("5.2", "Business impact analysis", "Recovery time objective", ["recovery time objective", "RTO"]),
  I("5.2", "Business impact analysis", "Recovery point objective", ["recovery point objective", "RPO"]),
  I("5.2", "Business impact analysis", "Mean time to repair", ["mean time to repair", "MTTR"]),
  I("5.2", "Business impact analysis", "Mean time between failures", ["mean time between failures", "MTBF"]),

  // ---- 5.3 Third-party risk ----
  I("5.3", "Vendor assessment", "Penetration testing", ["penetration testing", "test di penetrazione"]),
  I("5.3", "Vendor assessment", "Right-to-audit clause", ["right-to-audit", "clausola di audit"]),
  I("5.3", "Vendor assessment", "Evidence of internal audits", ["evidence of internal audit", "prove di audit interni"]),
  I("5.3", "Vendor assessment", "Independent assessments", ["independent assessment", "valutazioni indipendenti"]),
  I("5.3", "Vendor assessment", "Supply chain analysis", ["supply chain analysis", "analisi della supply chain"]),
  I("5.3", "Vendor selection", "Due diligence", ["due diligence"]),
  I("5.3", "Vendor selection", "Conflict of interest", ["conflict of interest", "conflitto di interessi"]),
  I("5.3", "Agreement types", "Service-level agreement", ["service-level agreement", "SLA"]),
  I("5.3", "Agreement types", "Memorandum of agreement", ["memorandum of agreement", "MOA"]),
  I("5.3", "Agreement types", "Memorandum of understanding", ["memorandum of understanding", "MOU"]),
  I("5.3", "Agreement types", "Master service agreement", ["master service agreement", "MSA"]),
  I("5.3", "Agreement types", "Work order/statement of work", ["work order", "statement of work", "SOW"]),
  I("5.3", "Agreement types", "Non-disclosure agreement", ["non-disclosure agreement", "NDA"]),
  I("5.3", "Agreement types", "Business partners agreement", ["business partners agreement", "BPA"]),
  I("5.3", "Third-party risk", "Vendor monitoring", ["vendor monitoring", "monitoraggio dei fornitori"]),
  I("5.3", "Third-party risk", "Questionnaires", ["questionnaire", "questionari"]),
  I("5.3", "Third-party risk", "Rules of engagement", ["rules of engagement", "regole d'ingaggio"]),

  // ---- 5.4 Security compliance ----
  I("5.4", "Compliance reporting", "Internal", ["internal", "interno", "interna"]),
  I("5.4", "Compliance reporting", "External", ["external", "esterno", "esterna"]),
  I("5.4", "Consequences", "Fines", ["fines", "sanzioni pecuniarie", "multe"]),
  I("5.4", "Consequences", "Sanctions", ["sanctions", "sanzioni"]),
  I("5.4", "Consequences", "Reputational damage", ["reputational damage", "danno reputazionale"]),
  I("5.4", "Consequences", "Loss of license", ["loss of license", "withdrawal of the operating license", "perdita della licenza", "revoca della licenza"]),
  I("5.4", "Consequences", "Contractual impacts", ["contractual impact", "impatti contrattuali"]),
  I("5.4", "Compliance monitoring", "Due diligence/care", ["due diligence", "due care", "dovuta diligenza"]),
  I("5.4", "Compliance monitoring", "Attestation and acknowledgement", ["attestation and acknowledgement", "attestazione e riconoscimento"]),
  I("5.4", "Compliance monitoring", "Internal and external", ["internal and external", "interno ed esterno"]),
  I("5.4", "Compliance monitoring", "Automation", ["automation", "automazione"]),
  I("5.4", "Privacy / Legal implications", "Local/regional", ["local/regional", "locale/regionale"]),
  I("5.4", "Privacy / Legal implications", "National", ["national", "nazionale"]),
  I("5.4", "Privacy / Legal implications", "Global", ["global", "globale"]),
  I("5.4", "Privacy", "Data subject", ["data subject", "interessato"]),
  I("5.4", "Privacy", "Controller vs. processor", ["controller", "processor", "titolare", "responsabile del trattamento"]),
  I("5.4", "Privacy", "Ownership", ["ownership", "titolarità"]),
  I("5.4", "Privacy", "Data inventory and retention", ["data inventory", "inventario dei dati", "retention"]),
  I("5.4", "Privacy", "Right to be forgotten", ["right to be forgotten", "diritto all'oblio"]),

  // ---- 5.5 Audits and assessments ----
  I("5.5", "Audits", "Attestation", ["attestation", "attestazione"]),
  I("5.5", "Internal", "Compliance (internal)", ["compliance", "conformità"]),
  I("5.5", "Internal", "Audit committee", ["audit committee", "comitato di audit"]),
  I("5.5", "Internal", "Self-assessments", ["self-assessment", "autovalutazioni"]),
  I("5.5", "External", "Regulatory", ["regulatory", "normativo"]),
  I("5.5", "External", "Examinations", ["examination", "esami", "ispezioni"]),
  I("5.5", "External", "Assessment", ["assessment", "valutazione"]),
  I("5.5", "External", "Independent third-party audit", ["third-party audit", "revisore indipendente", "audit di terza parte"]),
  I("5.5", "Penetration testing", "Physical", ["physical", "fisico"]),
  I("5.5", "Penetration testing", "Offensive", ["offensive", "offensivo"]),
  I("5.5", "Penetration testing", "Defensive", ["defensive", "difensivo"]),
  I("5.5", "Penetration testing", "Integrated", ["integrated", "integrato"]),
  I("5.5", "Penetration testing", "Known environment", ["known environment", "ambiente noto"]),
  I("5.5", "Penetration testing", "Partially known environment", ["partially known environment", "ambiente parzialmente noto"]),
  I("5.5", "Penetration testing", "Unknown environment", ["unknown environment", "ambiente sconosciuto"]),
  I("5.5", "Reconnaissance", "Passive reconnaissance", ["passive reconnaissance", "ricognizione passiva"]),
  I("5.5", "Reconnaissance", "Active reconnaissance", ["active reconnaissance", "ricognizione attiva"]),

  // ---- 5.6 Security awareness ----
  I("5.6", "Phishing", "Campaigns", ["phishing campaign", "campagne di phishing"]),
  I("5.6", "Phishing", "Recognizing a phishing attempt", ["identify phishing", "recognizing a phishing", "riconoscere un tentativo di phishing"]),
  I("5.6", "Phishing", "Responding to reported suspicious messages", ["suspicious message", "messaggi sospetti"]),
  I("5.6", "Anomalous behavior", "Risky", ["risky behavior", "comportamento rischioso", "rischioso"]),
  I("5.6", "Anomalous behavior", "Unexpected", ["unexpected behavior", "inatteso", "comportamento inatteso"]),
  I("5.6", "Anomalous behavior", "Unintentional", ["unintentional", "non intenzionale"]),
  I("5.6", "User guidance", "Policy/handbooks", ["handbook", "manuali", "policy/handbook"]),
  I("5.6", "User guidance", "Situational awareness", ["situational awareness", "consapevolezza situazionale"]),
  I("5.6", "User guidance", "Insider threat", ["insider threat", "minaccia interna"]),
  I("5.6", "User guidance", "Password management", ["password management", "gestione delle password"]),
  I("5.6", "User guidance", "Removable media and cables", ["removable media", "supporti rimovibili", "cavi"]),
  I("5.6", "User guidance", "Social engineering", ["social engineering", "ingegneria sociale"]),
  I("5.6", "User guidance", "Operational security", ["operational security", "sicurezza operativa", "OPSEC"]),
  I("5.6", "User guidance", "Hybrid/remote work environments", ["hybrid work", "remote work", "lavoro remoto", "lavoro ibrido"]),
  I("5.6", "Reporting and monitoring", "Initial", ["initial", "iniziale"]),
  I("5.6", "Reporting and monitoring", "Recurring", ["recurring", "ricorrente"]),
  I("5.6", "Awareness", "Development", ["development", "sviluppo"]),
  I("5.6", "Awareness", "Execution", ["execution", "esecuzione"]),
];
