import type { Lang } from "./i18n";
import type { TopicGroup } from "./types";

/**
 * Acronyms that were not yet represented by a standalone glossary entry.
 * Expansions intentionally reproduce the official CompTIA SY0-701 Acronym
 * List verbatim; the learner-facing explanation is localized separately.
 */
export const ACRONYM_APPENDIX = [
  ["2FA", "Two-factor Authentication"],
  ["3DES", "Triple Data Encryption Standard"],
  ["AES-256", "Advanced Encryption Standards 256-bit"],
  ["AH", "Authentication Header"],
  ["AI", "Artificial Intelligence"],
  ["AIS", "Automated Indicator Sharing"],
  ["AP", "Access Point"],
  ["APT", "Advanced Persistent Threat"],
  ["ARP", "Address Resolution Protocol"],
  ["ASLR", "Address Space Layout Randomization"],
  ["ATT&CK", "Adversarial Tactics, Techniques, and Common Knowledge"],
  ["AV", "Antivirus"],
  ["BASH", "Bourne Again Shell"],
  ["BGP", "Border Gateway Protocol"],
  ["BIA", "Business Impact Analysis"],
  ["BIOS", "Basic Input/Output System"],
  ["BPDU", "Bridge Protocol Data Unit"],
  ["CA", "Certificate Authority"],
  ["CAPTCHA", "Completely Automated Public Turing Test to Tell Computers and Humans Apart"],
  ["CAR", "Corrective Action Report"],
  ["CASB", "Cloud Access Security Broker"],
  ["CBC", "Cipher Block Chaining"],
  ["CCTV", "Closed-circuit Television"],
  ["CERT", "Computer Emergency Response Team"],
  ["CFB", "Cipher Feedback"],
  ["CHAP", "Challenge Handshake Authentication Protocol"],
  ["CIA", "Confidentiality, Integrity, Availability"],
  ["CIO", "Chief Information Officer"],
  ["CIRT", "Computer Incident Response Team"],
  ["CMS", "Content Management System"],
  ["COBO", "Corporate-owned, Business-only"],
  ["COOP", "Continuity of Operation Planning"],
  ["CP", "Contingency Planning"],
  ["CRC", "Cyclical Redundancy Check"],
  ["CSO", "Chief Security Officer"],
  ["CSP", "Cloud Service Provider"],
  ["CSU", "Channel Service Unit"],
  ["CTM", "Counter Mode"],
  ["CTO", "Chief Technology Officer"],
  ["DAC", "Discretionary Access Control"],
  ["DBA", "Database Administrator"],
  ["DDoS", "Distributed Denial of Service"],
  ["DEP", "Data Execution Prevention"],
  ["DES", "Digital Encryption Standard"],
  ["DHCP", "Dynamic Host Configuration Protocol"],
  ["DHE", "Diffie-Hellman Ephemeral"],
  ["DLL", "Dynamic Link Library"],
  ["DNAT", "Destination Network Address Translation"],
  ["DNS", "Domain Name System"],
  ["DNSSEC", "Domain Name System Security Extensions"],
  ["DoS", "Denial of Service"],
  ["DPO", "Data Privacy Officer"],
  ["DSA", "Digital Signature Algorithm"],
  ["DSL", "Digital Subscriber Line"],
  ["ECB", "Electronic Code Book"],
  ["ECC", "Elliptic Curve Cryptography"],
  ["ECDHE", "Elliptic Curve Diffie-Hellman Ephemeral"],
  ["ECDSA", "Elliptic Curve Digital Signature Algorithm"],
  ["EDR", "Endpoint Detection and Response"],
  ["EFS", "Encrypted File System"],
  ["ERP", "Enterprise Resource Planning"],
  ["ESN", "Electronic Serial Number"],
  ["ESP", "Encapsulated Security Payload"],
  ["EULA", "End User License Agreement"],
  ["FACL", "File System Access Control List"],
  ["FDE", "Full Disk Encryption"],
  ["FPGA", "Field Programmable Gate Array"],
  ["FRR", "False Rejection Rate"],
  ["FTP", "File Transfer Protocol"],
  ["FTPS", "Secured File Transfer Protocol"],
  ["GCM", "Galois Counter Mode"],
  ["GPG", "Gnu Privacy Guard"],
  ["GPO", "Group Policy Object"],
  ["GPS", "Global Positioning System"],
  ["GPU", "Graphics Processing Unit"],
  ["GRE", "Generic Routing Encapsulation"],
  ["HDD", "Hard Disk Drive"],
  ["HIDS", "Host-based Intrusion Detection System"],
  ["HIPS", "Host-based Intrusion Prevention System"],
  ["HMAC", "Hashed Message Authentication Code"],
  ["HOTP", "HMAC-based One-time Password"],
  ["HTML", "Hypertext Markup Language"],
  ["HTTP", "Hypertext Transfer Protocol"],
  ["HTTPS", "Hypertext Transfer Protocol Secure"],
  ["IAM", "Identity and Access Management"],
  ["ICMP", "Internet Control Message Protocol"],
  ["IDEA", "International Data Encryption Algorithm"],
  ["IDF", "Intermediate Distribution Frame"],
  ["IdP", "Identity Provider"],
  ["IDS", "Intrusion Detection System"],
  ["IEEE", "Institute of Electrical and Electronics Engineers"],
  ["IKE", "Internet Key Exchange"],
  ["IM", "Instant Messaging"],
  ["IMAP", "Internet Message Access Protocol"],
  ["IoC", "Indicators of Compromise"],
  ["IP", "Internet Protocol"],
  ["IR", "Incident Response"],
  ["IRC", "Internet Relay Chat"],
  ["IRP", "Incident Response Plan"],
  ["ISO", "International Standards Organization"],
  ["ISP", "Internet Service Provider"],
  ["ISSO", "Information Systems Security Officer"],
  ["IV", "Initialization Vector"],
  ["KDC", "Key Distribution Center"],
  ["KEK", "Key Encryption Key"],
  ["L2TP", "Layer 2 Tunneling Protocol"],
  ["LAN", "Local Area Network"],
  ["MaaS", "Monitoring as a Service"],
  ["MAC", "Mandatory Access Control / Media Access Control / Message Authentication Code"],
  ["MAN", "Metropolitan Area Network"],
  ["MBR", "Master Boot Record"],
  ["MD5", "Message Digest 5"],
  ["MDF", "Main Distribution Frame"],
  ["MFD", "Multifunction Device"],
  ["MFP", "Multifunction Printer"],
  ["ML", "Machine Learning"],
  ["MMS", "Multimedia Message Service"],
  ["MPLS", "Multi-protocol Label Switching"],
  ["MSCHAP", "Microsoft Challenge Handshake Authentication Protocol"],
  ["MSP", "Managed Service Provider"],
  ["MSSP", "Managed Security Service Provider"],
  ["MTBF", "Mean Time Between Failures"],
  ["MTTF", "Mean Time to Failure"],
  ["MTTR", "Mean Time to Recover"],
  ["MTU", "Maximum Transmission Unit"],
  ["MX", "Mail Exchange"],
  ["NAT", "Network Address Translation"],
  ["NFC", "Near Field Communication"],
  ["NIDS", "Network-based Intrusion Detection System"],
  ["NIPS", "Network-based Intrusion Prevention System"],
  ["NIST", "National Institute of Standards & Technology"],
  ["NTFS", "New Technology File System"],
  ["NTP", "Network Time Protocol"],
  ["OAUTH", "Open Authorization"],
  ["OID", "Object Identifier"],
  ["OS", "Operating System"],
  ["OSPF", "Open Shortest Path First"],
  ["OT", "Operational Technology"],
  ["OTA", "Over the Air"],
  ["OVAL", "Open Vulnerability Assessment Language"],
  ["OWASP", "Open Worldwide Application Security Project"],
  ["P2P", "Peer to Peer"],
  ["PAC", "Proxy Auto Configuration"],
  ["PAM", "Privileged Access Management / Pluggable Authentication Modules"],
  ["PAT", "Port Address Translation"],
  ["PBKDF2", "Password-based Key Derivation Function 2"],
  ["PBX", "Private Branch Exchange"],
  ["PCAP", "Packet Capture"],
  ["PDU", "Power Distribution Unit"],
  ["PED", "Personal Electronic Device"],
  ["PGP", "Pretty Good Privacy"],
  ["PHI", "Personal Health Information"],
  ["PII", "Personally Identifiable Information"],
  ["PIV", "Personal Identity Verification"],
  ["PKCS", "Public Key Cryptography Standards"],
  ["POP", "Post Office Protocol"],
  ["POTS", "Plain Old Telephone Service"],
  ["PPP", "Point-to-Point Protocol"],
  ["PPTP", "Point-to-Point Tunneling Protocol"],
  ["PTZ", "Pan-tilt-zoom"],
  ["PUP", "Potentially Unwanted Program"],
  ["RA", "Recovery Agent / Registration Authority"],
  ["RACE", "Research and Development in Advanced Communications Technologies in Europe"],
  ["RAD", "Rapid Application Development"],
  ["RAID", "Redundant Array of Inexpensive Disks"],
  ["RAS", "Remote Access Server"],
  ["RAT", "Remote Access Trojan"],
  ["RBAC", "Role-based Access Control / Rule-based Access Control"],
  ["RC4", "Rivest Cipher version 4"],
  ["RDP", "Remote Desktop Protocol"],
  ["RIPEMD", "RACE Integrity Primitives Evaluation Message Digest"],
  ["ROI", "Return on Investment"],
  ["RSA", "Rivest, Shamir, & Adleman"],
  ["RTBH", "Remotely Triggered Black Hole"],
  ["RTP", "Real-time Transport Protocol"],
  ["S/MIME", "Secure/Multipurpose Internet Mail Extensions"],
  ["SAN", "Storage Area Network / Subject Alternative Name"],
  ["SASE", "Secure Access Service Edge"],
  ["SCEP", "Simple Certificate Enrollment Protocol"],
  ["SD-WAN", "Software-defined Wide Area Network"],
  ["SDK", "Software Development Kit"],
  ["SDLM", "Software Development Lifecycle Methodology"],
  ["SE Linux", "Security-enhanced Linux"],
  ["SED", "Self-encrypting Drives"],
  ["SEH", "Structured Exception Handler"],
  ["SFTP", "Secured File Transfer Protocol"],
  ["SHA", "Secure Hashing Algorithm"],
  ["SHTTP", "Secure Hypertext Transfer Protocol"],
  ["SIM", "Subscriber Identity Module"],
  ["SMB", "Server Message Block"],
  ["SMS", "Short Message Service"],
  ["SMTPS", "Simple Mail Transfer Protocol Secure"],
  ["SOAP", "Simple Object Access Protocol"],
  ["SOAR", "Security Orchestration, Automation, Response"],
  ["SOC", "Security Operations Center"],
  ["SoC", "System on Chip"],
  ["SPIM", "Spam over Internet Messaging"],
  ["SQL", "Structured Query Language"],
  ["SRTP", "Secure Real-Time Protocol"],
  ["SSD", "Solid State Drive"],
  ["SSL", "Secure Sockets Layer"],
  ["STIX", "Structured Threat Information eXchange"],
  ["SWG", "Secure Web Gateway"],
  ["TACACS+", "Terminal Access Controller Access Control System"],
  ["TAXII", "Trusted Automated eXchange of Indicator Information"],
  ["TCP/IP", "Transmission Control Protocol/Internet Protocol"],
  ["TGT", "Ticket Granting Ticket"],
  ["TOC", "Time-of-check"],
  ["TOTP", "Time-based One-time Password"],
  ["TOU", "Time-of-use"],
  ["TSIG", "Transaction Signature"],
  ["TTP", "Tactics, Techniques, and Procedures"],
  ["UAT", "User Acceptance Testing"],
  ["UAV", "Unmanned Aerial Vehicle"],
  ["UDP", "User Datagram Protocol"],
  ["UEFI", "Unified Extensible Firmware Interface"],
  ["UEM", "Unified Endpoint Management"],
  ["URI", "Uniform Resource Identifier"],
  ["URL", "Universal Resource Locator"],
  ["USB", "Universal Serial Bus"],
  ["USB OTG", "USB On the Go"],
  ["UTP", "Unshielded Twisted Pair"],
  ["VBA", "Visual Basic"],
  ["VDE", "Virtual Desktop Environment"],
  ["VDI", "Virtual Desktop Infrastructure"],
  ["VLSM", "Variable Length Subnet Masking"],
  ["VoIP", "Voice over IP"],
  ["VPC", "Virtual Private Cloud"],
  ["VTC", "Video Teleconferencing"],
  ["WAP", "Wireless Access Point"],
  ["WIDS", "Wireless Intrusion Detection System"],
  ["WIPS", "Wireless Intrusion Prevention System"],
  ["WO", "Work Order"],
  ["XDR", "Extended Detection and Response"],
  ["XML", "Extensible Markup Language"],
  ["XOR", "Exclusive Or"],
] as const;

const DOMAIN_1 = new Set(["2FA", "CFB", "CHAP", "CTM", "DSA", "GPG", "IDEA", "KEK", "MSCHAP", "PIV", "RIPEMD", "S/MIME", "SCEP", "SED", "TSIG"]);
const DOMAIN_2 = new Set(["IM", "IRC", "MMS", "P2P", "PUP", "SEH", "SPIM", "UAV", "VBA"]);
const DOMAIN_3 = new Set(["COBO", "CSU", "DNAT", "DSL", "ESN", "FPGA", "GRE", "IDF", "ISP", "MAN", "MBR", "MDF", "MFD", "MTU", "OTA", "PAT", "PBX", "PED", "POP", "POTS", "PTZ", "RAS", "RTP", "SoC", "SRTP", "TCP/IP", "USB OTG", "VDE", "VDI", "VLSM", "VPC", "VTC"]);
const DOMAIN_4 = new Set(["AIS", "BASH", "CIRT", "FTPS", "MaaS", "ML", "MSSP", "NIPS", "RTBH", "SHTTP", "SOAP", "UEM", "WIDS", "WIPS"]);

export const acronymAppendixDomain = (acronym: string): number =>
  DOMAIN_1.has(acronym) ? 1 : DOMAIN_2.has(acronym) ? 2 : DOMAIN_3.has(acronym) ? 3 : DOMAIN_4.has(acronym) ? 4 : 5;

const OBJECTIVE: Record<number, string> = { 1: "1.4", 2: "2.4", 3: "3.1", 4: "4.4", 5: "5.1" };
const GROUP_TITLE: Record<Lang, Record<number, string>> = {
  it: {
    1: "Appendice sigle: controlli e crittografia (Obj 1.4)",
    2: "Appendice sigle: minacce e vulnerabilità (Obj 2.4)",
    3: "Appendice sigle: architettura e infrastruttura (Obj 3.1)",
    4: "Appendice sigle: operazioni di sicurezza (Obj 4.4)",
    5: "Appendice sigle: governance e programma (Obj 5.1)",
  },
  en: {
    1: "Acronym appendix: controls and cryptography (Obj 1.4)",
    2: "Acronym appendix: threats and vulnerabilities (Obj 2.4)",
    3: "Acronym appendix: architecture and infrastructure (Obj 3.1)",
    4: "Acronym appendix: security operations (Obj 4.4)",
    5: "Acronym appendix: governance and program (Obj 5.1)",
  },
};

const keyOf = (acronym: string) => `AcronymAppendix_${acronym.replace(/[^A-Za-z0-9]+/g, "_")}`;
const LEGACY = new Set(["IDEA", "POTS", "RACE", "RIPEMD", "SHTTP"]);

const distinction = (acronym: string, lang: Lang): string => {
  if (acronym === "FTPS") return lang === "it" ? " Non confonderlo con SFTP, che usa SSH." : " Do not confuse it with SFTP, which uses SSH.";
  if (acronym === "SoC") return lang === "it" ? " Non confonderlo con SOC, il Security Operations Center." : " Do not confuse it with SOC, the Security Operations Center.";
  if (acronym === "SHTTP") return lang === "it" ? " È storico e distinto da HTTPS/TLS." : " It is historical and distinct from HTTPS/TLS.";
  return "";
};

export function acronymAppendixTopics(domainId: number, lang: Lang): TopicGroup[] {
  const entries = ACRONYM_APPENDIX.filter(([acronym]) => acronymAppendixDomain(acronym) === domainId);
  if (entries.length === 0) return [];
  return [{
    title: GROUP_TITLE[lang][domainId],
    description: lang === "it"
      ? "Voci autonome della Acronym List ufficiale SY0-701, ricercabili e disponibili come flashcard."
      : "Standalone entries from the official SY0-701 Acronym List, searchable and available as flashcards.",
    icon: "BookOpen",
    subtopics: entries.map(([acronym, expansion]) => ({
      name: `${expansion} (${acronym})`,
      checklistKey: keyOf(acronym),
      definition: lang === "it"
        ? `${expansion}: termine ${LEGACY.has(acronym) ? "legacy/storico " : ""}della Acronym List SY0-701 usato nel contesto di sicurezza del dominio ${domainId}.${distinction(acronym, lang)}`
        : `${expansion}: a ${LEGACY.has(acronym) ? "legacy/historical " : ""}term in the SY0-701 Acronym List used in the security context of domain ${domainId}.${distinction(acronym, lang)}`,
      details: lang === "it"
        ? `La sigla ${acronym} identifica ${expansion}. Associa la sigla all'obiettivo ${OBJECTIVE[domainId]} e distingui il nome esteso dalla funzione concreta descritta nello scenario. **Piccolo Esempio Concentrato:** in una domanda d'esame, riconoscere ${acronym} permette di classificare subito la tecnologia, il ruolo o il processo citato.`
        : `The acronym ${acronym} identifies ${expansion}. Link it to objective ${OBJECTIVE[domainId]} and distinguish the expanded name from the concrete function described by the scenario. **Focused Mini-Example:** in an exam question, recognizing ${acronym} immediately helps classify the cited technology, role, or process.`,
      examTip: lang === "it"
        ? `Memorizza l'associazione esatta ${acronym} ↔ ${expansion}; poi verifica nella domanda quale funzione o rischio viene richiesto.`
        : `Memorize the exact ${acronym} ↔ ${expansion} association; then identify which function or risk the question asks about.`,
    })),
  }];
}
