/**
 * Where each statement about a law or a standard can be checked (ROADMAP:
 * "Citazioni verificabili"). The sources of every objective are in
 * src/contentReview.ts; here a single concept that names a regulation, a
 * standard or a scoring system points to that document, and to the exact
 * article when the text states a specific rule (a deadline, a fine, a scope).
 *
 * The study view lists these under each concept, and docs/gap-analysis.md
 * writes their URLs, which the weekly external-link check verifies.
 * tests/citations.test.ts fails when a concept names a document it does not
 * cite, so a new normative statement cannot arrive without its source.
 * A locator is written only when it is certain: otherwise the citation points
 * to the document as a whole, never to a guessed article.
 */
import type { ConceptRef } from "./canonicalTerms";
import type { SourceId } from "./contentReview";

export interface Citation {
  source: SourceId;
  /** Article, section or paragraph, in each language. */
  locator?: { it: string; en: string };
}

/** How the study text names each cited document. */
export const MENTIONS: [SourceId, RegExp][] = [
  ["sox", /\bSOX\b|SEC Sarbanes-Oxley Rulemaking/],
  ["glba", /\bGLBA\b|FTC Gramm-Leach-Bliley Act/],
  ["ftcSafeguards", /FTC Safeguards Rule/],
  ["hipaaCovered", /HHS Covered Entities and Business Associates/],
  ["hipaaSecurity", /HHS Security Rule/],
  ["pciPrograms", /PCI SSC compliance programs/],
  ["samlCore", /OASIS SAML 2.0 Core/],
  ["rfc6749", /RFC 6749/],
  ["oidcCore", /OpenID Connect Core/],
  ["rfc4120", /RFC 4120/],
  ["icannHijacking", /ICANN Domain Name Registration Hijacking/],
  ["icannProtection", /ICANN Protect Your Domain Name/],
  ["icannLocks", /ICANN EPP Status Codes/],
  ["rfc4033", /RFC 4033/],
  ["ieee80211", /IEEE Std 802\.11/],
  ["wifiAlliance", /Wi-Fi Alliance/],
  ["ciscoEolPolicy", /Cisco End-of-Life Policy/],

  ["owaspSession", /Session Management Cheat Sheet/],
  ["mdnCookies", /MDN Set-Cookie/],
  ["owaspXss", /XSS Prevention Cheat Sheet/],
  ["owaspCsrf", /CSRF Prevention Cheat Sheet/],
  ["owaspSsrf", /SSRF Prevention Cheat Sheet/],
  ["nistSteganography", /NIST CSRC/],
  ["gdpr", /\bGDPR\b/],
  ["pciDss", /\bPCI[- ]DSS\b/],
  ["iso27001", /\b27001\b/],
  ["hipaa", /\bHIPAA\b/],
  ["soc2", /\bSOC ?2\b/],
  ["firstCvss", /\bCVSS\b/],
  ["nistCsf", /\bNIST CSF\b|\bCSF\b|Cybersecurity Framework/],
  ["owaspTop10", /\bOWASP\b/],
  ["mitreAttack", /ATT&CK/],
  ["nist800207", /SP ?800-207/],
  ["nist800128", /SP ?800-128/],
  ["nist8286c", /NIST IR 8286C Rev\. 1/],
  ["nist8286d", /NISTIR ?8286D/],
  ["nist80056a", /SP ?800-56A/],
  ["nist80056b", /SP ?800-56B/],
  ["nist80063b", /SP ?800-63B/],
  ["nist80061", /SP ?800-61/],
  ["nist80053", /SP ?800-53/],
  ["nist80037", /SP ?800-37/],
  ["nist80088", /SP ?800-88/],
  ["rfc8446", /RFC ?8446/],
  ["rfc9190", /RFC ?9190/],
  ["rfc5281", /RFC ?5281/],
  ["microsoftEapCertificates", /requisiti dei certificati EAP-TLS\/PEAP|EAP-TLS\/PEAP certificate requirements/],
  ["microsoftWifiProfiles", /impostazioni Wi-Fi Intune|Intune Wi-Fi settings/],
];

export const CONCEPT_CITATIONS: Partial<Record<ConceptRef, Citation[]>> = {
  "1:ThreatScopeReduction": [{ source: "nist800207" }],
  "1:RecordLevelEncryption": [{ source: "nist80053", locator: { it: "controllo SC-28", en: "control SC-28" } }],
  "2:ConfigurationEnforcement": [{ source: "nist800128" }],
  "4:PasswordVaulting": [{ source: "nist80053", locator: { it: "controlli IA-5 e AC-2", en: "controls IA-5 and AC-2" } }],
  "5:KeyRiskIndicators": [{ source: "nist8286c" }],
  "2:AcronymAppendix_ATT_CK": [{ source: "mitreAttack" }],
  "2:AcronymAppendix_OWASP": [{ source: "owaspTop10" }],
  "5:SarbanesOxleyAct": [{ source: "sox" }],
  "5:GrammLeachBlileyAct": [{ source: "glba" }, { source: "ftcSafeguards" }],
  "5:HIPAAComplianceConcept": [{ source: "hipaa" }, { source: "hipaaCovered" }, { source: "hipaaSecurity" }],
  "5:PCIDSSComplianceConcept": [{ source: "pciDss" }, { source: "pciPrograms" }],
  "1:SingleSignOn": [{ source: "samlCore" }],
  "1:SAML": [{ source: "samlCore" }],
  "1:OAuth2": [{ source: "rfc6749" }],
  "1:OpenIDConnect": [{ source: "oidcCore" }],
  "1:Kerberos": [{ source: "rfc4120" }],

  "2:DomainHijackingAttack": [{ source: "icannHijacking" }, { source: "icannProtection" }, { source: "icannLocks" }, { source: "rfc4033" }],
  "2:WiFiJammingAttack": [{ source: "ieee80211" }, { source: "wifiAlliance" }],
  "2:WiFiDeauthAttack": [{ source: "ieee80211" }, { source: "wifiAlliance" }],
  "3:ProtectedManagementFrames": [{ source: "ieee80211" }, { source: "wifiAlliance" }],
  "2:SessionHijackingAttack": [{ source: "owaspSession" }],
  "2:ReplayAttack": [{ source: "owaspSession" }, { source: "nist80063b" }],
  "2:CookieHeaderTampering": [{ source: "owaspSession" }, { source: "mdnCookies" }],
  "2:XSSAttack": [{ source: "owaspXss" }],
  "2:CSRFAttack": [{ source: "owaspCsrf" }],
  "2:SSRFAttack": [{ source: "owaspSsrf" }],
  "1:SteganographyConcept": [{ source: "nistSteganography" }],
  "1:GapAnalysis": [{ source: "pciDss" }, { source: "iso27001" }, { source: "hipaa" }, { source: "nistCsf" }],
  "1:PolicyEngineZTA": [{ source: "nist800207", locator: { it: "Sezione 3: componenti logici", en: "Section 3: logical components" } }],
  "1:PolicyAdministratorZTA": [{ source: "nist800207", locator: { it: "Sezione 3: componenti logici", en: "Section 3: logical components" } }],
  "1:PolicyEnforcementPointZTA": [{ source: "nist800207", locator: { it: "Sezione 3: componenti logici", en: "Section 3: logical components" } }],
  "1:DataPlaneZTA": [{ source: "nist800207", locator: { it: "Sezione 3: componenti logici", en: "Section 3: logical components" } }],
  "1:ZeroTrustIntro": [{ source: "nist800207" }],
  "1:DirectiveControl": [{ source: "gdpr" }, { source: "pciDss" }],
  "1:ImpactAnalysis": [{ source: "gdpr" }, { source: "hipaa" }],
  "1:SessionKeyConcept": [{ source: "nist80056a" }, { source: "rfc8446" }],
  "1:KeyTransportConcept": [{ source: "nist80056b" }, { source: "rfc8446" }],
  "1:KeyAgreementConcept": [{ source: "nist80056a" }, { source: "rfc8446" }],
  "1:DiffieHellmanConcept": [{ source: "nist80056a" }, { source: "rfc8446" }],
  "1:ECDHConcept": [{ source: "nist80056a" }, { source: "rfc8446" }],
  "1:EphemeralKeyConcept": [{ source: "nist80056a" }, { source: "rfc8446" }],
  "1:ForwardSecrecyConcept": [{ source: "nist80056a" }, { source: "rfc8446" }],
  "1:AsymmetricEncryption": [{ source: "nist80056a" }],
  "1:PasswordPoliciesAccount": [{ source: "nist80063b" }],
  "1:MFAImplementationsTokens": [{ source: "nist80063b" }],
  "2:CVSSVuln": [{ source: "firstCvss" }],
  "2:LegacyEOLVuln": [{ source: "ciscoEolPolicy" }],
  "3:PaaSCloud": [{ source: "owaspTop10" }],
  "3:TLSTerminationOffload": [{ source: "rfc8446" }],
  "3:EAP-TLS": [{ source: "rfc9190" }, { source: "microsoftEapCertificates" }],
  "3:EAP-TTLS": [{ source: "rfc5281" }],
  "3:PEAP": [{ source: "microsoftEapCertificates" }, { source: "microsoftWifiProfiles" }],
  "3:SaaSCloud": [{ source: "iso27001" }, { source: "soc2" }],
  "3:APIArchitecture": [{ source: "owaspTop10" }],
  "3:WAFFire": [{ source: "owaspTop10" }],
  "3:DataTypesConcept": [{ source: "gdpr" }, { source: "pciDss" }, { source: "hipaa" }],
  "3:TokenizationSec": [{ source: "pciDss" }],
  "3:DataMaskingSec": [{ source: "gdpr" }],
  "3:BackupEncryptionRes": [{ source: "gdpr" }, { source: "pciDss" }],
  "4:CISBenchmarkRes": [{ source: "pciDss" }, { source: "hipaa" }],
  "4:CVSS": [{ source: "firstCvss" }],
  "4:PatchAvailabilityConcept": [{ source: "firstCvss" }],
  "4:VulnerabilityAssessmentConcept": [{ source: "firstCvss" }],
  "4:PackageMonitoringRes": [{ source: "firstCvss" }],
  "4:VulnerabilityScannerRes": [{ source: "firstCvss" }],
  "4:SCAP": [{ source: "firstCvss" }],
  "4:PreparationPhase": [{ source: "gdpr", locator: { it: "art. 33 e art. 34", en: "Art. 33 and Art. 34" } }],
  "4:IncidentResponseGeneralConcept": [{ source: "nist80061" }],
  "4:ThreatHuntingIR": [{ source: "mitreAttack" }],
  "4:LegalHoldForensics": [{ source: "gdpr", locator: { it: "art. 17, par. 3, lett. e", en: "Art. 17(3)(e)" } }],
  "5:DataRolesGovernance": [{ source: "gdpr", locator: { it: "art. 24 e artt. 37–39", en: "Art. 24 and Arts. 37–39" } }],
  "5:RiskAppetite": [{ source: "pciDss" }],
  "5:OrganizationalImpactRes": [{ source: "gdpr" }],
  "5:Transfer": [{ source: "gdpr", locator: { it: "art. 33 e art. 83", en: "Art. 33 and Art. 83" } }],
  "5:RiskTransferConcept": [{ source: "gdpr", locator: { it: "art. 33 e art. 83", en: "Art. 33 and Art. 83" } }],
  "5:Compliance": [{ source: "sox" }, { source: "glba" }, { source: "gdpr" }, { source: "pciDss" }, { source: "hipaa" }],
  "5:DueDiligence": [{ source: "iso27001" }, { source: "soc2" }],
  "5:GDPRComplianceConcept": [{ source: "gdpr", locator: { it: "art. 3, par. 2, e art. 83, par. 5", en: "Art. 3(2) and Art. 83(5)" } }],
  "5:DataSovereigntyConcept": [{ source: "gdpr", locator: { it: "art. 3 e artt. 44–49", en: "Art. 3 and Arts. 44–49" } }],
  "5:NISTRes": [{ source: "nistCsf" }, { source: "nist80053" }, { source: "nist80037" }],
  "5:VendorAssessment": [{ source: "iso27001" }, { source: "soc2" }],
  "5:Questionnaires": [{ source: "soc2" }],
  "5:RightToAuditClause": [{ source: "gdpr" }, { source: "pciDss" }, { source: "iso27001" }, { source: "soc2" }],
  "5:VendorMonitoring": [{ source: "iso27001" }, { source: "soc2" }],
  "5:InternalAudit": [{ source: "iso27001" }],
  "5:ExternalAudit": [{ source: "iso27001" }, { source: "soc2" }],
  "5:RegulatoryAudit": [{ source: "gdpr", locator: { it: "art. 58 e art. 83, par. 5", en: "Art. 58 and Art. 83(5)" } }, { source: "hipaa" }],
  "5:ReportingRes": [{ source: "firstCvss" }],
  "5:AttestationConcept": [{ source: "iso27001" }, { source: "soc2" }],
  "5:SelfAssessmentConcept": [{ source: "nistCsf" }, { source: "iso27001" }],
  "5:MediaSanitizationRes": [{ source: "nist80088" }],
  "5:CertificateOfDestructionRes": [{ source: "nist80088" }],
  "5:DataRetentionRes": [{ source: "gdpr", locator: { it: "art. 17", en: "Art. 17" } }],
};
