import type { Question } from "./types";
import type { QuestionOverride } from "./data.en";

/** Original applied questions for Roadmap task 30. */
export const IAM_HARDENING_COMPLIANCE_QUESTIONS: Record<number, Question[]> = {
  4: [
    {
      id: 9020, topic: "Identity & Access Management", level: "ANALISI",
      scenario: "Un'app mobile deve far accedere l'utente tramite l'identity provider aziendale e poi chiamare un'API di profilo. Il team vuole distinguere la prova dell'autenticazione dal permesso concesso all'app per usare l'API.",
      question: "Quale combinazione assegna correttamente i due artefatti?",
      options: ["OIDC fornisce l'ID token per l'identità; OAuth 2.0 fornisce l'access token con scope per l'API", "OAuth 2.0 autentica da solo l'utente; l'ID token autorizza ogni API", "SAML trasforma automaticamente l'asserzione XML in un access token OAuth", "Il refresh token prova l'identità dell'utente direttamente al resource server"],
      answerIndex: 0,
      explanation: "OpenID Connect aggiunge a OAuth 2.0 un livello di identità: l'ID token consente al client di verificare l'autenticazione dell'utente, dopo i controlli su firma, issuer, audience, scadenza e nonce quando previsto. L'access token OAuth autorizza invece operazioni sul resource server secondo gli scope. OAuth da solo non è un protocollo di autenticazione, e ID token, asserzione SAML e refresh token non sono sostituti intercambiabili dell'access token API."
    },
    {
      id: 9021, topic: "Identity & Access Management", level: "APPLICAZIONE",
      scenario: "Un servizio di stampa fotografica vuole permettere a un'app esterna di leggere soltanto un album cloud scelto dall'utente. L'app non deve conoscere la password né ottenere il diritto di modificare o cancellare le altre foto; non serve creare una sessione SSO nell'app.",
      question: "Quale meccanismo soddisfa meglio il requisito?",
      options: ["OAuth 2.0 con consenso e access token limitato allo scope di lettura dell'album", "SAML, usando l'asserzione di identità come autorizzazione illimitata alle API", "OIDC, usando l'ID token come permesso di cancellazione delle foto", "LDAP bind, consegnando all'app le credenziali dell'utente"],
      answerIndex: 0,
      explanation: "OAuth 2.0 è progettato per l'autorizzazione delegata: il resource owner concede a un client uno scope limitato senza condividere la password. Lo scenario non richiede autenticazione federata dell'utente nell'app, quindi SAML e OIDC non risolvono il bisogno principale. Un'asserzione SAML o un ID token descrivono identità/autenticazione e non vanno presentati come token API universali; LDAP bind esporrebbe le credenziali."
    },
    {
      id: 9022, topic: "System & Device Hardening", level: "ANALISI",
      scenario: "Su un server Linux, il processo web non può leggere una directory anche dopo che un amministratore ha concesso permessi DAC molto ampi con chmod. Il log AVC di SELinux mostra un diniego fra il tipo del processo e quello dei file.",
      question: "Qual è la risposta di hardening corretta?",
      options: ["Correggere etichetta o policy SELinux in base al flusso autorizzato, mantenendo la modalità enforcing", "Disabilitare SELinux perché i permessi Unix devono avere sempre priorità", "Attivare UAC per isolare il processo Linux in una sandbox", "Lasciare SELinux permanentemente in permissive, così il MAC continua a bloccare"],
      answerIndex: 0,
      explanation: "SELinux applica Mandatory Access Control sopra i permessi discrezionali Unix: entrambi i controlli devono consentire l'operazione. Un chmod permissivo non supera un diniego di type enforcement. La soluzione è verificare il contesto previsto e correggere etichetta o regola minima necessaria, non spegnere il controllo. Permissive registra ma non blocca; UAC è un meccanismo Windows di elevazione e non una sandbox Linux."
    },
    {
      id: 9023, topic: "System & Device Hardening", level: "APPLICAZIONE",
      scenario: "Su Windows, un'applicazione scaricata chiede tramite UAC di essere eseguita con privilegi amministrativi. Il responsabile sostiene che approvare il prompt sia sicuro perché UAC eseguirà comunque l'app in una sandbox isolata dal sistema.",
      question: "Quale valutazione è corretta?",
      options: ["L'affermazione è falsa: UAC separa il token standard dall'elevazione, ma un consenso approvato può far eseguire il codice con privilegi elevati", "L'affermazione è vera: UAC è un modello MAC equivalente a SELinux", "L'affermazione è vera: ogni processo elevato perde automaticamente accesso a file e registro", "UAC autentica la firma dell'app e garantisce che il codice non sia malevolo"],
      answerIndex: 0,
      explanation: "UAC riduce l'uso implicito dei privilegi amministrativi e richiede consenso o credenziali per l'elevazione; non confina automaticamente l'app in una sandbox. Se l'utente approva codice malevolo, quel codice può agire con il token elevato. UAC non è SELinux/MAC, non garantisce la firma o la benignità dell'eseguibile e non nega per definizione l'accesso alle risorse amministrative."
    },
    {
      id: 9024, topic: "Asset Management", level: "ANALISI",
      scenario: "La policy di un produttore definisce EOL come l'intero ciclo di dismissione, EOS come la data dopo cui il prodotto non è più ordinabile e LDOS come l'ultimo giorno di assistenza contrattuale. Un prodotto raggiunge EOS oggi, ma la manutenzione programmata continua per altri due anni.",
      question: "Quale decisione interpreta correttamente le date?",
      options: ["Avviare la migrazione secondo il calendario, ma non dichiarare cessate oggi patch e assistenza: fanno fede le ulteriori scadenze pubblicate", "Considerare EOS sempre sinonimo universale di fine supporto e isolare subito il prodotto come non supportato", "Ignorare l'avviso EOL finché non compare una vulnerabilità sfruttata", "Assumere che EOL garantisca patch illimitate fino a quando il prodotto resta installato"],
      answerIndex: 0,
      explanation: "Le sigle del ciclo di vita dipendono dalla policy dichiarata dal produttore. Nel caso descritto EOS termina le vendite, non la manutenzione prevista per i due anni successivi; EOL nomina il processo complessivo e LDOS chiude l'assistenza contrattuale. L'organizzazione deve inventariare prodotto, versione, contratto e date, pianificare la sostituzione e non anticipare né estendere arbitrariamente gli impegni del vendor."
    },
    {
      id: 9025, topic: "Asset Management", level: "APPLICAZIONE",
      scenario: "Un dispositivo clinico non può essere sostituito prima di diciotto mesi. La manutenzione ordinaria del software è terminata, ma un contratto di supporto esteso copre fino a una data precisa solo assistenza e aggiornamenti espressamente elencati.",
      question: "Quale piano gestisce correttamente il rischio residuo?",
      options: ["Verificare l'ambito del contratto, pianificare la migrazione prima della scadenza e applicare segmentazione, allowlisting, monitoraggio e virtual patching dove appropriato", "Definire il prodotto pienamente supportato per qualsiasi vulnerabilità finché esiste un contratto", "Posticipare indefinitamente la migrazione perché il supporto esteso riapre la manutenzione ordinaria", "Collegare il dispositivo direttamente a Internet per ricevere eventuali patch eccezionali"],
      answerIndex: 0,
      explanation: "Il supporto esteso vale soltanto per durata e servizi dichiarati: non garantisce ogni correzione né riapre automaticamente la manutenzione ordinaria. Occorre verificare copertura e responsabilità, migrare prima della scadenza e ridurre nel frattempo l'esposizione con controlli compensativi. Segmentazione, allowlisting, monitoraggio e virtual patching riducono il rischio, ma non rendono il prodotto nuovamente supportato."
    }
  ],
  5: [
    {
      id: 9020, topic: "Compliance, Privacy, Due Diligence & Due Care", level: "ANALISI",
      scenario: "Il gruppo comprende una società quotata che deve attestare i controlli sul reporting finanziario e una società di mutui non bancaria che raccoglie informazioni finanziarie personali dei clienti. Il team vorrebbe applicare un solo quadro a entrambe.",
      question: "Quale associazione riflette meglio l'ambito dei due obblighi?",
      options: ["SOX per reporting finanziario e controlli interni dell'emittente; GLBA e Safeguards Rule per le informazioni dei clienti dell'istituzione finanziaria soggetta", "GLBA per i bilanci della società quotata; SOX per ogni dato personale della società di mutui", "HIPAA per entrambe, perché ogni informazione finanziaria è anche sanitaria", "PCI DSS per entrambe, perché sostituisce tutte le leggi federali"],
      answerIndex: 0,
      explanation: "L'applicabilità dipende dall'entità, dall'attività e dai dati. SOX riguarda gli emittenti nel perimetro SEC e l'affidabilità del reporting finanziario e dei relativi controlli interni. GLBA e le regole del regolatore competente, inclusa la FTC Safeguards Rule per le istituzioni sotto la sua giurisdizione, tutelano informazioni finanziarie non pubbliche dei clienti. Nessuno dei due quadri si applica automaticamente a ogni azienda o sostituisce gli altri."
    },
    {
      id: 9021, topic: "Compliance, Privacy, Due Diligence & Due Care", level: "APPLICAZIONE",
      scenario: "Un fornitore cloud conserva ePHI per conto di una clinica tramite un accordo da business associate e ospita anche un ambiente che può influire sulla sicurezza dei dati delle carte usato per i pagamenti dei pazienti.",
      question: "Quale valutazione evita di confondere legge e standard di settore?",
      options: ["HIPAA può applicarsi al fornitore come business associate; PCI DSS può applicarsi al cardholder data environment, ma è uno standard di settore e non una legge", "Si applica solo HIPAA, perché la presenza di dati sanitari annulla PCI DSS", "Si applica solo PCI DSS, che trasforma il fornitore in covered entity HIPAA", "Nessuno dei due si applica se la clinica ha esternalizzato l'infrastruttura"],
      answerIndex: 0,
      explanation: "HHS indica che le HIPAA Rules si applicano a covered entities e business associates quando le funzioni coinvolgono PHI/ePHI. PCI DSS è invece uno standard di settore, non una legge: riguarda entità che memorizzano, elaborano o trasmettono dati di carta o possono influire sulla sicurezza del CDE. I due ambiti possono sovrapporsi; l'outsourcing non elimina automaticamente responsabilità o applicabilità e PCI DSS non crea lo status HIPAA."
    }
  ]
};

export const IAM_HARDENING_COMPLIANCE_QUESTION_EN: Record<number, Record<number, QuestionOverride>> = {
  4: {
    9020: { topic: "Identity & Access Management", scenario: "A mobile app must sign a user in through the corporate identity provider and then call a profile API. The team wants to distinguish evidence of authentication from permission granted to the app to use the API.", question: "Which combination assigns the two artifacts correctly?", options: ["OIDC supplies the ID token for identity; OAuth 2.0 supplies the scoped access token for the API", "OAuth 2.0 authenticates the user by itself; the ID token authorizes every API", "SAML automatically converts its XML assertion into an OAuth access token", "The refresh token proves the user's identity directly to the resource server"], explanation: "OpenID Connect adds an identity layer to OAuth 2.0: the ID token lets the client verify user authentication after checking signature, issuer, audience, expiration, and nonce where applicable. The OAuth access token instead authorizes operations at the resource server according to scopes. OAuth alone is not an authentication protocol, and ID tokens, SAML assertions, and refresh tokens are not interchangeable substitutes for API access tokens." },
    9021: { topic: "Identity & Access Management", scenario: "A photo-printing service wants to let an external app read only one cloud album selected by the user. The app must not learn the password or gain rights to modify or delete other photos; it does not need to create an SSO session for the user.", question: "Which mechanism best meets the requirement?", options: ["OAuth 2.0 with consent and an access token limited to the album's read scope", "SAML, using the identity assertion as unlimited API authorization", "OIDC, using the ID token as permission to delete photos", "An LDAP bind that gives the app the user's credentials"], explanation: "OAuth 2.0 is designed for delegated authorization: a resource owner grants a client limited scope without sharing a password. The scenario does not require federated user authentication in the app, so SAML and OIDC do not address the primary need. A SAML assertion or ID token describes identity/authentication and should not be presented as a universal API token; LDAP bind would expose credentials." },
    9022: { topic: "System & Device Hardening", scenario: "On a Linux server, the web process cannot read a directory even after an administrator grants very broad DAC permissions with chmod. The SELinux AVC log shows a denial between the process type and the file type.", question: "What is the correct hardening response?", options: ["Correct the SELinux label or policy for the authorized flow while keeping enforcing mode", "Disable SELinux because Unix permissions must always take priority", "Enable UAC to isolate the Linux process in a sandbox", "Leave SELinux permanently permissive so MAC continues to block"], explanation: "SELinux applies Mandatory Access Control on top of discretionary Unix permissions: both checks must allow the operation. A permissive chmod does not override a type-enforcement denial. The fix is to verify the intended context and correct the label or minimum necessary rule, not disable the control. Permissive mode logs but does not block; UAC is a Windows elevation mechanism, not a Linux sandbox." },
    9023: { topic: "System & Device Hardening", scenario: "On Windows, a downloaded application asks through UAC to run with administrative privileges. The manager claims approval is safe because UAC will still run the app in a sandbox isolated from the system.", question: "Which assessment is correct?", options: ["The claim is false: UAC separates the standard token from elevation, but approved consent can run the code with elevated privileges", "The claim is true: UAC is a MAC model equivalent to SELinux", "The claim is true: every elevated process automatically loses access to files and registry", "UAC authenticates the app's signature and guarantees the code is benign"], explanation: "UAC reduces implicit use of administrative privileges and requires consent or credentials for elevation; it does not automatically confine the app in a sandbox. If the user approves malicious code, that code can act with the elevated token. UAC is not SELinux/MAC, does not guarantee the executable's signature or safety, and does not inherently deny access to administrative resources." },
    9024: { topic: "Asset Management", scenario: "A vendor policy defines EOL as the whole retirement process, EOS as the date after which the product can no longer be ordered, and LDOS as the last day of contract support. A product reaches EOS today, but scheduled maintenance continues for two more years.", question: "Which decision interprets the dates correctly?", options: ["Begin migration according to the timeline, but do not claim patches and support end today: the additional published milestones control", "Always treat EOS as a universal synonym for end of support and isolate the product immediately as unsupported", "Ignore the EOL notice until an exploited vulnerability appears", "Assume EOL guarantees unlimited patches while the product remains installed"], explanation: "Lifecycle acronyms depend on the vendor's declared policy. In this case EOS ends sales, not maintenance scheduled for two more years; EOL names the overall process and LDOS closes contract support. The organization must inventory product, version, contract, and dates, plan replacement, and neither shorten nor extend the vendor's commitments arbitrarily." },
    9025: { topic: "Asset Management", scenario: "A clinical device cannot be replaced for eighteen months. Ordinary software maintenance has ended, but an extended-support contract runs until a fixed date and covers only expressly listed assistance and updates.", question: "Which plan correctly manages residual risk?", options: ["Verify contract scope, plan migration before expiry, and apply segmentation, allowlisting, monitoring, and virtual patching where appropriate", "Call the product fully supported for every vulnerability as long as any contract exists", "Delay migration indefinitely because extended support reopens ordinary maintenance", "Connect the device directly to the Internet to receive any exceptional patches"], explanation: "Extended support is only as broad and as long as declared; it does not guarantee every fix or automatically reopen ordinary maintenance. The organization should verify coverage and responsibilities, migrate before expiry, and reduce exposure meanwhile with compensating controls. Segmentation, allowlisting, monitoring, and virtual patching reduce risk but do not make the product supported again." }
  },
  5: {
    9020: { topic: "Compliance, Privacy, Due Diligence & Due Care", scenario: "A group includes a listed company that must attest controls over financial reporting and a non-bank mortgage company that collects customers' personal financial information. The team wants to apply one framework to both.", question: "Which association best reflects the scope of the two obligations?", options: ["SOX for the issuer's financial reporting and internal controls; GLBA and the Safeguards Rule for customer information at the covered financial institution", "GLBA for the listed company's financial statements; SOX for every item of personal data at the mortgage company", "HIPAA for both because every financial record is also health information", "PCI DSS for both because it replaces all federal laws"], explanation: "Applicability depends on the entity, activity, and data. SOX concerns issuers in SEC scope and reliable financial reporting and related internal controls. GLBA and the relevant regulator's rules, including the FTC Safeguards Rule for institutions under its jurisdiction, protect customers' nonpublic financial information. Neither framework automatically applies to every company or replaces the others." },
    9021: { topic: "Compliance, Privacy, Due Diligence & Due Care", scenario: "A cloud provider stores ePHI for a clinic under a business-associate agreement and also hosts an environment that can affect the security of card data used for patient payments.", question: "Which assessment avoids confusing law and an industry standard?", options: ["HIPAA may apply to the provider as a business associate; PCI DSS may apply to the cardholder data environment, but it is an industry standard rather than a law", "Only HIPAA applies because health data cancels PCI DSS", "Only PCI DSS applies, and it turns the provider into a HIPAA covered entity", "Neither applies once the clinic outsources infrastructure"], explanation: "HHS states that the HIPAA Rules apply to covered entities and business associates when functions involve PHI/ePHI. PCI DSS is an industry standard, not a law: it concerns entities that store, process, or transmit card data or can affect CDE security. The scopes can overlap; outsourcing does not automatically remove responsibility or applicability, and PCI DSS does not create HIPAA status." }
  }
};
