import type { Question } from "./types";
import type { QuestionOverride } from "./data.en";

/** Original applied questions for Roadmap task 29. */
export const NETWORK_CLOUD_QUESTIONS: Record<number, Question[]> = {
  3: [
    {
      id: 9015, topic: "Secure Network Protocols", level: "ANALISI",
      scenario: "Un reverse proxy pubblico termina TLS e inoltra HTTP in chiaro al server applicativo su una VLAN condivisa. Un nuovo requisito impone riservatezza e autenticazione del server su ogni tratto, incluso quello interno.",
      question: "Quale modifica soddisfa integralmente il requisito?",
      options: ["Ri-cifrare dal proxy al backend con TLS e validare il certificato e il nome del backend", "Installare un certificato pubblico più lungo solo sul proxy", "Abilitare HSTS sul browser senza modificare il tratto interno", "Spostare il backend su una porta TCP diversa"],
      answerIndex: 0,
      explanation: "Il TLS del client termina sul proxy: il segmento successivo è una nuova connessione e deve essere protetto separatamente. Ri-cifrare e validare certificato, catena e identità del backend offre riservatezza e autenticazione anche sul tratto interno. HSTS protegge il collegamento browser-proxy, mentre lunghezza del certificato e cambio di porta non cifrano la VLAN."
    },
    {
      id: 9016, topic: "Network Security Devices", level: "APPLICAZIONE",
      scenario: "Un load balancer deve ispezionare richieste HTTPS e applicare il WAF, ma la policy vieta traffico applicativo in chiaro fra zone. Il team propone il TLS passthrough per evitare di custodire chiavi sul bilanciatore.",
      question: "Quale progetto mantiene sia l'ispezione sia la protezione dei due segmenti?",
      options: ["Terminare TLS sul load balancer, proteggervi la chiave e aprire una seconda sessione TLS verificata verso il backend", "Usare passthrough e chiedere comunque al WAF sul load balancer di leggere il payload cifrato", "Terminare TLS e inoltrare HTTP perché la rete è interna", "Disabilitare la verifica del certificato backend per evitare errori operativi"],
      answerIndex: 0,
      explanation: "Per ispezionare il payload il load balancer deve terminare la prima sessione TLS, quindi diventa un confine di fiducia e deve proteggere la chiave, idealmente con un HSM. Una seconda sessione TLS, con validazione del backend, protegge la zona interna. Il passthrough conserva la cifratura end-to-end ma impedisce quell'ispezione; HTTP interno e verifica disabilitata violano il requisito."
    },
    {
      id: 9017, topic: "Infrastructure Segmentations & Topologies", level: "APPLICAZIONE",
      scenario: "Quaranta filiali usano MPLS, banda larga e 5G. L'obiettivo immediato è scegliere dinamicamente il collegamento con latenza e perdita migliori per ogni applicazione; firewall e servizi cloud di sicurezza sono già gestiti separatamente.",
      question: "Quale soluzione risponde meglio al requisito senza attribuirle funzioni non richieste?",
      options: ["SD-WAN, per selezione dei percorsi e gestione programmabile della WAN", "SASE, perché ogni SD-WAN include necessariamente CASB e SWG", "CASB, per instradare il traffico voce sul link meno congestionato", "SWG, per aggregare MPLS e 5G"],
      answerIndex: 0,
      explanation: "SD-WAN affronta connettività, misurazione dei link e scelta del percorso per applicazione. SASE converge networking e servizi di sicurezza, ma sarebbe una risposta più ampia del requisito e il suo catalogo varia. CASB governa uso e dati delle applicazioni cloud; SWG filtra traffico web. Nessuno dei due sostituisce l'ottimizzazione WAN."
    },
    {
      id: 9018, topic: "Network Security Devices", level: "ANALISI",
      scenario: "L'azienda blocca già siti malevoli con uno SWG. Ora deve scoprire SaaS non approvati, classificare i dati già archiviati in tali servizi e impedire la condivisione pubblica tramite API, senza sostituire il filtro web.",
      question: "Quale componente va aggiunto, e perché non basta chiamare l'intera soluzione SASE?",
      options: ["CASB, perché governa app e dati SaaS; SASE è un'architettura il cui catalogo effettivo va verificato", "SD-WAN, perché analizza via API i file già presenti nel SaaS", "Un secondo SWG, perché il filtraggio URL equivale alla governance dei dati SaaS", "FWaaS, perché ogni firewall cloud include necessariamente controlli CASB"],
      answerIndex: 0,
      explanation: "Il requisito riguarda shadow IT, configurazioni, sessioni e dati dentro applicazioni SaaS: è il ruolo del CASB, incluse modalità API. Lo SWG resta pertinente al canale web ma non governa automaticamente i dati già nel servizio. SASE può integrare CASB e SWG, tuttavia il nome dell'architettura non garantisce che ogni capacità sia acquistata, configurata o disponibile."
    }
  ],
  4: [
    {
      id: 9015, topic: "Wireless Security", level: "ANALISI",
      scenario: "Dopo l'attivazione di PMF, i frame di deautenticazione contraffatti non disconnettono più i client. Durante un nuovo incidente, però, tutti i canali a 5 GHz mostrano rumore continuo e i dispositivi non riescono comunque a trasmettere.",
      question: "Qual è la diagnosi più corretta?",
      options: ["Jamming RF al livello fisico: PMF autentica frame di gestione ma non rende disponibile la portante radio", "PMF è guasto, perché dovrebbe eliminare ogni forma di indisponibilità Wi-Fi", "Attacco SAE offline, risolvibile passando a WPA2-Personal", "Errore del server RADIUS, perché il rumore radio dipende da EAP"],
      answerIndex: 0,
      explanation: "PMF protegge frame robusti di gestione, contrastando spoofing di deautenticazione e disassociazione, ma non può impedire a una sorgente di saturare lo spettro radio. Rumore continuo su più canali indica interferenza o jamming da localizzare con analisi dello spettro. SAE, WPA2 e RADIUS riguardano autenticazione o chiavi e non ripristinano una portante fisica indisponibile."
    },
    {
      id: 9016, topic: "Wireless Security", level: "APPLICAZIONE",
      scenario: "Una rete governativa richiede autenticazione individuale con certificati client, PMF obbligatorio e la suite di sicurezza WPA3-Enterprise a 192 bit. Il team nota che l'attuale profilo è soltanto WPA3-Enterprise standard.",
      question: "Quale decisione rispetta il requisito senza confondere le due modalità?",
      options: ["Configurare esplicitamente WPA3-Enterprise 192-bit con 802.1X/EAP-TLS e verificare compatibilità di client e infrastruttura", "Lasciare WPA3-Enterprise standard: la suite a 192 bit è implicita in ogni configurazione WPA3", "Passare a WPA3-Personal con SAE, che fornisce certificati individuali", "Usare OWE, perché autentica ogni dipendente senza credenziali"],
      answerIndex: 0,
      explanation: "La modalità WPA3-Enterprise a 192 bit è una suite distinta e va configurata e supportata esplicitamente; non è implicita in ogni rete WPA3-Enterprise. EAP-TLS soddisfa l'autenticazione individuale a certificati e PMF è richiesto da WPA3. SAE usa una credenziale Personal condivisa, mentre OWE cifra reti aperte senza autenticare l'identità dell'utente."
    },
    {
      id: 9017, topic: "Wireless Security", level: "ANALISI",
      scenario: "Un profilo PEAP aziendale accetta qualunque certificato presentato dal server RADIUS. Un access point malevolo usa un proprio certificato valido per un altro nome e induce alcuni client a iniziare l'autenticazione.",
      question: "Quale correzione elimina la fiducia eccessiva che rende possibile l'attacco?",
      options: ["Distribuire un profilo gestito che validi la CA attendibile e l'identità prevista del server RADIUS prima di inviare credenziali", "Disabilitare il certificato server, perché PEAP protegge comunque il tunnel", "Verificare soltanto che il certificato non sia scaduto, ignorando nome e catena", "Sostituire RADIUS con DHCP, mantenendo il profilo invariato"],
      answerIndex: 0,
      explanation: "Il client deve verificare sia la catena verso una CA autorizzata sia l'identità attesa del server. Un certificato valido per un altro nome non autentica il RADIUS aziendale. Il tunnel PEAP non è affidabile prima di questa verifica e il certificato server non è facoltativo. Controllare solo la scadenza o cambiare DHCP non corregge la fiducia nell'evil twin."
    },
    {
      id: 9018, topic: "Wireless Security", level: "APPLICAZIONE",
      scenario: "Un'organizzazione non può ancora distribuire certificati client, ma vuole autenticare gli utenti con password solo dentro un tunnel TLS e imporre ai dispositivi un profilo che convalidi il certificato del server.",
      question: "Quale metodo EAP è coerente con questi vincoli, e quale differenza rispetto a EAP-TLS resta essenziale?",
      options: ["PEAP: usa credenziali interne protette dal tunnel; EAP-TLS richiede invece certificati client e server", "EAP-TLS: usa solo password e non richiede un certificato client", "LEAP: offre la stessa protezione del tunnel TLS con algoritmi moderni", "WPS: trasporta la password utente dentro un tunnel autenticato"],
      answerIndex: 0,
      explanation: "PEAP crea un tunnel TLS autenticato dal certificato del server e può trasportare credenziali utente al suo interno, quindi si adatta al vincolo senza PKI client. EAP-TLS realizza autenticazione reciproca con certificati anche sul client. La validazione del server resta obbligatoria in entrambi i disegni pertinenti; LEAP è legacy e WPS non è un metodo EAP aziendale."
    }
  ]
};

export const NETWORK_CLOUD_QUESTION_EN: Record<number, Record<number, QuestionOverride>> = {
  3: {
    9015: { topic: "Secure Network Protocols", scenario: "A public reverse proxy terminates TLS and forwards cleartext HTTP to the application server across a shared VLAN. A new requirement mandates confidentiality and server authentication on every leg, including the internal one.", question: "Which change fully meets the requirement?", options: ["Re-encrypt from the proxy to the backend with TLS and validate the backend certificate and name", "Install a longer public certificate only on the proxy", "Enable HSTS in the browser without changing the internal leg", "Move the backend to a different TCP port"], explanation: "Client TLS ends at the proxy, so the next leg is a new connection that must be protected separately. Re-encryption plus validation of the backend certificate, chain, and identity provides confidentiality and authentication on the internal leg. HSTS protects browser-to-proxy traffic, while certificate length and a port change do not encrypt the VLAN." },
    9016: { topic: "Network Security Devices", scenario: "A load balancer must inspect HTTPS requests and apply a WAF, but policy forbids cleartext application traffic between zones. The team proposes TLS passthrough to avoid holding keys on the balancer.", question: "Which design retains both inspection and protection of the two segments?", options: ["Terminate TLS at the load balancer, protect the key there, and open a second validated TLS session to the backend", "Use passthrough and still ask the WAF on the load balancer to read the encrypted payload", "Terminate TLS and forward HTTP because the network is internal", "Disable backend certificate validation to avoid operational errors"], explanation: "To inspect the payload, the load balancer must terminate the first TLS session, becoming a trust boundary whose key should be protected, ideally by an HSM. A second TLS session with backend validation protects the internal zone. Passthrough preserves end-to-end encryption but prevents that inspection; internal HTTP and disabled validation violate the requirement." },
    9017: { topic: "Infrastructure Segmentations & Topologies", scenario: "Forty branches use MPLS, broadband, and 5G. The immediate goal is to dynamically choose the link with the best latency and loss for each application; firewalls and cloud security services are already managed separately.", question: "Which solution best meets the requirement without attributing unrequested functions to it?", options: ["SD-WAN, for path selection and programmable WAN management", "SASE, because every SD-WAN necessarily includes CASB and SWG", "CASB, to route voice over the least congested link", "SWG, to aggregate MPLS and 5G"], explanation: "SD-WAN addresses connectivity, link measurement, and application-aware path selection. SASE converges networking and security services, but is broader than this requirement and its service catalog varies. CASB governs cloud application use and data; SWG filters web traffic. Neither replaces WAN optimization." },
    9018: { topic: "Network Security Devices", scenario: "The company already blocks malicious sites with an SWG. It now needs to discover unsanctioned SaaS, classify data already stored in those services, and prevent public sharing through APIs without replacing web filtering.", question: "Which component should be added, and why is calling the whole solution SASE not enough?", options: ["CASB, because it governs SaaS applications and data; SASE is an architecture whose actual service catalog must be verified", "SD-WAN, because it inspects files already stored in SaaS through APIs", "A second SWG, because URL filtering equals SaaS data governance", "FWaaS, because every cloud firewall necessarily includes CASB controls"], explanation: "The requirement concerns shadow IT, configuration, sessions, and data inside SaaS applications: that is the CASB role, including API modes. SWG remains relevant to the web channel but does not automatically govern data already in a service. SASE may integrate CASB and SWG, but the architecture name does not guarantee that every capability is purchased, configured, or available." }
  },
  4: {
    9015: { topic: "Wireless Security", scenario: "After PMF is enabled, forged deauthentication frames no longer disconnect clients. During a new incident, however, every 5 GHz channel shows continuous noise and devices still cannot transmit.", question: "What is the most accurate diagnosis?", options: ["Physical-layer RF jamming: PMF authenticates management frames but cannot make the radio carrier available", "PMF is broken because it should eliminate every form of Wi-Fi unavailability", "An offline SAE attack, fixed by reverting to WPA2-Personal", "A RADIUS server error, because radio noise depends on EAP"], explanation: "PMF protects robust management frames against forged deauthentication and disassociation, but it cannot stop a source from saturating radio spectrum. Continuous noise across channels indicates interference or jamming to locate with spectrum analysis. SAE, WPA2, and RADIUS concern authentication or keys and cannot restore an unavailable physical carrier." },
    9016: { topic: "Wireless Security", scenario: "A government network requires individual client-certificate authentication, mandatory PMF, and the 192-bit WPA3-Enterprise security suite. The team notes that the current profile is only standard WPA3-Enterprise.", question: "Which decision meets the requirement without confusing the two modes?", options: ["Explicitly configure WPA3-Enterprise 192-bit with 802.1X/EAP-TLS and verify client and infrastructure compatibility", "Keep standard WPA3-Enterprise: the 192-bit suite is implicit in every WPA3 configuration", "Move to WPA3-Personal with SAE, which provides individual certificates", "Use OWE because it authenticates every employee without credentials"], explanation: "WPA3-Enterprise 192-bit mode is a distinct suite that must be explicitly configured and supported; it is not implicit in every WPA3-Enterprise network. EAP-TLS meets individual certificate authentication and WPA3 requires PMF. SAE uses a Personal shared credential, while OWE encrypts open networks without authenticating user identity." },
    9017: { topic: "Wireless Security", scenario: "A corporate PEAP profile accepts any certificate presented by the RADIUS server. A malicious access point uses its own certificate valid for another name and causes some clients to start authentication.", question: "Which correction removes the excessive trust that enables the attack?", options: ["Deploy a managed profile that validates the trusted CA and expected RADIUS server identity before sending credentials", "Disable the server certificate because PEAP protects the tunnel anyway", "Check only that the certificate is not expired while ignoring name and chain", "Replace RADIUS with DHCP while keeping the profile unchanged"], explanation: "The client must verify both the chain to an authorized CA and the expected server identity. A certificate valid for another name does not authenticate the corporate RADIUS server. The PEAP tunnel is not trustworthy before this check, and the server certificate is not optional. Checking only expiry or changing DHCP does not fix trust in an evil twin." },
    9018: { topic: "Wireless Security", scenario: "An organization cannot yet deploy client certificates, but it wants to authenticate users with passwords only inside a TLS tunnel and enforce a device profile that validates the server certificate.", question: "Which EAP method fits these constraints, and which difference from EAP-TLS remains essential?", options: ["PEAP: it carries inner credentials protected by the tunnel; EAP-TLS instead requires client and server certificates", "EAP-TLS: it uses passwords only and requires no client certificate", "LEAP: it provides the same modern TLS tunnel protection", "WPS: it carries the user password inside an authenticated tunnel"], explanation: "PEAP builds a TLS tunnel authenticated by the server certificate and can carry user credentials inside it, fitting the no-client-PKI constraint. EAP-TLS provides mutual authentication with a certificate on the client too. Server validation remains mandatory in both relevant designs; LEAP is legacy and WPS is not an enterprise EAP method." }
  }
};
