/**
 * Maps a subtopic `checklistKey` to the display name of the thematic subgroup it
 * belongs to. Subtopics that share a subgroup are rendered together as a single
 * unified study card. A key with no entry here is rendered standalone.
 *
 * Subgroup names are Italian (the source language); `localizeSubgroup()` in
 * `i18n.tsx` translates them for display.
 */
export const SUBGROUP_MAP: Record<string, string> = {
  // Domain 1
  "CIATriad": "Principi Fondamentali (CIA, AAA, Non-Repudio)",
  "AAAFramework": "Principi Fondamentali (CIA, AAA, Non-Repudio)",
  "NonRepudiation": "Principi Fondamentali (CIA, AAA, Non-Repudio)",
  "GapAnalysis": "Analisi Postura e Gap",
  "ZeroTrustIntro": "Zero Trust Architecture (ZTA)",
  "PolicyDrivenAccessControl": "Zero Trust Architecture (ZTA)",
  "ControlPlaneZTA": "Zero Trust Architecture (ZTA)",
  "ImplicitTrustZones": "Zero Trust Architecture (ZTA)",
  "DataPlaneZTA": "Zero Trust Architecture (ZTA)",
  "TechnicalControls": "Categorie di Controlli (Implementazione)",
  "OperationalControls": "Categorie di Controlli (Implementazione)",
  "ManagerialControls": "Categorie di Controlli (Implementazione)",
  "PhysicalControls": "Categorie di Controlli (Implementazione)",
  "PreventiveControl": "Tipi di Controlli (In base alla Funzione)",
  "DetectiveControl": "Tipi di Controlli (In base alla Funzione)",
  "CorrectiveControl": "Tipi di Controlli (In base alla Funzione)",
  "DeterrentControl": "Tipi di Controlli (In base alla Funzione)",
  "CompensatingControl": "Tipi di Controlli (In base alla Funzione)",
  "DirectiveControl": "Tipi di Controlli (In base alla Funzione)",
  "ApprovalProcess": "Processi di Change Management",
  "ImpactAnalysis": "Processi di Change Management",
  "BackoutPlan": "Processi di Change Management",
  "MaintenanceWindow": "Processi di Change Management",
  "VersionControl": "Processi di Change Management",
  
  // Topic 5: Cryptography
  "SymmetricEncryption": "Crittografia",
  "AsymmetricEncryption": "Crittografia",
  "HashingConcept": "Crittografia",
  "PKIFundamentals": "Infrastruttura PKI",
  "RootOfTrustConcept": "Infrastruttura PKI",
  "CertificateAuthorityConcept": "Infrastruttura PKI",
  "RegistrationAuthorityConcept": "Infrastruttura PKI",
  "PublicKeyConcept": "Infrastruttura PKI",
  "PrivateKeyConcept": "Infrastruttura PKI",
  "CSRConcept": "Infrastruttura PKI",
  "CertificatesConcept": "Infrastruttura PKI",
  "WildcardCertificates": "Infrastruttura PKI",
  "SaltingConcept": "Crittografia",
  "DigitalSignaturesConcept": "Infrastruttura PKI",
  "TPMHardware": "Infrastruttura PKI",
  "HSMHardware": "Infrastruttura PKI",
  "KeyEscrowConcept": "Infrastruttura PKI",
  "BlockCipherConcept": "Crittografia",
  "AES256Concept": "Crittografia",
  "StreamCipherConcept": "Crittografia",
  "KeyStretchingConcept": "Crittografia",
  "BlockchainConcept": "Crittografia",
  "CodeSigningConcept": "Infrastruttura PKI",

  // Topic 6: Physical Security
  "PhysicalBadge": "Misure di Sicurezza Fisica",
  "SecurityGuards": "Misure di Sicurezza Fisica",
  "PhysicalCameras": "Misure di Sicurezza Fisica",
  "PhysicalFencing": "Misure di Sicurezza Fisica",
  "PhysicalBollards": "Misure di Sicurezza Fisica",
  "PhysicalSensors": "Misure di Sicurezza Fisica",

  // Topic 7: Deception Technologies
  "HoneypotDeception": "Tecnologie di Inganno (Deception)",
  "HoneynetDeception": "Tecnologie di Inganno (Deception)",
  "HoneyfileDeception": "Tecnologie di Inganno (Deception)",
  "HoneytokenDeception": "Tecnologie di Inganno (Deception)",

  // Topic 8: Identity & Access Control Models
  "AuthenticationConcept_New": "Modelli d'Identità e Federazione",
  "AuthorizationConcept_New": "Modelli di Controllo Accessi (IAM)",
  "AccountingConcept_New": "Modelli d'Identità e Federazione",
  "MFA_SSO_Federation": "Modelli d'Identità e Federazione",
  "PasswordPoliciesAccount": "Modelli d'Identità e Federazione",
  "LDAPProtocol_New": "Modelli d'Identità e Federazione",
  "AttributeBasedConcept": "Modelli di Controllo Accessi (IAM)",
  "DACConcept": "Modelli di Controllo Accessi (IAM)",
  "MACConcept": "Modelli di Controllo Accessi (IAM)",
  "MFAConcept_New": "Modelli d'Identità e Federazione",
  "FederationConcept": "Modelli d'Identità e Federazione",
  "AccessControlModels": "Modelli di Controllo Accessi (IAM)",
  "RBACConcept": "Modelli di Controllo Accessi (IAM)",
  "RuleBasedAccessControlConcept": "Modelli di Controllo Accessi (IAM)",
  "LeastPrivilegeConcept": "Modelli di Controllo Accessi (IAM)",
  "NeedToKnowConcept": "Modelli di Controllo Accessi (IAM)",
  "JustInTimeConcept": "Modelli di Controllo Accessi (IAM)",
  "JustEnoughAdministrationConcept": "Modelli di Controllo Accessi (IAM)",
  "ImplicitDenyConcept": "Modelli di Controllo Accessi (IAM)",
  "PermissionRestrictions": "Modelli di Controllo Accessi (IAM)",
  "GeographicNetworkRestrictions": "Modelli di Controllo Accessi (IAM)",

  // Domain 2
  "NationStateActor": "Profili e Attori delle Minacce",
  "InsiderThreatActor": "Profili e Attori delle Minacce",
  "OrganizedCrimeActor": "Profili e Attori delle Minacce",
  "HacktivistActor": "Profili e Attori delle Minacce",
  "ScriptKiddieActor": "Profili e Attori delle Minacce",
  "CompetitorActor": "Profili e Attori delle Minacce",
  
  "FinancialGainMotiv": "Motivazioni degli Attaccanti",
  "EspionageMotiv": "Motivazioni degli Attaccanti",
  "RevengeMotiv": "Motivazioni degli Attaccanti",
  "IdeologyMotiv": "Motivazioni degli Attaccanti",
  "ChaosMotiv": "Motivazioni degli Attaccanti",

  "ThreatVectorsDetails": "Vettori e Superfici di Attacco",
  "AttackSurfacesDetails": "Vettori e Superfici di Attacco",

  "VirusMalware": "Tipologie di Malware",
  "WormMalware": "Tipologie di Malware",
  "TrojanMalware": "Tipologie di Malware",
  "RansomwareMalware": "Tipologie di Malware",
  "RootkitMalware": "Tipologie di Malware",
  "SpywareMalware": "Tipologie di Malware",
  "KeyloggerMalware": "Tipologie di Malware",
  "LogicBombMalware": "Tipologie di Malware",

  "PhishingSE": "Ingegneria Sociale & Phishing",
  "SmishingSE": "Ingegneria Sociale & Phishing",
  "VishingSE": "Ingegneria Sociale & Phishing",
  "PretextingSE": "Ingegneria Sociale & Phishing",
  "ImpersonationSE": "Ingegneria Sociale & Phishing",
  "WateringHoleSE": "Ingegneria Sociale & Phishing",
  "TyposquattingSE": "Ingegneria Sociale & Phishing",
  "CloningSE": "Ingegneria Sociale & Phishing",
  "WhalingSE_New": "Ingegneria Sociale & Phishing",
  "MisinformationSE_New": "Ingegneria Sociale & Phishing",
  "PhishingCampaignSE_New": "Ingegneria Sociale & Phishing",

  "BruteForceAtt": "Attacchi alle Credenziali",
  "DictionaryAtt": "Attacchi alle Credenziali",
  "PasswordSprayingAtt": "Attacchi alle Credenziali",
  "CredentialStuffingAtt": "Attacchi alle Credenziali",

  "NetworkWirelessAttacks": "Attacchi Infrastrutturali & Web",
  "AppCryptoAttacks": "Attacchi Infrastrutturali & Web",
  "AmplifiedDDoS_New": "Attacchi Infrastrutturali & Web",
  "ReflectedDDoS_New": "Attacchi Infrastrutturali & Web",
  "SQLi_New": "Attacchi Infrastrutturali & Web",

  "CVEVuln": "Analisi di Vulnerabilità",
  "CVSSVuln": "Analisi di Vulnerabilità",
  "ZeroDayVuln": "Analisi di Vulnerabilità",
  "FalsePositiveVuln": "Analisi di Vulnerabilità",
  "FalseNegativeVuln": "Analisi di Vulnerabilità",

  "SegmentationMiti": "Tecniche di Mitigazione (Hardening)",
  "LeastPrivilegeMiti": "Tecniche di Mitigazione (Hardening)",
  "PatchingMiti": "Tecniche di Mitigazione (Hardening)",
  "IsolationMiti": "Tecniche di Mitigazione (Hardening)",
  "EncryptionMiti": "Tecniche di Mitigazione (Hardening)",
  "MonitoringMiti": "Tecniche di Mitigazione (Hardening)",
  "DisablePortsMiti": "Tecniche di Mitigazione (Hardening)",
  "ChangePasswordsMiti": "Tecniche di Mitigazione (Hardening)",
  "RemoveSoftwareMiti": "Tecniche di Mitigazione (Hardening)",
  "ACLMiti": "Tecniche di Mitigazione (Hardening)",
  "AppAllowListMiti": "Tecniche di Mitigazione (Hardening)",

  // Domain 3
  "OnPremisesArchitecture": "Modelli Architetturali Tradizionali",
  "CentralizedArchitecture": "Modelli Architetturali Tradizionali",
  "DecentralizedArchitecture": "Modelli Architetturali Tradizionali",
  "IaaSCloud": "Modelli di Servizio Cloud & Responsabilità",
  "PaaSCloud": "Modelli di Servizio Cloud & Responsabilità",
  "FaaSCloud": "Modelli di Servizio Cloud & Responsabilità",
  "SaaSCloud": "Modelli di Servizio Cloud & Responsabilità",
  "SharedResponsibilityCloud": "Modelli di Servizio Cloud & Responsabilità",
  "ResponsibilityMatrixConcept": "Modelli di Servizio Cloud & Responsabilità",
  
  // Under Network Security (Obj 3.2):
  "Layer1Physical": "Modello ISO/OSI (7 Livelli)",
  "Layer2DataLink": "Modello ISO/OSI (7 Livelli)",
  "Layer3Network": "Modello ISO/OSI (7 Livelli)",
  "Layer4Transport": "Modello ISO/OSI (7 Livelli)",
  "Layer5Session": "Modello ISO/OSI (7 Livelli)",
  "Layer6Presentation": "Modello ISO/OSI (7 Livelli)",
  "Layer7Application": "Modello ISO/OSI (7 Livelli)",
  "RoutersConcept": "Dispositivi di Connettività e Relay",
  "ProxyServerConcept": "Dispositivi di Connettività e Relay",
  "JumpServerConcept": "Dispositivi di Connettività e Relay",
  "NACNet": "Sicurezza & Monitoraggio degli Accessi di Rete",
  "IDSSolutionConcept": "Sicurezza & Monitoraggio degli Accessi di Rete",
  "IPS_New": "Sicurezza & Monitoraggio degli Accessi di Rete",
  "PassiveMode_New": "Sicurezza & Monitoraggio degli Accessi di Rete",
  "IPSecNet": "Protocolli di Crittografia in Transito",
  "TLSNet": "Protocolli di Crittografia in Transito",
  "SSHNet": "Protocolli di Crittografia in Transito",
  "VPNNet": "Architetture VPN",
  "SiteToSiteVPNNet": "Architetture VPN",
  "VPNGateway_New": "Architetture VPN",
  "PSKConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "WEPConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "WPAWirelessConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "TKIPConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "MICConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "WPA3Net": "Sicurezza Reti Wireless (Wi-Fi)",
  "WPA2Net": "Sicurezza Reti Wireless (Wi-Fi)",
  "GCMPConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "SAEConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "OpenSystemConcept": "Sicurezza Reti Wireless (Wi-Fi)",
  "WPA3PersonalRes": "Sicurezza Reti Wireless (Wi-Fi)",
  "WPA3EnterpriseRes": "Sicurezza Reti Wireless (Wi-Fi)",
  "WiFiBluetoothTech": "Sicurezza Reti Wireless (Wi-Fi)",
  "WirelessSurveyRes": "Sicurezza Reti Wireless (Wi-Fi)",
  "RADIUSNet": "Autenticazione di Rete Centralizzata (AAA)",
  "EAPProtocol_New": "Autenticazione di Rete Centralizzata (AAA)",
  "SMTPProtocol": "Sicurezza E-Mail",
  "MTAConcept": "Sicurezza E-Mail",
  "SPFConcept_New": "Sicurezza E-Mail",
  "DKIMConcept_New": "Sicurezza E-Mail",
  "DMARCConcept_New": "Sicurezza E-Mail",
  "PhysicalSegmentationConcept": "Segmentazione e Isolamento di Rete",
  "AirGapConcept": "Segmentazione e Isolamento di Rete",
  "LogicalSegmentationConcept": "Segmentazione e Isolamento di Rete",
  "VLANConcept": "Segmentazione e Isolamento di Rete",
  "Layer3SwitchConcept": "Segmentazione e Isolamento di Rete",
  "InterVLANRoutingConcept": "Segmentazione e Isolamento di Rete",
  "NetSegmentationPortSecurityConcept": "Segmentazione e Isolamento di Rete",
  "IEEE8021XAuthConcept": "Autenticazione di Rete Centralizzata (AAA)",
  "TrafficCaptureTAPConcept": "Sicurezza & Monitoraggio degli Accessi di Rete",
  "ProxyTypesAdvancedConcept": "Dispositivi di Connettività e Relay",
  "ModernCloudNetArchitectures": "Segmentazione e Isolamento di Rete",
  "SDNConcept": "Software-Defined Networking (SDN)",
  "DataPlaneConcept": "Software-Defined Networking (SDN)",
  "ControlPlaneConcept": "Software-Defined Networking (SDN)",
  "ManagementPlaneConcept": "Software-Defined Networking (SDN)",
  "ResponsivenessPerformance": "Performance e Metriche di Rete",
  "LatencyPerformance": "Performance e Metriche di Rete",

  // Topic 3: Firewalls
  "NGFWFire": "Soluzioni di Sicurezza Integrate",
  "WAFFire": "Soluzioni di Sicurezza Integrate",
  "UTMFire": "Soluzioni di Sicurezza Integrate",
  "FirewallBase_New": "Tipi di Architetture Firewall",
  "StatefulFirewall_New": "Tipi di Architetture Firewall",
  "PacketFilteringFirewall_New": "Tipi di Architetture Firewall",
  "ProxyFirewall_New": "Tipi di Architetture Firewall",
  "StatelessFirewallConcept": "Tipi di Architetture Firewall",
  "DPIFire": "Soluzioni di Sicurezza Integrate",
  "AllowRule": "Configurazione Regole Firewall",
  "DenyRule": "Configurazione Regole Firewall",
  "InboundTraffic": "Configurazione Regole Firewall",
  "OutboundTraffic": "Configurazione Regole Firewall",
  "NetFirewallNATConcept": "Soluzioni di Sicurezza Integrate",
  "NGFWCapabilitiesConcept": "Soluzioni di Sicurezza Integrate",
  "SecurityZonesConcept": "Segmentazione e Isolamento di Rete",
  "FailClosed_New": "Comportamenti di Sicurezza e Controllo Rate",
  "FailOpen_New": "Comportamenti di Sicurezza e Controllo Rate",
  "RateBasedFiltering_New": "Comportamenti di Sicurezza e Controllo Rate",

  // Topic 4: Data Security
  "DataAtRestSec": "Stati del Ciclo di Vita del Dato",
  "DataInTransitSec": "Stati del Ciclo di Vita del Dato",
  "DataInUseSec": "Stati del Ciclo di Vita del Dato",
  "DataTypesConcept": "Classificazione e Tipologia dei Dati",
  "DataClassificationLevels": "Classificazione e Tipologia dei Dati",
  "EncryptionSec": "Tecniche di Protezione del Dato",
  "AppVsNetworkEncryptionConcept": "Tecniche di Protezione del Dato",
  "HashingSec": "Tecniche di Protezione del Dato",
  "TokenizationSec": "Tecniche di Protezione del Dato",
  "DataMaskingSec": "Tecniche di Protezione del Dato",
  "ObfuscationSec": "Tecniche di Protezione del Dato",
  "SanitizationSec_New": "Tecniche di Protezione del Dato",

  // Topic 5: Resilience & Recovery
  "AvailabilityRes": "Sistemi di Alta Disponibilità (HA)",
  "HighAvailabilityRes": "Sistemi di Alta Disponibilità (HA)",
  "ActiveActivePassiveRes": "Sistemi di Alta Disponibilità (HA)",
  "FailoverFailbackRes": "Sistemi di Alta Disponibilità (HA)",
  "SharedStorageRes": "Sistemi di Alta Disponibilità (HA)",
  "ScalabilityRes": "Sistemi di Alta Disponibilità (HA)",
  "PlatformDiversityRes": "Sistemi di Alta Disponibilità (HA)",
  "MultiCloudOutageRes": "Sistemi di Alta Disponibilità (HA)",
  "LoadBalancingRes": "Sistemi di Alta Disponibilità (HA)",
  "FaultToleranceConcept": "Sistemi di Alta Disponibilità (HA)",
  "ClusteringRes": "Sistemi di Alta Disponibilità (HA)",
  "CapacityPlanningRes": "Sistemi di Alta Disponibilità (HA)",
  "ParallelProcessingRes": "Sistemi di Alta Disponibilità (HA)",
  "SiteResiliencyRes": "Siti di Disaster Recovery",
  "DisasterRecoverySiteRes": "Siti di Disaster Recovery",
  "BusinessContinuityCOOPRes": "Siti di Disaster Recovery",
  "ManualProceduresRes": "Siti di Disaster Recovery",
  "HotSiteRes": "Siti di Disaster Recovery",
  "WarmSiteRes": "Siti di Disaster Recovery",
  "ColdSiteRes": "Siti di Disaster Recovery",
  "DisasterRecoveryRes": "Siti di Disaster Recovery",
  "BusinessContinuityRes": "Siti di Disaster Recovery",
  "BackupsRes": "Strategie di Backup e Replica",
  "ReplicationRes": "Strategie di Backup e Replica",
  "SynchronizationRes": "Strategie di Backup e Replica",
  "SnapshotsRes": "Strategie di Backup e Replica",
  "RecoveryRes": "Strategie di Backup e Replica",
  "EaseOfRecoveryConcept": "Strategie di Backup e Replica",
  "CorporateImageConcept": "Strategie di Backup e Replica",
  "RestoreAction": "Strategie di Backup e Replica",
  "RecoveryTestingRes": "Strategie di Backup e Replica",
  "OnSiteBackupRes": "Strategie di Backup e Replica",
  "OffSiteBackupRes": "Strategie di Backup e Replica",
  "BackupFrequencyRes": "Strategie di Backup e Replica",
  "BackupEncryptionRes": "Strategie di Backup e Replica",
  "JournalingRes": "Strategie di Backup e Replica",
  "UPSRes": "Resilienza Alimentazione Fisica",
  "GeneratorsRes": "Resilienza Alimentazione Fisica",
  "BackupPowerConcept": "Resilienza Alimentazione Fisica",
  "PowerResilience": "Resilienza Alimentazione Fisica",
  "PowerResiliencyRes": "Resilienza Alimentazione Fisica",
  "OfflineUPSRes": "Resilienza Alimentazione Fisica",
  "LineInteractiveUPSRes": "Resilienza Alimentazione Fisica",
  "OnlineUPSRes": "Resilienza Alimentazione Fisica",
  "GeneratorRes": "Resilienza Alimentazione Fisica",
  "SPOFConcept": "Analisi dei Punti di Guasto Singoli",
  "RedundancyConcept": "Analisi dei Punti di Guasto Singoli",
  "IoTConcept_New": "Dispositivi Speciali e IoT",
  "EmbeddedSystemConcept_New": "Dispositivi Speciali e IoT",
  "RTOSConcept_New": "Dispositivi Speciali e IoT",
  "SCADAConcept_New": "Dispositivi Speciali e IoT",
  "ICSConcept_New": "Dispositivi Speciali e IoT",

  // Topic 6: PBQ Dominio 3 Scenarios
  "VPNPBQ": "Scenari Pratici di Laboratorio (PBQ)",
  "FirewallRulesPBQ": "Scenari Pratici di Laboratorio (PBQ)",
  "SSHPBQ": "Scenari Pratici di Laboratorio (PBQ)",
  "WPA3PBQ": "Scenari Pratici di Laboratorio (PBQ)",
  "RADIUSPBQ": "Scenari Pratici di Laboratorio (PBQ)",
  "EncryptionVsHashingPBQ": "Scenari Pratici di Laboratorio (PBQ)",
  "BackupRecoveryPBQ": "Scenari Pratici di Laboratorio (PBQ)",

  // Domain 4
  "HardeningConcept": "Hardening di Sistemi e Dispositivi",
  "ServerHardening": "Hardening di Sistemi e Dispositivi",
  "WorkstationHardening": "Hardening di Sistemi e Dispositivi",
  "RouterHardening": "Hardening di Sistemi e Dispositivi",
  "SwitchHardening": "Hardening di Sistemi e Dispositivi",
  "MobileDeviceHardening": "Hardening di Sistemi e Dispositivi",
  "IoTHardening": "Hardening di Sistemi e Dispositivi",
  "AntivirusScanningConcept": "Hardening di Sistemi e Dispositivi",
  "SecurityBaselineRes": "Hardening di Sistemi e Dispositivi",
  "PatchManagementRes": "Hardening di Sistemi e Dispositivi",
  "GroupPolicyRes": "Hardening di Sistemi e Dispositivi",
  "MDM": "Dispositivi Mobili ed Enterprise (MDM)",
  "BYOD": "Dispositivi Mobili ed Enterprise (MDM)",
  "COPE": "Dispositivi Mobili ed Enterprise (MDM)",
  "CYOD": "Dispositivi Mobili ed Enterprise (MDM)",
  "VulnerabilityScan": "Metodologie di Vulnerability Assessment",
  "PenetrationTest": "Metodologie di Vulnerability Assessment", // Domain 4

  "CVE": "Metodologie di Vulnerability Assessment",
  "CVSS": "Metodologie di Vulnerability Assessment",
  "PatchManagement": "Metodologie di Vulnerability Assessment",
  "PatchConcept": "Metodologie di Vulnerability Assessment",
  "PatchAvailabilityConcept": "Metodologie di Vulnerability Assessment",
  "InabilityToPatchConcept": "Metodologie di Vulnerability Assessment",
  "EaseOfDeploymentConcept": "Automazione e Orchestrazione di Sicurezza",
  "AutomationConcept": "Automazione e Orchestrazione di Sicurezza",
  "ActiveReconnaissanceConcept": "Tecniche di Reconnaissance e Testing",
  "PassiveReconnaissanceConcept": "Tecniche di Reconnaissance e Testing",
  "VulnerabilityAssessmentConcept": "Tecniche di Reconnaissance e Testing",
  "BlackBoxTesting": "Tecniche di Reconnaissance e Testing",
  "WhiteBoxTesting": "Tecniche di Reconnaissance e Testing",
  "GreyBoxTesting": "Tecniche di Reconnaissance e Testing",
  "PassiveTestingConcept": "Tecniche di Reconnaissance e Testing",
  "SIEM": "Strumenti di Monitoraggio e Telemetria",
  "DLP": "Strumenti di Monitoraggio e Telemetria",
  "SCAP": "Strumenti di Monitoraggio e Telemetria",
  "SNMP": "Strumenti di Monitoraggio e Telemetria",
  "NetFlow": "Strumenti di Monitoraggio e Telemetria",
  "UBAConcept": "Strumenti di Monitoraggio e Telemetria",
  "ActivePassiveMonitoringConcept": "Strumenti di Monitoraggio e Telemetria",
  "SIEMComponentsConcept": "Strumenti di Monitoraggio e Telemetria",
  "FirewallLogs": "Analisi delle Tipologie di Log",
  "EndpointLogs": "Analisi delle Tipologie di Log",
  "SystemLogs": "Analisi delle Tipologie di Log",
  "IDSLogs": "Analisi delle Tipologie di Log",
  "IPSLogs": "Analisi delle Tipologie di Log",
  "ApplicationLogs": "Analisi delle Tipologie di Log",
  "PreparationPhase": "Fasi del Ciclo di Incident Response",
  "DetectionPhase": "Fasi del Ciclo di Incident Response",
  "AnalysisPhase": "Fasi del Ciclo di Incident Response",
  "ContainmentPhase": "Fasi del Ciclo di Incident Response",
  "EradicationPhase": "Fasi del Ciclo di Incident Response",
  "RecoveryPhase": "Fasi del Ciclo di Incident Response",
  "LessonsLearnedPhase": "Fasi del Ciclo di Incident Response",
  "IncidentResponseGeneralConcept": "Esercitazioni e Procedure di Risposta",
  "TabletopExercisesConcept": "Esercitazioni e Procedure di Risposta",
  "SimulationsConcept": "Esercitazioni e Procedure di Risposta",
  "FunctionalExercisesConcept": "Esercitazioni e Procedure di Risposta",
  "LiveDrillsConcept": "Esercitazioni e Procedure di Risposta",
  "ChainOfCustody": "Fasi di Digital Forensics",
  "AcquisitionForensics": "Fasi di Digital Forensics",
  "PreservationForensics": "Fasi di Digital Forensics",
  "ReportingForensics": "Fasi di Digital Forensics",
  "ProvisioningAutomation": "Automazione e Orchestrazione di Sicurezza",
  "APIAutomation": "Automazione e Orchestrazione di Sicurezza",
  "ScriptingAutomation": "Automazione e Orchestrazione di Sicurezza",
  "OrchestrationAutomation": "Automazione e Orchestrazione di Sicurezza",
  "PBQLogAnalysis": "Scenari Pratici di Analisi Incidenti (PBQ)",
  "PBQFirewallLogs": "Scenari Pratici di Analisi Incidenti (PBQ)",
  "PBQIncidentInvestigation": "Scenari Pratici di Analisi Incidenti (PBQ)",
  "PBQMalwareId": "Scenari Pratici di Analisi Incidenti (PBQ)",
  "PBQHostIsolation": "Scenari Pratici di Analisi Incidenti (PBQ)",
  "PBQAccessLogReview": "Scenari Pratici di Analisi Incidenti (PBQ)",

  // Domain 5
  "Governance": "Strutture di Governance e Ruoli dei Dati",
  "Boards": "Strutture di Governance e Ruoli dei Dati",
  "Committees": "Strutture di Governance e Ruoli dei Dati",
  "DataRolesGovernance": "Strutture di Governance e Ruoli dei Dati",
  "AUP": "Politiche di Sicurezza e Standard di Sviluppo",
  "SecurityPolicies": "Politiche di Sicurezza e Standard di Sviluppo",
  "IncidentResponsePolicy": "Politiche di Sicurezza e Standard di Sviluppo",
  "BCP": "Politiche di Sicurezza e Standard di Sviluppo",
  "DRP": "Politiche di Sicurezza e Standard di Sviluppo",
  "RTORes": "Politiche di Sicurezza e Standard di Sviluppo",
  "RPORes": "Politiche di Sicurezza e Standard di Sviluppo",
  "SDLC": "Politiche di Sicurezza e Standard di Sviluppo",
  "ChangeManagement": "Politiche di Sicurezza e Standard di Sviluppo",
  "TechnicalDebtConcept": "Politiche di Sicurezza e Standard di Sviluppo",
  "RiskAssessment": "Quadro di Riferimento del Rischio (Framework)",
  "RiskRegister": "Quadro di Riferimento del Rischio (Framework)",
  "RiskAppetite": "Quadro di Riferimento del Rischio (Framework)",
  "RiskTolerance": "Quadro di Riferimento del Rischio (Framework)",
  "SLE": "Valutazione Quantitativa del Rischio (Metrics)",
  "ALE": "Valutazione Quantitativa del Rischio (Metrics)",
  "ARO": "Valutazione Quantitativa del Rischio (Metrics)",
  "ExposureFactorEF": "Valutazione Quantitativa del Rischio (Metrics)",
  "ProbabilityConcept": "Valutazione Quantitativa del Rischio (Metrics)",
  "LikelihoodConcept": "Valutazione Quantitativa del Rischio (Metrics)",
  "RiskAnalysisConcept": "Metodologie di Analisi del Rischio",
  "ResidualRiskAnalysisConcept": "Metodologie di Analisi del Rischio",
  "QualitativeRiskAssessmentConcept": "Metodologie di Analisi del Rischio",
  "QuantitativeRiskAssessmentConcept": "Metodologie di Analisi del Rischio",
  "ThreatVectorAnalysisConcept": "Metodologie di Analisi del Rischio",
  "Accept": "Strategie di Trattamento del Rischio",
  "Transfer": "Strategie di Trattamento del Rischio",
  "RiskTransferConcept": "Strategie di Trattamento del Rischio",
  "CyberInsuranceConcept": "Strategie di Trattamento del Rischio",
  "Mitigate": "Strategie di Trattamento del Rischio",
  "Avoid": "Strategie di Trattamento del Rischio",
  "Compliance": "Conformità Normativa e Obblighi Legali",
  "Privacy": "Conformità Normativa e Obblighi Legali",
  "DueDiligence": "Conformità Normativa e Obblighi Legali",
  "DueCare": "Conformità Normativa e Obblighi Legali",
  "GDPRComplianceConcept": "Conformità Normativa e Obblighi Legali",
  "DataSovereigntyConcept": "Conformità Normativa e Obblighi Legali",
  "VendorAssessment": "Valutazione del Rischio Fornitori (Third Party)",
  "SupplyChainAnalysis": "Valutazione del Rischio Fornitori (Third Party)",
  "Questionnaires": "Valutazione del Rischio Fornitori (Third Party)",
  "SLA": "Accordi e Contratti di Servizio",
  "NDA": "Accordi e Contratti di Servizio",
  "MOU": "Accordi e Contratti di Servizio",
  "MOA": "Accordi e Contratti di Servizio",
  "BPA": "Accordi e Contratti di Servizio",
  "MSA": "Accordi e Contratti di Servizio",
  "SOW": "Accordi e Contratti di Servizio",
  "InternalAudit": "Valutazioni e Audit di Sicurezza",
  "ExternalAudit": "Valutazioni e Audit di Sicurezza",
  "RegulatoryAudit": "Valutazioni e Audit di Sicurezza",
  "PenetrationTestAudit": "Valutazioni e Audit di Sicurezza", // Domain 5
  "PeriodicReviewConcept": "Valutazioni e Audit di Sicurezza",
  "ContinuousAssessmentConcept": "Valutazioni e Audit di Sicurezza",
  "PhishingAwareness": "Consapevolezza e Addestramento Personale",
  "PasswordManagement": "Consapevolezza e Addestramento Personale",
  "SocialEngineering": "Consapevolezza e Addestramento Personale",
  "InsiderThreat": "Consapevolezza e Addestramento Personale",
  "AssetManagementRes": "Smaltimento e Declassificazione Asset",
  "AssetTrackingRes": "Smaltimento e Declassificazione Asset",
  "BarcodeRes": "Smaltimento e Declassificazione Asset",
  "RFIDRes": "Smaltimento e Declassificazione Asset",
  "MediaSanitizationRes": "Smaltimento e Declassificazione Asset",
  "PhysicalDestructionRes": "Smaltimento e Declassificazione Asset",
  "DegaussingRes": "Smaltimento e Declassificazione Asset",
  "CertificateOfDestructionRes": "Smaltimento e Declassificazione Asset",
  "DataRetentionRes": "Smaltimento e Declassificazione Asset",

  // New & Previous Keys Mapping
  // Domain 4 - Topic 1
  "CISBenchmarkRes": "Hardening di Sistemi e Dispositivi",
  "BenchmarkRes": "Hardening di Sistemi e Dispositivi",
  "AntivirusRes": "Hardening di Sistemi e Dispositivi",
  "AntiMalwareRes": "Hardening di Sistemi e Dispositivi",
  "QuarantineRes": "Hardening di Sistemi e Dispositivi",

  // Domain 4 - Topic 3
  "RulesOfEngagementRes": "Metodologie di Vulnerability Assessment",
  "ExploitationRes": "Metodologie di Vulnerability Assessment",
  "LateralMovementRes": "Metodologie di Vulnerability Assessment",
  "PersistenceRes": "Metodologie di Vulnerability Assessment",
  "PivotingRes": "Metodologie di Vulnerability Assessment",
  "SASTRes": "Metodologie di Vulnerability Assessment",
  "FuzzingRes": "Metodologie di Vulnerability Assessment",
  "PackageMonitoringRes": "Metodologie di Vulnerability Assessment",
  "ResponsibleDisclosureRes": "Metodologie di Vulnerability Assessment",
  "BugBountyRes": "Metodologie di Vulnerability Assessment",
  "ValidationOfRemediationRes": "Metodologie di Vulnerability Assessment",
  "RescanningRes": "Metodologie di Vulnerability Assessment",
  "VulnerabilityScannerRes": "Metodologie di Vulnerability Assessment",
  "PortScanRes": "Metodologie di Vulnerability Assessment",
  "VulnerabilityAssessmentRes": "Metodologie di Vulnerability Assessment",
  "RemediationRes": "Metodologie di Vulnerability Assessment",

  // Domain 4 - Topic 4
  "SecurityMonitoringRes": "Strumenti di Monitoraggio e Telemetria",
  "ComputingResourcesRes": "Strumenti di Monitoraggio e Telemetria",
  "LogAggregationRes": "Strumenti di Monitoraggio e Telemetria",
  "LogCorrelationRes": "Strumenti di Monitoraggio e Telemetria",
  "DashboardRes": "Strumenti di Monitoraggio e Telemetria",
  "AlertingRes": "Strumenti di Monitoraggio e Telemetria",
  "AlertTuningRes": "Strumenti di Monitoraggio e Telemetria",
  "AgentRes": "Strumenti di Monitoraggio e Telemetria",
  "AgentlessRes": "Strumenti di Monitoraggio e Telemetria",
  "DataLeakageRes": "Strumenti di Monitoraggio e Telemetria",
  "MIBRes": "Strumenti di Monitoraggio e Telemetria",
  "OIDRes": "Strumenti di Monitoraggio e Telemetria",
  "SNMPPollRes": "Strumenti di Monitoraggio e Telemetria",
  "SNMPTrapRes": "Strumenti di Monitoraggio e Telemetria",
  "PollingRes": "Strumenti di Monitoraggio e Telemetria",
  "TrapRes": "Strumenti di Monitoraggio e Telemetria",
  "ProbeRes": "Strumenti di Monitoraggio e Telemetria",
  "CollectorRes": "Strumenti di Monitoraggio e Telemetria",
  "FlowRecordsRes": "Strumenti di Monitoraggio e Telemetria",
  "CorrelationRes": "Strumenti di Monitoraggio e Telemetria",

  // Domain 5 - Topic 1 & 2
  "ExceptionRes": "Politiche di Sicurezza e Standard di Sviluppo",
  "ExemptionRes": "Politiche di Sicurezza e Standard di Sviluppo",

  // Domain 5 - Topic 3
  "EnvironmentalVariablesRes": "Metodologie di Analisi del Rischio",
  "OrganizationalImpactRes": "Metodologie di Analisi del Rischio",

  // Domain 5 - Topic 5
  "NISTRes": "Conformità Normativa e Obblighi Legali",

  // Domain 5 - Topic 8
  "AuditConceptRes": "Valutazioni e Audit di Sicurezza",
  "VerificationRes": "Valutazioni e Audit di Sicurezza",
  "ReportingRes": "Valutazioni e Audit di Sicurezza"
};

export const getSubgroupForSubtopic = (checklistKey: string): string | null => {
  return SUBGROUP_MAP[checklistKey] || null;
};
